//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BFAppLink, UIButton, UIColor, UILabel, UITapGestureRecognizer;

@interface BFAppLinkReturnToRefererView : UIView
{
    _Bool _explicitlyHidden;
    _Bool _closed;
    id <BFAppLinkReturnToRefererViewDelegate> _delegate;
    UIColor *_textColor;
    BFAppLink *_refererAppLink;
    unsigned long long _includeStatusBarInSize;
    UILabel *_labelView;
    UIButton *_closeButton;
    UITapGestureRecognizer *_insideTapGestureRecognizer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
- (void)closeButtonTapped:(id)arg1;
@property(nonatomic) _Bool closed; // @synthesize closed=_closed;
- (void)commonInit;
@property(nonatomic) __weak id <BFAppLinkReturnToRefererViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)drawCloseButtonImageWithColor:(id)arg1;
- (_Bool)hasRefererData;
@property(nonatomic) unsigned long long includeStatusBarInSize; // @synthesize includeStatusBarInSize=_includeStatusBarInSize;
- (void)initViews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *insideTapGestureRecognizer; // @synthesize insideTapGestureRecognizer=_insideTapGestureRecognizer;
- (struct CGSize)intrinsicContentSize;
@property(retain, nonatomic) UILabel *labelView; // @synthesize labelView=_labelView;
- (void)layoutSubviews;
- (id)localizedLabelForReferer:(id)arg1;
- (void)onTapInside:(id)arg1;
@property(retain, nonatomic) BFAppLink *refererAppLink; // @synthesize refererAppLink=_refererAppLink;
- (void)setHidden:(_Bool)arg1;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)statusBarHeight;
- (void)updateColors;
- (void)updateHidden;
- (void)updateLabelText;

@end

