//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface BFCancellationToken : NSObject
{
    _Bool _cancellationRequested;
    _Bool _disposed;
    NSMutableArray *_registrations;
    NSObject *_lock;
}

- (void).cxx_destruct;
- (void)cancel;
- (void)cancelAfterDelay:(int)arg1;
- (void)cancelPrivate;
- (void)dispose;
@property(nonatomic) _Bool disposed; // @synthesize disposed=_disposed;
- (id)init;
@property(readonly, nonatomic, getter=isCancellationRequested) _Bool cancellationRequested; // @synthesize cancellationRequested=_cancellationRequested;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
- (void)notifyCancellation:(id)arg1;
- (id)registerCancellationObserverWithBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableArray *registrations; // @synthesize registrations=_registrations;
- (void)throwIfDisposed;
- (void)unregisterRegistration:(id)arg1;

@end

