//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class CPTPlot, CPTTextStyle, NSAttributedString, NSString;

@interface CPTLegendEntry : NSObject <NSCoding>
{
    CPTPlot *plot;
    unsigned long long index;
    unsigned long long row;
    unsigned long long column;
    CPTTextStyle *textStyle;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSAttributedString *attributedTitle;
@property(nonatomic) unsigned long long column; // @synthesize column;
- (void)drawTitleInRect:(struct CGRect)arg1 inContext:(struct CGContext *)arg2 scale:(double)arg3;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) unsigned long long index; // @synthesize index;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) __weak CPTPlot *plot; // @synthesize plot;
@property(nonatomic) unsigned long long row; // @synthesize row;
@property(retain, nonatomic) CPTTextStyle *textStyle; // @synthesize textStyle;
@property(readonly, nonatomic) NSString *title; // @dynamic title;
@property(readonly, nonatomic) struct CGSize titleSize; // @dynamic titleSize;

@end

