//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTShadow.h"

@class CPTColor;

@interface CPTMutableShadow : CPTShadow
{
}


// Remaining properties
@property(nonatomic) double shadowBlurRadius; // @dynamic shadowBlurRadius;
@property(retain, nonatomic) CPTColor *shadowColor; // @dynamic shadowColor;
@property(nonatomic) struct CGSize shadowOffset; // @dynamic shadowOffset;
@end

