//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTBorderedLayer.h"

@class CPTAxisSet, CPTPlotArea, CPTPlotGroup;

@interface CPTPlotAreaFrame : CPTBorderedLayer
{
    CPTPlotArea *plotArea;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CPTAxisSet *axisSet; // @dynamic axisSet;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithLayer:(id)arg1;
@property(retain, nonatomic) CPTPlotArea *plotArea; // @synthesize plotArea;
@property(retain, nonatomic) CPTPlotGroup *plotGroup; // @dynamic plotGroup;
- (_Bool)pointingDeviceCancelledEvent:(struct UIEvent *)arg1;
- (_Bool)pointingDeviceDownEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (_Bool)pointingDeviceDraggedEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (_Bool)pointingDeviceUpEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (void)setGraph:(id)arg1;

@end

