//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBAutoupdaterReactService, FBAutoupdaterUpdate, NSString;

@protocol FBAutoupdaterReactServiceDelegate <NSObject>
- (void)autoupdaterReactService:(FBAutoupdaterReactService *)arg1 didRequestReactResource:(FBAutoupdaterUpdate *)arg2 lastActiveVersion:(NSString *)arg3;
- (void)autoupdaterReactServiceDidActivateResourceAfterLockingUpdate:(FBAutoupdaterReactService *)arg1;
@end

