//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBAutoupdaterUpdateDriverDelegate.h"

@class FBAutoupdater, FBAutoupdaterUpdate, NSDate, NSString;

@interface FBAutoupdaterReactService : NSObject <FBAutoupdaterUpdateDriverDelegate>
{
    FBAutoupdaterUpdate *_updateBeingProcessed;
    NSDate *_lastEventDate;
    NSString *_nativeBundleVersion;
    CDUnknownBlockType _loggerBlock;
    CDUnknownBlockType _exceptionInfoSetterBlock;
    FBAutoupdater *_autoupdater;
    id <FBAutoupdaterReactServiceDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_didActivateUpdate:(id)arg1;
- (id)_normalizeReactBundleVersion:(id)arg1;
@property(readonly, nonatomic) FBAutoupdater *autoupdater; // @synthesize autoupdater=_autoupdater;
- (void)autoupdaterDriver:(id)arg1 didFailUpdate:(id)arg2 error:(id)arg3;
- (void)autoupdaterDriver:(id)arg1 didFinishDownloadingUpdate:(id)arg2;
- (void)autoupdaterDriver:(id)arg1 didProcessUpdate:(id)arg2;
- (void)autoupdaterDriver:(id)arg1 didStartDownloadingUpdate:(id)arg2 expectedLength:(long long)arg3;
- (id)currentActiveReactBundleVersion;
- (void)dealloc;
@property(nonatomic) __weak id <FBAutoupdaterReactServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didActivateResourceAfterLockingUpdate;
- (void)didRequestReactResource;
- (id)initWithHost:(id)arg1 feed:(id)arg2 loggerBlock:(CDUnknownBlockType)arg3 exceptionInfoSetterBlock:(CDUnknownBlockType)arg4 otaResources:(id)arg5;
- (id)lastActivatedReactBundleVersion;
- (void)startService;
- (void)stopService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

