//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBOpenGLFilter.h"

#import "FBFilterCropping.h"
#import "NSCopying.h"

@class FBOpenGLProgram, NSString;

@interface FBBGRAtoYUVConverterFilter : FBOpenGLFilter <NSCopying, FBFilterCropping>
{
    _Bool _flip;
    _Bool _needsConfigure;
    FBOpenGLProgram *_uvProgram;
    NSString *_fullFragmentShader;
    NSString *_fullVertexShader;
    union _GLKMatrix4 _contentTransform;
    union _GLKMatrix4 _textureTransform;
}

- (void).cxx_destruct;
- (void)_render:(id)arg1 to:(id)arg2 program:(id)arg3 framebuffer:(unsigned int)arg4 framebufferSize:(struct CGSize)arg5;
- (void)configureProgram:(id)arg1;
@property(nonatomic) union _GLKMatrix4 contentTransform; // @synthesize contentTransform=_contentTransform;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)flip;
@property(copy, nonatomic) NSString *fullFragmentShader; // @synthesize fullFragmentShader=_fullFragmentShader;
- (id)fullFragmentShaderUV;
@property(copy, nonatomic) NSString *fullVertexShader; // @synthesize fullVertexShader=_fullVertexShader;
- (id)init;
- (unsigned long long)inputPixelFormat;
- (unsigned long long)outputPixelFormat;
- (void)render:(id)arg1 to:(id)arg2 program:(id)arg3 time:(CDStruct_1b6d18a9)arg4;
- (void)setFlip:(_Bool)arg1;
@property(nonatomic) union _GLKMatrix4 textureTransform; // @synthesize textureTransform=_textureTransform;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

