//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface FBFamilyDeviceIDReportInternal : NSObject
{
    NSObject<OS_dispatch_queue> *_serialReportingQueue;
    _Bool _accessed;
    NSString *_familyDeviceIDBeforeAppAccess;
    NSString *_familyDeviceIDAfterAppAccess;
    long long _accessingIDTimestamp;
    NSString *_backupID;
    long long _backupIDTimestamp;
    NSString *_appDeviceID;
    NSString *_backupAppDeviceID;
    _Bool _isRegeneratedByClientDetectionOnNewDevice;
}

- (void).cxx_destruct;
- (_Bool)FBFamilyIDDeviceIsJailbroken;
- (void)_generatePayloadForIDAccessAndLog:(CDUnknownBlockType)arg1;
- (void)_readBackupIDAndTimestamp;
- (void)_writeBackupID:(id)arg1 backupTimestamp:(long long)arg2;
- (void)detectedOtherAppRegenerateUponServer:(id)arg1 newFamilyDeviceID:(id)arg2 analyticsLogBlock:(CDUnknownBlockType)arg3;
- (void)didAccessFamilyDeviceID:(id)arg1 familyDeviceIDAfterAccess:(id)arg2 appDeviceID:(id)arg3 backupAppDeviceID:(id)arg4 isIdRegenByDetectingNewDevice:(_Bool)arg5;
- (void)didRegenerateByServerDetection:(id)arg1 familyDeviceIDAfterRegeneration:(id)arg2 analyticsLogBlock:(CDUnknownBlockType)arg3;
- (void)inNSUserDefaultsMakeFakeBackupID:(id)arg1 backupTimestamp:(long long)arg2;
- (id)initWithQueue:(id)arg1;
- (void)logAccessActivityWithBlock:(CDUnknownBlockType)arg1;
- (void)testGeneratePayload:(CDUnknownBlockType)arg1;

@end

