//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBFunnelPayload, NSString;

@interface FBFunnelAction : NSObject
{
    NSString *_actionName;
    NSString *_tag;
    double _relativeTime;
    FBFunnelPayload *_actionPayload;
}

+ (id)dictionaryToObject:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(readonly, copy, nonatomic) FBFunnelPayload *actionPayload; // @synthesize actionPayload=_actionPayload;
- (id)initWithActionName:(id)arg1 tag:(id)arg2 relativeTime:(double)arg3 actionPayload:(id)arg4;
- (id)objectToDictionary;
@property(readonly, nonatomic) double relativeTime; // @synthesize relativeTime=_relativeTime;
@property(readonly, copy, nonatomic) NSString *tag; // @synthesize tag=_tag;

@end

