//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable;

@interface FBKVOController : NSObject
{
    NSMapTable *_objectInfosMap;
    struct _opaque_pthread_mutex_t _lock;
    id _observer;
}

+ (id)controllerWithObserver:(id)arg1;
- (void).cxx_destruct;
- (void)_observe:(id)arg1 info:(id)arg2;
- (void)_unobserve:(id)arg1;
- (void)_unobserve:(id)arg1 info:(id)arg2;
- (void)_unobserveAll;
- (void)dealloc;
- (id)debugDescription;
- (id)initWithObserver:(id)arg1;
- (id)initWithObserver:(id)arg1 retainObserved:(_Bool)arg2;
- (void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 action:(SEL)arg4;
- (void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 block:(CDUnknownBlockType)arg4;
- (void)observe:(id)arg1 keyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 action:(SEL)arg4;
- (void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 block:(CDUnknownBlockType)arg4;
- (void)observe:(id)arg1 keyPaths:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
@property(readonly, nonatomic) __weak id observer; // @synthesize observer=_observer;
- (void)unobserve:(id)arg1;
- (void)unobserve:(id)arg1 keyPath:(id)arg2;
- (void)unobserveAll;

@end

