//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBRtmpSocket, NSError;

@protocol FBRtmpSocketDelegate <NSObject>
- (void)rtmpSocket:(FBRtmpSocket *)arg1 completedSpeedTestWithStatus:(struct FBNetworkSpeedTestStatus)arg2;
- (void)rtmpSocketOnConnectWithSpeedTestStatus:(struct FBNetworkSpeedTestStatus)arg1;
- (void)rtmpSocketOnError:(NSError *)arg1;
- (void)rtmpSocketRequireReconnectDueToError:(NSError *)arg1;
@end

