//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBWebViewProvider : NSObject
{
    id <FBWebViewAnalytics> _analytics;
    id <FBWebViewAlertHandler> _alertHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <FBWebViewAlertHandler> alertHandler; // @synthesize alertHandler=_alertHandler;
@property(retain, nonatomic) id <FBWebViewAnalytics> analytics; // @synthesize analytics=_analytics;
- (id)webViewForBackgroundProcessingWithEmptyFrameAndProcessPoolContainer:(id)arg1;
- (id)webViewWithFrame:(struct CGRect)arg1 processPoolContainer:(id)arg2;
- (id)webViewWithFrame:(struct CGRect)arg1 processPoolContainer:(id)arg2 implementation:(int)arg3;

@end

