//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FNFAssetResourceLoadingContentInformationRequest : NSObject
{
    _Bool _byteRangeAccessSupported;
    long long _contentLength;
    NSString *_contentType;
}

- (void).cxx_destruct;
@property(nonatomic) long long contentLength; // @synthesize contentLength=_contentLength;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(nonatomic, getter=isByteRangeAccessSupported) _Bool byteRangeAccessSupported; // @synthesize byteRangeAccessSupported=_byteRangeAccessSupported;

@end

