//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FNFAssetResourceLoadingContentInformationRequest, FNFAssetResourceLoadingDataRequest, NSDictionary, NSURLRequest, NSURLResponse;

@interface FNFAssetResourceLoadingRequest : NSObject
{
    CDUnknownBlockType _completionCallback;
    NSURLRequest *_request;
    FNFAssetResourceLoadingContentInformationRequest *_contentInformationRequest;
    FNFAssetResourceLoadingDataRequest *_dataRequest;
    NSURLResponse *_response;
    NSURLRequest *_redirect;
    NSDictionary *_metadataDictionary;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) FNFAssetResourceLoadingContentInformationRequest *contentInformationRequest; // @synthesize contentInformationRequest=_contentInformationRequest;
@property(readonly, nonatomic) FNFAssetResourceLoadingDataRequest *dataRequest; // @synthesize dataRequest=_dataRequest;
- (void)finishLoading;
- (void)finishLoadingWithError:(id)arg1;
- (void)finishLoadingWithMetadataDictionary:(id)arg1;
- (id)initWithContentInformationRequest:(id)arg1 dataRequest:(id)arg2 urlRequest:(id)arg3 completionCallback:(CDUnknownBlockType)arg4;
@property(copy, nonatomic) NSDictionary *metadataDictionary; // @synthesize metadataDictionary=_metadataDictionary;
@property(copy, nonatomic) NSURLRequest *redirect; // @synthesize redirect=_redirect;
@property(readonly, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) NSURLResponse *response; // @synthesize response=_response;

@end

