//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable;

@interface FNFIdleTimeoutManager : NSObject
{
    NSHashTable *_clients;
    id <FBSetIdleTimerApplicationProtocol> _application;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_setApplication:(id)arg1;
- (void)addNonIdlingClient:(id)arg1;
- (id)init;
- (void)removeNonIdlingClient:(id)arg1;

@end

