//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FNFLiveDashPrefetchedAssetSet, NSMutableDictionary;

@interface FNFLiveDashAssetPrefetcher : NSObject
{
    FNFLiveDashPrefetchedAssetSet *_prefetchedAssets;
    NSMutableDictionary *_timers;
    id <FNFDashAssetPrefetcherLogger> _logger;
    struct mutex _mutex;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_logAndReleaseUnusedAssetWithUrl:(id)arg1;
- (id)initWithLogger:(id)arg1;
- (id)newAssetForURL:(id)arg1 creatorBlock:(CDUnknownBlockType)arg2;
- (void)prefetchURL:(id)arg1 timeManager:(id)arg2 delayBeforeDeallocInMs:(unsigned int)arg3 creatorBlock:(CDUnknownBlockType)arg4;

@end

