//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate;

@interface FNFMediaPresentationDescription : NSObject
{
    _Bool _isDynamic;
    _Bool _isFragmented;
    unsigned int _durationMS;
    long long _videoType;
    double _publishFrameTimeMS;
    NSDate *_availabilityEndTime;
    NSArray *_videoTracks;
    NSArray *_audioTracks;
}

+ (id)presentationDescriptionWithContentsOfXml:(id)arg1 mpdUrl:(id)arg2 segmentsFromEndToStartForLive:(unsigned int)arg3 error:(id *)arg4;
+ (id)urlFromBase:(id)arg1 suffix:(id)arg2;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *audioTracks; // @synthesize audioTracks=_audioTracks;
@property(readonly, copy, nonatomic) NSDate *availabilityEndTime; // @synthesize availabilityEndTime=_availabilityEndTime;
@property(readonly, nonatomic) unsigned int durationMS; // @synthesize durationMS=_durationMS;
- (id)initWithAudioTracks:(id)arg1 videoTracks:(id)arg2 isDynamic:(_Bool)arg3 isFragmented:(_Bool)arg4 durationMS:(unsigned int)arg5 videoType:(long long)arg6 publishFrameTime:(unsigned long long)arg7 availabilityEndTime:(id)arg8;
@property(readonly, nonatomic) _Bool isDynamic; // @synthesize isDynamic=_isDynamic;
@property(readonly, nonatomic) _Bool isFragmented; // @synthesize isFragmented=_isFragmented;
@property(readonly, nonatomic) double publishFrameTimeMS; // @synthesize publishFrameTimeMS=_publishFrameTimeMS;
@property(readonly, copy, nonatomic) NSArray *videoTracks; // @synthesize videoTracks=_videoTracks;
@property(readonly, nonatomic) long long videoType; // @synthesize videoType=_videoType;

@end

