//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGAccountRecoveryEmailConfirmationScrollView, IGRetroRegistrationBackgroundView;

@interface IGAccountRecoveryEmailConfirmationView : UIView
{
    IGAccountRecoveryEmailConfirmationScrollView *_confirmationScrollView;
    IGRetroRegistrationBackgroundView *_backgroundView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGRetroRegistrationBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) IGAccountRecoveryEmailConfirmationScrollView *confirmationScrollView; // @synthesize confirmationScrollView=_confirmationScrollView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

