//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGViewController, UIScrollView;

@protocol IGActivityFeedViewControllerProtocol <NSObject>
@property(nonatomic) __weak IGViewController *containingViewController;
@property(nonatomic) __weak id <IGActivityFeedViewControllerDelegate> delegate;
- (void)fetchData;
- (unsigned long long)fetchState;
- (UIScrollView *)scrollView;
@end

