//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedConfigurationType.h"

@class IGDefaultFeedConfiguration, IGMainFeedConfiguration, NSString;

@interface IGAdRatingFeedConfiguration : NSObject <IGFeedConfigurationType>
{
    IGDefaultFeedConfiguration *_defaultFeedConfiguration;
    IGMainFeedConfiguration *_mainFeedConfiguration;
}

- (void).cxx_destruct;
- (_Bool)allowAutoPlay;
- (id)analyticsModule;
@property(readonly, nonatomic) IGDefaultFeedConfiguration *defaultFeedConfiguration; // @synthesize defaultFeedConfiguration=_defaultFeedConfiguration;
- (id)feedAccessibilityIdentifier;
- (id)init;
@property(readonly, nonatomic) IGMainFeedConfiguration *mainFeedConfiguration; // @synthesize mainFeedConfiguration=_mainFeedConfiguration;
- (_Bool)shouldAutoplayVideos;
- (_Bool)shouldPrefetchMediaForFeedItems;
- (_Bool)supportSaveTooltip;
- (_Bool)supportShareTooltip;
- (_Bool)supportStoryRingInHeader;
- (unsigned long long)tombstoneTypeForFeed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

