//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "IGAdsManagerListDataReceiving.h"

@class IGAdManagerEmptyListView, IGAdsListViewModel, IGAdsManagerDataProvider, IGAdsManagerLogger, IGRefreshControl, IGUserSession, NSString;

@interface IGAdsManagerListViewController : IGGroupedTableViewController <IGAdsManagerListDataReceiving>
{
    _Bool _isFirstLoad;
    _Bool _isVerifyingFacebookToken;
    IGUserSession *_userSession;
    IGAdsManagerDataProvider *_dataProvider;
    IGAdsListViewModel *_adsList;
    IGRefreshControl *_refreshControl;
    IGAdManagerEmptyListView *_emptyListView;
    IGAdsManagerLogger *_logger;
}

- (void).cxx_destruct;
- (id)adViewModelForIndexPath:(id)arg1;
- (struct NSArray *)adsArrayForSection:(long long)arg1;
@property(retain, nonatomic) IGAdsListViewModel *adsList; // @synthesize adsList=_adsList;
- (void)adsManagerListDataProvider:(id)arg1 didFailWithError:(id)arg2;
- (void)adsManagerListDataProvider:(id)arg1 didReceiveAdsList:(id)arg2;
- (id)analyticsModule;
- (_Bool)canHostInlineGallery:(_Bool)arg1;
@property(readonly, nonatomic) IGAdsManagerDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void)didFinishFetchingWithAdsManagerListDataProvider:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
@property(retain, nonatomic) IGAdManagerEmptyListView *emptyListView; // @synthesize emptyListView=_emptyListView;
- (id)initWithLogger:(id)arg1 userSession:(id)arg2;
@property(nonatomic) _Bool isFirstLoad; // @synthesize isFirstLoad=_isFirstLoad;
@property(nonatomic) _Bool isVerifyingFacebookToken; // @synthesize isVerifyingFacebookToken=_isVerifyingFacebookToken;
@property(readonly, nonatomic) IGAdsManagerLogger *logger; // @synthesize logger=_logger;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onRefreshTapped:(id)arg1;
@property(retain, nonatomic) IGRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setNeedsFetchForFeedItemsInOldAdList:(id)arg1 newAdList:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForHeaderInSection:(long long)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willStartFetchingWithAdsManagerListDataProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

