//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGAdRatingWebViewCellFactory : NSObject
{
}

+ (id)cellFromCollectionView:(id)arg1 indexPath:(id)arg2;
+ (void)configureCell:(id)arg1 webView:(id)arg2;
+ (void)registerCellWithCollectionView:(id)arg1;
+ (struct CGSize)sizeForCellWithAvailableWidth:(double)arg1;
+ (struct CGSize)sizeForCellWithAvailableWidth:(double)arg1 webView:(id)arg2;

@end

