//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGAmebaAuthDelegate.h"
#import "IGAmebaThemesDelegate.h"
#import "IGServiceHelperProtocol.h"

@class IGUserDefaults, NSDictionary, NSString;

@interface IGAmebaHelper : NSObject <IGAmebaAuthDelegate, IGAmebaThemesDelegate, IGServiceHelperProtocol>
{
    IGUserDefaults *_sessionUserDefaults;
    id <IGAPIClient> _networker;
    NSString *_accessToken;
    NSDictionary *_currentThemeSetting;
    NSString *_username;
    NSString *_refreshToken;
}

+ (id)accessTokenKey;
+ (void)clearForUserPK:(id)arg1;
+ (_Bool)hasAdvancedOptions;
+ (id)serviceName;
+ (id)sharedHelperForUserSession:(id)arg1;
+ (id)shortServiceName;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void)amebaAuthController:(id)arg1 didLoginWithCode:(id)arg2;
- (void)amebaAuthControllerLoginFailed:(id)arg1;
@property(readonly, nonatomic) NSString *authURLString;
@property(readonly, nonatomic) NSString *callbackURLString;
@property(readonly, nonatomic) NSString *clientID;
@property(copy, nonatomic) NSDictionary *currentThemeSetting; // @synthesize currentThemeSetting=_currentThemeSetting;
- (id)currentUsername;
- (void)fetchTokenFinished:(id)arg1;
- (_Bool)hasEverBeenConfigured;
- (id)initWithSessionUserDefaults:(id)arg1 networker:(id)arg2;
- (_Bool)isAvailableInCurrentLocale;
- (_Bool)isConfigurable;
- (_Bool)isConfigured;
- (void)logout;
- (void)logoutAndUnlink;
- (_Bool)needsToReauthorize;
@property(retain, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
- (void)onFetchTokenFailed;
- (void)reauthorizationNeedsLogin;
- (void)reauthorize;
- (void)reauthorizeIfNeeded;
@property(copy, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
- (_Bool)requiresLocationCoordinate;
@property(retain, nonatomic) IGUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
- (void)setAccessAndRefreshToken:(id)arg1 expirationInSeconds:(int)arg2 refreshToken:(id)arg3;
- (void)setCurrentUsername:(id)arg1;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (id)sharingInfo;
- (_Bool)supportsMediaType:(long long)arg1;
- (void)themesViewController:(id)arg1 didSelectTheme:(id)arg2;
- (id)viewControllerForAdvancedOptionsWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

