//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGAnalyticsLogFileManager, IGAnalyticsUploader, IGSequenceNumberGenerator, NSObject<OS_dispatch_queue>, NSString, UIApplication;

@interface IGAnalyticsNoLatencyLogger : NSObject
{
    NSString *_APIKey;
    NSString *_clientToken;
    NSString *_appID;
    NSString *_deviceID;
    _Bool _aldrinMode;
    NSObject<OS_dispatch_queue> *_queue;
    IGSequenceNumberGenerator *_sequenceNumberGenerator;
    _Bool _uploadingData;
    NSString *_userID;
    NSString *_facebookID;
    IGAnalyticsLogFileManager *_fileManager;
    IGAnalyticsUploader *_uploader;
    UIApplication *_application;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIApplication *application; // @synthesize application=_application;
- (double)currentTimestamp;
@property(copy, nonatomic) NSString *facebookID; // @synthesize facebookID=_facebookID;
@property(retain, nonatomic) IGAnalyticsLogFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (id)initWithAPIKey:(id)arg1 clientToken:(id)arg2 appID:(id)arg3 deviceID:(id)arg4 userID:(id)arg5 facebookID:(id)arg6 aldrinMode:(_Bool)arg7 application:(id)arg8 queue:(id)arg9 logFileDirectory:(id)arg10;
- (void)logEvent:(id)arg1;
@property(retain, nonatomic) IGAnalyticsUploader *uploader; // @synthesize uploader=_uploader;
@property _Bool uploadingData; // @synthesize uploadingData=_uploadingData;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
- (void)uploadEventsIfNecessary;
- (void)uploadSessionData:(id)arg1 session:(id)arg2 allowableRetries:(long long)arg3;

@end

