//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAGradientLayer.h"

@interface IGAppColorGradientLayer : CAGradientLayer
{
}

+ (struct CGPoint)endPoint;
+ (id)gradientColors;
+ (id)gradientLocations;
+ (id)layer;
+ (struct CGPoint)startPoint;

@end

