//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGAutocompleteAbstractStore.h"

#import "IGAutocompleteAbstractStoreProtocol.h"

@class NSArray, NSMutableOrderedSet, NSString;

@interface IGAutocompletePlacesStore : IGAutocompleteAbstractStore <IGAutocompleteAbstractStoreProtocol>
{
    NSMutableOrderedSet *_places;
}

+ (id)archiveURLForUserPK:(id)arg1;
+ (void)clearForUserPK:(id)arg1;
+ (id)regex;
- (void).cxx_destruct;
- (_Bool)_addPlaceToRecent:(id)arg1;
@property(readonly, nonatomic) NSArray *allPlaces;
- (void)archive;
- (id)archiveURL;
- (void)clearHistory;
- (id)initWithCurrentUser:(id)arg1 sessionUserDefaults:(id)arg2 networker:(id)arg3;
@property(readonly, nonatomic) NSMutableOrderedSet *places; // @synthesize places=_places;
@property(readonly, nonatomic) NSArray *recentPlaces;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

