//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGImageFilter.h"

@class IGSurface;

@interface IGBasicAdjustFilter : IGImageFilter
{
    _Bool _sharpenDisabled;
    _Bool _sharpenSurfaceDirty;
    _Bool _shadowsSurfaceDirty;
    double _brightness;
    double _saturation;
    double _contrast;
    double _temperature;
    double _vignette;
    double _fade;
    double _highlights;
    double _shadows;
    double _sharpen;
    double _tintShadowsIntensity;
    double _tintHighlightsIntensity;
    IGSurface *_blurredSurface;
    IGSurface *_sharpenBlurSurface;
    union _GLKVector3 _tintShadowsColor;
    union _GLKVector3 _tintHighlightsColor;
}

+ (id)filterName;
+ (long long)filterType;
- (void).cxx_destruct;
@property(retain, nonatomic) IGSurface *blurredSurface; // @synthesize blurredSurface=_blurredSurface;
@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
- (void)clearCachesNotOfSize:(struct CGSize)arg1;
- (void)configureProgram:(id)arg1;
@property(nonatomic) double contrast; // @synthesize contrast=_contrast;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dirtyInternalCaches;
@property(nonatomic) double fade; // @synthesize fade=_fade;
- (id)fragmentFunctions;
- (id)fragmentShader;
- (id)fragmentShaderPrecision;
- (_Bool)hasAdjustedValues;
@property(nonatomic) double highlights; // @synthesize highlights=_highlights;
- (void)render:(id)arg1 to:(id)arg2;
- (id)samplers;
@property(nonatomic) double saturation; // @synthesize saturation=_saturation;
@property(nonatomic) double shadows; // @synthesize shadows=_shadows;
@property(nonatomic) _Bool shadowsSurfaceDirty; // @synthesize shadowsSurfaceDirty=_shadowsSurfaceDirty;
@property(nonatomic) double sharpen; // @synthesize sharpen=_sharpen;
@property(retain, nonatomic) IGSurface *sharpenBlurSurface; // @synthesize sharpenBlurSurface=_sharpenBlurSurface;
@property(nonatomic) _Bool sharpenDisabled; // @synthesize sharpenDisabled=_sharpenDisabled;
@property(nonatomic) _Bool sharpenSurfaceDirty; // @synthesize sharpenSurfaceDirty=_sharpenSurfaceDirty;
@property(nonatomic) double temperature; // @synthesize temperature=_temperature;
@property(nonatomic) union _GLKVector3 tintHighlightsColor; // @synthesize tintHighlightsColor=_tintHighlightsColor;
@property(nonatomic) double tintHighlightsIntensity; // @synthesize tintHighlightsIntensity=_tintHighlightsIntensity;
@property(nonatomic) union _GLKVector3 tintShadowsColor; // @synthesize tintShadowsColor=_tintShadowsColor;
@property(nonatomic) double tintShadowsIntensity; // @synthesize tintShadowsIntensity=_tintShadowsIntensity;
@property(nonatomic) double vignette; // @synthesize vignette=_vignette;

@end

