//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserSession, NSString;

@interface IGBoostPostLogger : NSObject
{
    NSString *_entryPoint;
    NSString *_waterfallID;
    IGUserSession *_userSession;
}

+ (id)loggerWithEntryPoint:(id)arg1 userSession:(id)arg2;
- (void).cxx_destruct;
- (void)didEnterMediaSelectionView;
- (void)didTapClose;
- (void)didTapEntryPoint;
@property(readonly, copy, nonatomic) NSString *entryPoint; // @synthesize entryPoint=_entryPoint;
- (void)failToLoadMediaSelectionViewWithErrorMessage:(id)arg1;
- (id)initWithEntryPoint:(id)arg1 userSession:(id)arg2;
- (void)logEvent:(id)arg1 additionalFields:(id)arg2;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, copy, nonatomic) NSString *waterfallID; // @synthesize waterfallID=_waterfallID;

@end

