//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGImageFilter.h"

@class IGSurface;

@interface IGBoxBlurFilter : IGImageFilter
{
    union _GLKVector2 _blurVector;
    IGSurface *_intermediateTexture;
    unsigned long long _kernelSize;
}

- (void).cxx_destruct;
- (void)configureProgram:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)fragmentFunctions;
- (id)fragmentShader;
- (id)fragmentShaderPrecision;
- (id)init;
- (id)initWithKernelSize:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long kernelSize; // @synthesize kernelSize=_kernelSize;
- (void)render:(id)arg1 to:(id)arg2 program:(id)arg3;

@end

