//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class IGBoostPostLogger, IGCameraNavigationControllerTransitionDelegate, IGFeedItem, IGUserSession, NSString;

@interface IGBoostPostViewController : UIViewController
{
    IGFeedItem *_feedItem;
    NSString *_analyticsModule;
    IGCameraNavigationControllerTransitionDelegate *_webviewTransitionDelegate;
    IGBoostPostLogger *_logger;
    IGUserSession *_userSession;
    UIViewController *_contentViewController;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
@property(retain, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void)dealloc;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (id)getContentViewController;
- (id)initWithFeedItem:(id)arg1 analyticsModule:(id)arg2 webviewTransitionDelegate:(id)arg3 boostPostLogger:(id)arg4 userSession:(id)arg5;
@property(readonly, nonatomic) IGBoostPostLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
@property(readonly, nonatomic) IGCameraNavigationControllerTransitionDelegate *webviewTransitionDelegate; // @synthesize webviewTransitionDelegate=_webviewTransitionDelegate;

@end

