//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGButton, UILabel;

@interface IGBusinessConversionNoPagesView : UIView
{
    id <IGBusinessConversionNoPagesViewDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    IGButton *_createPageButton;
    UILabel *_disclaimerLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGButton *createPageButton; // @synthesize createPageButton=_createPageButton;
@property(nonatomic) __weak id <IGBusinessConversionNoPagesViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapCreatePageButton;
@property(retain, nonatomic) UILabel *disclaimerLabel; // @synthesize disclaimerLabel=_disclaimerLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)newSecondaryLabel;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

