//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface IGBusinessNotice : NSObject <NSCoding>
{
    NSString *_title;
    NSString *_body;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *body; // @synthesize body=_body;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTitle:(id)arg1 body:(id)arg2;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;

@end

