//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGBusinessConversionActivityFeedView;

@interface IGBusinessConversionActivityFeedListViewCell : UICollectionViewCell
{
    IGBusinessConversionActivityFeedView *_activityFeedView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGBusinessConversionActivityFeedView *activityFeedView; // @synthesize activityFeedView=_activityFeedView;
- (void)configureCellWithUserProfileImageURL:(id)arg1 reminderText:(id)arg2 businessConversionActivityFeedDelegate:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

