//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGBusinessPageSelectionViewController, NSArray, NSError, UITableView;

@protocol IGBusinessPageSelectionDelegate <NSObject>
- (_Bool)isAdmin;
- (void)pageSelectionView:(UITableView *)arg1 didSelectRowAtIndex:(long long)arg2;
- (void)pageSelectionViewController:(IGBusinessPageSelectionViewController *)arg1 didEndFetchingPages:(NSArray *)arg2 oldPages:(NSArray *)arg3 andError:(NSError *)arg4;
- (void)pageSelectionViewControllerDidClickCreateOnePage:(IGBusinessPageSelectionViewController *)arg1;
- (void)pageSelectionViewControllerDidStartFetchingPages:(IGBusinessPageSelectionViewController *)arg1;
- (_Bool)shouldDefaultSelection;
@end

