//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGCustomViewController.h"
#import "IGMediaCaptureViewControllerDelegate.h"
#import "UINavigationBarDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class IGEditorViewController, IGUserSession, NSString, UINavigationBar, UIView;

@interface IGCameraNavigationController : IGViewController <IGMediaCaptureViewControllerDelegate, UIViewControllerTransitioningDelegate, UINavigationBarDelegate, IGCustomViewController>
{
    _Bool _isTranslucent;
    double _verticalOffset;
    id <IGCameraNavigationControllerDelegate> _delegate;
    UINavigationBar *_navigationBar;
    UIView *_containerView;
    UIView *_navigationBarShadow;
    IGEditorViewController *_currentEditor;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
- (id)analyticsModule;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak IGEditorViewController *currentEditor; // @synthesize currentEditor=_currentEditor;
- (void)dealloc;
@property(nonatomic) __weak id <IGCameraNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)handlesTransitionToEditor;
- (id)ig_keyViewControllers;
- (id)initWithMetadata:(id)arg1 captureFlowViewModel:(id)arg2 mode:(long long)arg3 userSession:(id)arg4;
@property(nonatomic, getter=isNavigationBarHidden) _Bool navigationBarHidden;
@property(nonatomic) _Bool isTranslucent; // @synthesize isTranslucent=_isTranslucent;
- (void)makeNavigationBarClear:(_Bool)arg1;
- (void)mediaCaptureViewController:(id)arg1 didProduceComposition:(id)arg2;
- (void)mediaCaptureViewController:(id)arg1 didProducePhoto:(id)arg2 withMediaMetadata:(id)arg3 cropRect:(struct CGRect)arg4 fromOrigin:(long long)arg5;
- (void)mediaCaptureViewController:(id)arg1 didProduceVideoComposition:(id)arg2 fromOrigin:(long long)arg3;
- (void)mediaCaptureViewController:(id)arg1 didSelectDraft:(id)arg2;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (void)navigationBar:(id)arg1 didPopItem:(id)arg2;
- (void)navigationBar:(id)arg1 didPushItem:(id)arg2;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (_Bool)navigationBar:(id)arg1 shouldPushItem:(id)arg2;
@property(retain, nonatomic) UIView *navigationBarShadow; // @synthesize navigationBarShadow=_navigationBarShadow;
- (void)popToRootViewControllerAndResetMediaMetadataWithNewDraft:(id)arg1;
- (void)popViewControllerAnimated:(_Bool)arg1;
- (void)popViewControllerWithPoppedToViewWillBeVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (long long)preferredStatusBarUpdateAnimation;
- (_Bool)prefersStatusBarHidden;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)pushViewController:(id)arg1 viewWillBeVisible:(_Bool)arg2 animated:(_Bool)arg3;
- (void)pushViewControllersForDraft:(id)arg1;
- (void)reloadNavigationItem:(id)arg1;
- (void)reloadNavigationItem:(id)arg1 animated:(_Bool)arg2;
@property(nonatomic) double verticalOffset; // @synthesize verticalOffset=_verticalOffset;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

