//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGQuickCamRecordingIndicatorView, UIImageView;

@interface IGCameraButtonModeCell : UICollectionViewCell
{
    UIImageView *_imageView;
    IGQuickCamRecordingIndicatorView *_recordingIndicatorView;
}

- (void).cxx_destruct;
- (void)configureWithMode:(long long)arg1;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
@property(readonly, nonatomic) IGQuickCamRecordingIndicatorView *recordingIndicatorView; // @synthesize recordingIndicatorView=_recordingIndicatorView;
- (void)updateForRecordingState:(_Bool)arg1;

@end

