//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, UIPanGestureRecognizer, UIView;

@interface IGCellSwipeActionManager : NSObject <UIGestureRecognizerDelegate>
{
    _Bool _dragging;
    _Bool _shouldDrag;
    _Bool _didCompleteExpandAnimation;
    _Bool _isShowingActions;
    id <IGCellSwipeActionManagerActionDelegate> _actionDelegate;
    id <IGCellSwipeActionManagerPanningDelegate> _panningDelegate;
    id <IGCellSwipeActionManagerSwipingDelegate> _swipingDelegate;
    NSArray *_actionButtons;
    NSArray *_accessibleElements;
    UIView *_hostingView;
    double _actionButtonWidth;
    UIView *_actionButtonContainerView;
    UIView *_contentScreenshotView;
    UIView *_swipeActionsContainerView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    double _totalTranslationX;
    double _contentScreenshotViewBeginningX;
    double _swipeCompletionThresholdX;
    unsigned long long _panState;
    struct CGRect _originalActionButtonContainerViewFrame;
}

- (void).cxx_destruct;
- (id)accessibileElements;
@property(retain, nonatomic) NSArray *accessibleElements; // @synthesize accessibleElements=_accessibleElements;
@property(retain, nonatomic) UIView *actionButtonContainerView; // @synthesize actionButtonContainerView=_actionButtonContainerView;
@property(nonatomic) double actionButtonWidth; // @synthesize actionButtonWidth=_actionButtonWidth;
@property(readonly, nonatomic) NSArray *actionButtons; // @synthesize actionButtons=_actionButtons;
@property(nonatomic) __weak id <IGCellSwipeActionManagerActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (double)actionsViewButtonsTotalWidth;
- (id)addBasicAnimationToView:(id)arg1 toFrame:(struct CGRect)arg2 duration:(double)arg3 name:(id)arg4;
- (id)addSpringAnimationToView:(id)arg1 toFrame:(struct CGRect)arg2 name:(id)arg3;
- (void)animateSwipeWithVelocity:(struct CGPoint)arg1;
- (double)calculateSwipeCompletionThresholdForHostingViewFrame:(struct CGRect)arg1 totalButtonWidth:(double)arg2 buttonWidth:(double)arg3;
- (void)cellDidPanWithVelocity:(struct CGPoint)arg1;
@property(retain, nonatomic) UIView *contentScreenshotView; // @synthesize contentScreenshotView=_contentScreenshotView;
@property(nonatomic) double contentScreenshotViewBeginningX; // @synthesize contentScreenshotViewBeginningX=_contentScreenshotViewBeginningX;
- (id)createAccessibilityCloseButton;
- (id)createActionsButtonViewWithBounds:(struct CGRect)arg1;
- (void)dealloc;
- (struct CGRect)defaultFrameForButtonAtIndex:(unsigned long long)arg1 buttons:(id)arg2 buttonWidth:(double)arg3 containerView:(id)arg4;
@property(nonatomic) _Bool didCompleteExpandAnimation; // @synthesize didCompleteExpandAnimation=_didCompleteExpandAnimation;
- (void)fillActionsButtonContainerView:(id)arg1 withButtonViews:(id)arg2 buttonWidth:(double)arg3;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleActionButtonFramesForPanState:(unsigned long long)arg1 deltaX:(double)arg2;
- (void)handleDoubleTapGestureRecognizer:(id)arg1;
- (void)handleHideActionView:(id)arg1;
- (void)handlePanGestureRecognizer:(id)arg1;
- (void)hideActionView:(_Bool)arg1;
- (void)hideActionView:(_Bool)arg1 duration:(double)arg2;
- (void)hideActionViewWithVelocity:(struct CGPoint)arg1;
@property(nonatomic) __weak UIView *hostingView; // @synthesize hostingView=_hostingView;
- (id)initWithHostingView:(id)arg1 actionButtons:(id)arg2 actionButtonWidth:(double)arg3;
@property(nonatomic, getter=isDragging) _Bool dragging; // @synthesize dragging=_dragging;
@property(nonatomic) _Bool isShowingActions; // @synthesize isShowingActions=_isShowingActions;
@property(nonatomic) struct CGRect originalActionButtonContainerViewFrame; // @synthesize originalActionButtonContainerViewFrame=_originalActionButtonContainerViewFrame;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) unsigned long long panState; // @synthesize panState=_panState;
- (unsigned long long)panStateFromSwipeViewFrame:(struct CGRect)arg1;
@property(nonatomic) __weak id <IGCellSwipeActionManagerPanningDelegate> panningDelegate; // @synthesize panningDelegate=_panningDelegate;
- (void)peekActionView;
- (void)removeSwipingView;
@property(nonatomic) _Bool shouldDrag; // @synthesize shouldDrag=_shouldDrag;
@property(retain, nonatomic) UIView *swipeActionsContainerView; // @synthesize swipeActionsContainerView=_swipeActionsContainerView;
@property(nonatomic) double swipeCompletionThresholdX; // @synthesize swipeCompletionThresholdX=_swipeCompletionThresholdX;
@property(nonatomic) __weak id <IGCellSwipeActionManagerSwipingDelegate> swipingDelegate; // @synthesize swipingDelegate=_swipingDelegate;
@property(nonatomic) double totalTranslationX; // @synthesize totalTranslationX=_totalTranslationX;
- (void)setupSwipingView;
- (void)showActionView:(_Bool)arg1;
- (void)showActionView:(_Bool)arg1 duration:(double)arg2;
- (void)showActionViewWithVelocity:(struct CGPoint)arg1;
- (unsigned long long)swipeCompletionActionForPanDirection:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool swipeToActionDisabled;
- (double)swipeViewHorizontalDistanceFromActionView;
- (void)updateButtonWidth:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

