//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"

@class NSArray, NSString;

@interface IGChannelHomeRowItemModel : NSObject <IGListDiffable>
{
    NSArray *_channels;
    NSString *_pk;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *channels; // @synthesize channels=_channels;
- (id)diffIdentifier;
- (unsigned long long)hash;
- (id)initWithChannels:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;
@property(readonly, copy, nonatomic) NSString *pk; // @synthesize pk=_pk;

@end

