//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGChallengeResponse : NSObject
{
    _Bool _showReactNativeFlow;
    _Bool _showCancelButton;
    NSString *_checkpointURLString;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *checkpointURLString; // @synthesize checkpointURLString=_checkpointURLString;
- (id)initWithCheckpointURLString:(id)arg1 showReactNativeFlow:(_Bool)arg2 showCancelButton:(_Bool)arg3;
@property(nonatomic) _Bool showCancelButton; // @synthesize showCancelButton=_showCancelButton;
@property(nonatomic) _Bool showReactNativeFlow; // @synthesize showReactNativeFlow=_showReactNativeFlow;

@end

