//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UIImageView, UITapGestureRecognizer;

@interface IGCheckbox : UIView
{
    _Bool _isChecked;
    id <IGCheckboxDelegate> _delegate;
    UIColor *_imageColor;
    UIImageView *_checkboxView;
    UITapGestureRecognizer *_gestureRecognizer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *checkboxView; // @synthesize checkboxView=_checkboxView;
@property(nonatomic) __weak id <IGCheckboxDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapOnCheckbox:(id)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *gestureRecognizer; // @synthesize gestureRecognizer=_gestureRecognizer;
@property(retain, nonatomic) UIColor *imageColor; // @synthesize imageColor=_imageColor;
- (id)init;
@property(readonly, nonatomic) _Bool isChecked; // @synthesize isChecked=_isChecked;
- (void)layoutSubviews;
- (void)setColor:(id)arg1;
- (void)updateCheckboxUI;

@end

