//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCommentContentWithLikeView, UIButton;

@protocol IGCommentContentWithLikeViewDelegate <NSObject>
- (void)contentView:(IGCommentContentWithLikeView *)arg1 didTapOnLikeButton:(UIButton *)arg2;
- (void)contentView:(IGCommentContentWithLikeView *)arg1 didTapOnLikeCountButton:(UIButton *)arg2;
- (void)contentView:(IGCommentContentWithLikeView *)arg1 didTapOnReplyButton:(UIButton *)arg2;
- (void)contentView:(IGCommentContentWithLikeView *)arg1 didTapOnRetryButton:(UIButton *)arg2;
@end

