//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGCommentLogger : NSObject
{
}

+ (id)extraForCommentLoggingForFeedItem:(id)arg1 flaggedCommentLedger:(id)arg2;
+ (void)notifyCommentButtonTappedOnFeedItem:(id)arg1 extraDict:(id)arg2 analyticsModule:(id)arg3 flaggedCommentLedger:(id)arg4;
+ (void)notifyCommentComposeOnFeedItem:(id)arg1 loggingDelegate:(id)arg2 analyticsModule:(id)arg3 extraDict:(id)arg4;
+ (void)notifyCommentPostOnFeedItem:(id)arg1 loggingDelegate:(id)arg2 analyticsModule:(id)arg3 extraDict:(id)arg4;
+ (void)notifyForLoggingNotificationName:(id)arg1 feedItem:(id)arg2 loggingDelegate:(id)arg3 analyticsModule:(id)arg4 extraDict:(id)arg5;

@end

