//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGCollectionViewLayoutApplier : NSObject
{
    _Bool _didApply;
    CDUnknownBlockType _applyLayoutBlock;
}

- (void).cxx_destruct;
- (void)applyChangedLayoutState;
@property(copy, nonatomic) CDUnknownBlockType applyLayoutBlock; // @synthesize applyLayoutBlock=_applyLayoutBlock;
@property(nonatomic) _Bool didApply; // @synthesize didApply=_didApply;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

