//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGDelayedExecutorTask : NSObject
{
    NSString *_name;
    CDUnknownBlockType _block;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (id)initWithName:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;

@end

