//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionObject.h"

@class NSMutableArray, NSString;

@interface IGDelayedExecutor : NSObject <IGUserSessionObject>
{
    NSString *_analyticsEventName;
    NSMutableArray *_tasks;
    _Bool _startupCompleted;
    _Bool _sampled;
    _Bool _taskIsScheduled;
}

+ (id)sharedColdStartExecutor;
- (void).cxx_destruct;
- (void)executeWithName:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)initWithAnalyticsEventName:(id)arg1 executionDelay:(double)arg2;
- (void)logTaskComplete:(id)arg1 duration:(double)arg2;
- (void)processQueue;
- (void)startupCompleted;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

