//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedConfigurationType.h"

@class NSString;

@interface IGDefaultFeedConfiguration : NSObject <IGFeedConfigurationType>
{
    NSString *_moduleName;
}

- (void).cxx_destruct;
- (_Bool)allowAutoPlay;
- (id)analyticsModule;
- (id)feedAccessibilityIdentifier;
- (id)initWithModuleName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
- (_Bool)shouldAutoplayVideos;
- (_Bool)shouldPrefetchMediaForFeedItems;
- (_Bool)supportSaveTooltip;
- (_Bool)supportShareTooltip;
- (_Bool)supportStoryRingInHeader;
- (unsigned long long)tombstoneTypeForFeed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

