//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGRealtimeOperationDelegate.h"
#import "IGUserSessionClearableObject.h"

@class IGBadgeHelper, IGDirectCache, IGDirectStoryService, IGDirectThreadService, IGRealtimeManager, IGUserSession, NSString;

@interface IGDirectRealtimeService : NSObject <IGRealtimeOperationDelegate, IGUserSessionClearableObject>
{
    IGUserSession *_userSession;
    IGRealtimeManager *_realtimeManager;
    IGDirectThreadService *_threadService;
    IGDirectStoryService *_directStoryService;
}

+ (void)clearForUserPK:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) IGBadgeHelper *badgeHelper;
@property(readonly, nonatomic) IGDirectCache *cache;
@property(readonly, nonatomic) IGDirectStoryService *directStoryService; // @synthesize directStoryService=_directStoryService;
- (void)handleAddDirectStoryMessageRealtimeEventWithDictionary:(id)arg1 forThreadId:(id)arg2;
- (void)handleAddMessageRealtimeEventWithDictionary:(id)arg1 forThreadId:(id)arg2;
- (void)handleRealtimeDirectStoryScreenshotEventWithDictionary:(id)arg1 forStoryId:(id)arg2;
- (void)handleRealtimeDirectStoryThreadCreatedEventWithDictionary:(id)arg1;
- (void)handleRealtimeDirectStoryUnseenCountEventWithCount:(id)arg1 withSequenceString:(id)arg2;
- (void)handleRealtimeOperation:(id)arg1;
- (void)handleRealtimeRefreshRequest;
- (void)handleRealtimeSeenEventForUserId:(id)arg1 contentInfo:(id)arg2 andThreadId:(id)arg3;
- (void)handleRealtimeThreadEventWithThreadInfo:(id)arg1;
- (void)handleRealtimeUnseenCountEventWithCount:(id)arg1 withSequenceString:(id)arg2;
- (void)handleRealtimeVisualActionBadgeReplaceEventWithDictionary:(id)arg1 forThreadId:(id)arg2;
- (void)handleRemoveRealtimeEventForItemWithId:(id)arg1 forThreadId:(id)arg2;
- (void)handleReplaceMessageRealtimeEventWithDictionary:(id)arg1 forThreadId:(id)arg2;
- (void)handleTypingIndicatorWithDictionary:(id)arg1 threadId:(id)arg2;
- (id)initWithUserSession:(id)arg1;
- (id)pkForRealtimeOperation:(id)arg1;
@property(readonly, nonatomic) _Bool readyForReceiving;
@property(readonly, nonatomic) _Bool readyForSending;
@property(readonly, nonatomic) IGRealtimeManager *realtimeManager; // @synthesize realtimeManager=_realtimeManager;
- (void)subscribeOn:(id)arg1;
@property(readonly, nonatomic) unsigned long long subscriptionStatus;
@property(readonly, nonatomic) IGDirectThreadService *threadService; // @synthesize threadService=_threadService;
@property(readonly, nonatomic) __weak IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

