//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "IGDirectAddPeopleViewControllerDelegate.h"
#import "IGDirectToggleTableViewCellDelegate.h"
#import "IGTextFieldDelegate.h"

@class IGDirectInboxService, IGDirectPendingInboxService, IGDirectThread, IGDirectThreadService, IGTextField, IGUserSession, NSArray, NSString;

@interface IGDirectThreadInfoViewController : IGGroupedTableViewController <IGTextFieldDelegate, IGDirectToggleTableViewCellDelegate, IGDirectAddPeopleViewControllerDelegate>
{
    _Bool _isLoading;
    id <IGDirectThreadInfoViewControllerDelegate> _delegate;
    NSString *_threadId;
    IGDirectInboxService *_mainInboxService;
    IGDirectPendingInboxService *_pendingInboxService;
    IGDirectThreadService *_threadService;
    IGDirectThread *_thread;
    IGUserSession *_userSession;
    IGTextField *_nameField;
    NSArray *_sections;
}

- (void).cxx_destruct;
- (id)actionCellWithText:(id)arg1 indexPath:(id)arg2 identifier:(id)arg3;
- (id)addPeopleCellAtIndexPath:(id)arg1;
- (void)addPeopleViewController:(id)arg1 didAddUsers:(id)arg2;
- (id)analyticsModule;
- (id)blockButtonTitle;
- (void)blockUserFromPendingThread;
- (void)blockUserFromThread;
- (void)cell:(id)arg1 didSwitchValueTo:(_Bool)arg2;
- (id)cellForBlockUserAtIndexPath:(id)arg1;
- (id)cellForGroupNameAtIndexPath:(id)arg1;
- (id)cellForMuteAtIndexPath:(id)arg1;
- (id)cellForReportUserAtIndexPath:(id)arg1;
- (id)cellForUser:(id)arg1 atIndexPath:(id)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <IGDirectThreadInfoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishEditingName;
- (id)hideThreadCellAtIndexPath:(id)arg1;
- (id)initWithThreadId:(id)arg1 userSession:(id)arg2;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (long long)itemTypeForIndexPath:(id)arg1;
- (void)leaveThread;
@property(readonly, nonatomic) IGDirectInboxService *mainInboxService; // @synthesize mainInboxService=_mainInboxService;
@property(retain, nonatomic) IGTextField *nameField; // @synthesize nameField=_nameField;
- (_Bool)nameIsTooLong;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(readonly, nonatomic) IGDirectPendingInboxService *pendingInboxService; // @synthesize pendingInboxService=_pendingInboxService;
- (_Bool)prefersTabBarHidden;
- (void)reportUser;
@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
- (id)sectionsBasedOnThread:(id)arg1;
@property(retain, nonatomic) IGDirectThread *thread; // @synthesize thread=_thread;
- (void)showLeaveActionMenu;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
@property(readonly, copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(readonly, nonatomic) IGDirectThreadService *threadService; // @synthesize threadService=_threadService;
- (void)threadUpdated;
- (void)updateDoneButton:(_Bool)arg1;
- (void)updateNameField;
- (void)updateThreadNameToName:(id)arg1;
- (id)userForMemberSectionAtIndexPath:(id)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

