//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectRealtimeMessageDispatcher, IGDirectRealtimeService, IGDirectThreadService;

@interface IGDirectUploadTask : NSObject
{
    CDUnknownBlockType _messageCompletion;
    long long _numberOfFailures;
    id <IGDirectUploadable> _uploadable;
    IGDirectRealtimeService *_realtimeService;
    IGDirectRealtimeMessageDispatcher *_realtimeDispatcher;
    IGDirectThreadService *_threadService;
    id <IGAPIClient> _networker;
}

- (void).cxx_destruct;
- (void)httpSendUploadable:(id)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithUploadable:(id)arg1 realtimeService:(id)arg2 realtimeDispatcher:(id)arg3 threadService:(id)arg4 networker:(id)arg5;
@property(copy, nonatomic) CDUnknownBlockType messageCompletion; // @synthesize messageCompletion=_messageCompletion;
@property(retain, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(nonatomic) long long numberOfFailures; // @synthesize numberOfFailures=_numberOfFailures;
@property(readonly, nonatomic) IGDirectRealtimeMessageDispatcher *realtimeDispatcher; // @synthesize realtimeDispatcher=_realtimeDispatcher;
- (void)realtimeSendUploadable:(id)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) IGDirectRealtimeService *realtimeService; // @synthesize realtimeService=_realtimeService;
- (void)sendUploadable:(id)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)start;
@property(readonly, nonatomic) IGDirectThreadService *threadService; // @synthesize threadService=_threadService;
@property(readonly, nonatomic) id <IGDirectUploadable> uploadable; // @synthesize uploadable=_uploadable;

@end

