//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSString;

@interface IGDirectResponseInfo : NSObject <NSCoding>
{
    _Bool _forceOverlay;
    NSString *_actionText;
    NSString *_actionName;
    NSArray *_appUrls;
    NSArray *_iosLinks;
    NSString *_overlayText;
    NSString *_overlayTitle;
    NSString *_overlaySubtitle;
    NSArray *_storeLocations;
    double _storeMapZoomLevel;
}

+ (_Bool)hasDirectResponseInfo:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(readonly, copy, nonatomic) NSString *actionText; // @synthesize actionText=_actionText;
@property(readonly, copy, nonatomic) NSArray *appUrls; // @synthesize appUrls=_appUrls;
- (_Bool)containsAppStoreLink;
- (_Bool)containsNonWebLinks;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) _Bool forceOverlay; // @synthesize forceOverlay=_forceOverlay;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *iosLinks; // @synthesize iosLinks=_iosLinks;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDirectResponseInfo:(id)arg1;
@property(readonly, copy, nonatomic) NSString *overlaySubtitle; // @synthesize overlaySubtitle=_overlaySubtitle;
@property(readonly, copy, nonatomic) NSString *overlayText; // @synthesize overlayText=_overlayText;
@property(readonly, copy, nonatomic) NSString *overlayTitle; // @synthesize overlayTitle=_overlayTitle;
@property(readonly, copy, nonatomic) NSArray *storeLocations; // @synthesize storeLocations=_storeLocations;
@property(readonly, nonatomic) double storeMapZoomLevel; // @synthesize storeMapZoomLevel=_storeMapZoomLevel;
- (_Bool)supportsCTA;

@end

