//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectResponseInfo, IGFeedItem, IGFeedItemActionCellState, IGFeedItemTracker, NSDictionary, NSString;

@protocol IGDirectResponseLogging <NSObject>
- (void)logActionFailedForFeedItem:(IGFeedItem *)arg1 feedItemTracker:(IGFeedItemTracker *)arg2 directResponseInfo:(IGDirectResponseInfo *)arg3 openContext:(NSString *)arg4 openTarget:(NSString *)arg5;
- (void)logActionForFeedItem:(IGFeedItem *)arg1 feedItemTracker:(IGFeedItemTracker *)arg2 directResponseInfo:(IGDirectResponseInfo *)arg3 actionCellState:(IGFeedItemActionCellState *)arg4 openContext:(NSString *)arg5 action:(NSString *)arg6 extraFields:(NSDictionary *)arg7;
@end

