//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBTimer, IGUserSession, NSDate, NSMutableDictionary;

@interface IGDirectTypingStatusService : NSObject
{
    int _incomingTypingStatusLock;
    IGUserSession *_userSession;
    double _typingStatusUpdateInterval;
    NSDate *_lastOutGoingTypingStatusActiveDate;
    FBTimer *_incomingTypingStatusTimer;
    NSMutableDictionary *_incomingTypingStatusMap;
}

- (void).cxx_destruct;
- (double)activeDurationForTypingStatus:(id)arg1;
- (void)dealloc;
- (void)deleteTypingStatus:(id)arg1;
@property(readonly, nonatomic) int incomingTypingStatusLock; // @synthesize incomingTypingStatusLock=_incomingTypingStatusLock;
@property(retain, nonatomic) NSMutableDictionary *incomingTypingStatusMap; // @synthesize incomingTypingStatusMap=_incomingTypingStatusMap;
@property(retain, nonatomic) FBTimer *incomingTypingStatusTimer; // @synthesize incomingTypingStatusTimer=_incomingTypingStatusTimer;
- (id)initWithUserSession:(id)arg1;
@property(retain, nonatomic) NSDate *lastOutGoingTypingStatusActiveDate; // @synthesize lastOutGoingTypingStatusActiveDate=_lastOutGoingTypingStatusActiveDate;
- (void)resetOutgoingStatus;
- (void)saveTypingStatus:(id)arg1;
- (void)sendTypingStatusAsIsActive:(_Bool)arg1 threadId:(id)arg2;
@property(nonatomic) double typingStatusUpdateInterval; // @synthesize typingStatusUpdateInterval=_typingStatusUpdateInterval;
@property(retain, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (_Bool)shouldSendStatus:(_Bool)arg1;
- (void)startIncomingTypingStatusTimer:(id)arg1;
- (id)typingStatusForThreadId:(id)arg1;
- (void)typingStatusUpdated:(id)arg1;
- (void)updateOutgoingStatusIsActive:(_Bool)arg1 threadId:(id)arg2;

@end

