//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UITabBar;

@interface IGDirectNewMessageBanner : UIButton
{
    UITabBar *_backdropTabBar;
}

+ (id)banner;
- (void).cxx_destruct;
@property(retain, nonatomic) UITabBar *backdropTabBar; // @synthesize backdropTabBar=_backdropTabBar;
- (void)layoutSubviews;

@end

