//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectResponseInfo, IGFeedItem, IGFeedItemActionCellState, IGFeedItemPageCellState, IGFeedItemTracker, IGUserSession, NSString, UIViewController;

@protocol IGDirectResponseHandling <NSObject>
- (struct IGDirectResponseHandleResult)handleFeedItem:(IGFeedItem *)arg1 feedItemTracker:(IGFeedItemTracker *)arg2 directResponseInfo:(IGDirectResponseInfo *)arg3 viewController:(UIViewController *)arg4 actionCellState:(IGFeedItemActionCellState *)arg5 pageCellState:(IGFeedItemPageCellState *)arg6 mediaPosition:(long long)arg7 userSession:(IGUserSession *)arg8 context:(NSString *)arg9 showCallConfirmation:(_Bool)arg10 completion:(void (^)(void))arg11;
@end

