//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStoryComposerLoggerProtocol.h"

@class IGStoryComposerWaterfallLoggingContext, NSString;

@interface IGDirectStoryComposerLogger : NSObject <IGStoryComposerLoggerProtocol>
{
    _Bool _didLogCompletion;
    _Bool _hasEnteredTextOnlyMode;
    long long _exitPoint;
    IGStoryComposerWaterfallLoggingContext *_loggingContext;
    NSString *_threadId;
    NSString *_traySessionId;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool didLogCompletion; // @synthesize didLogCompletion=_didLogCompletion;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) long long exitPoint; // @synthesize exitPoint=_exitPoint;
@property(nonatomic) _Bool hasEnteredTextOnlyMode; // @synthesize hasEnteredTextOnlyMode=_hasEnteredTextOnlyMode;
- (id)initWithCoder:(id)arg1;
- (id)initWithLoggingContext:(id)arg1 threadId:(id)arg2 traySessionId:(id)arg3;
- (void)logStepWithName:(id)arg1 module:(id)arg2 extraDict:(id)arg3;
@property(readonly, nonatomic) IGStoryComposerWaterfallLoggingContext *loggingContext; // @synthesize loggingContext=_loggingContext;
- (void)notifyCompletionWithExitPoint:(long long)arg1 module:(id)arg2;
- (void)notifyEnter;
- (void)notifyEnterWithCameraMode:(long long)arg1;
- (void)notifyEnteringTextOnlyMode;
- (void)notifyTapGoInstaButton;
@property(readonly, copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(readonly, copy, nonatomic) NSString *traySessionId; // @synthesize traySessionId=_traySessionId;

@end

