//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectStoryPresentationListener.h"

@class IGDirectStoryPresentationManager, NSMutableDictionary, NSString;

@interface IGDirectStoryReportController : NSObject <IGDirectStoryPresentationListener>
{
    id <IGAPIClient> _networker;
    IGDirectStoryPresentationManager *_presentationManager;
    NSMutableDictionary *_lastViewedMediaIdForStory;
}

- (void).cxx_destruct;
- (_Bool)allowReportForStoryWithId:(id)arg1;
- (void)directStoryPresentationManager:(id)arg1 didDismissViewerForStoryId:(id)arg2;
- (void)directStoryPresentationManager:(id)arg1 didFocusOnMessage:(id)arg2 forStoryId:(id)arg3 isReplay:(_Bool)arg4;
- (id)initWithNetworker:(id)arg1 presentationManager:(id)arg2;
@property(readonly, nonatomic) NSMutableDictionary *lastViewedMediaIdForStory; // @synthesize lastViewedMediaIdForStory=_lastViewedMediaIdForStory;
@property(readonly, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(readonly, nonatomic) IGDirectStoryPresentationManager *presentationManager; // @synthesize presentationManager=_presentationManager;
- (void)reportInappropriateStoryWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)reportSpamStoryWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)reportStoryWithId:(id)arg1 viewController:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

