//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListAdapterDataSource.h"

@class IGDirectMessageService, IGDirectThread, IGDirectThreadAnalyticsLogger, IGListCollectionView, IGUserSession, NSMapTable, NSString;

@interface IGDirectThreadListAdapterDataSource : NSObject <IGListAdapterDataSource>
{
    IGDirectThread *_thread;
    IGUserSession *_userSession;
    IGDirectMessageService *_messageService;
    IGListCollectionView *_collectionView;
    IGDirectThreadAnalyticsLogger *_analyticsLogger;
    NSMapTable *_viewModelsToMessages;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGDirectThreadAnalyticsLogger *analyticsLogger; // @synthesize analyticsLogger=_analyticsLogger;
@property(readonly, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)initWithUserSession:(id)arg1 messageService:(id)arg2 collectionView:(id)arg3 analyticsLogger:(id)arg4;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)messageForViewModel:(id)arg1;
@property(readonly, nonatomic) IGDirectMessageService *messageService; // @synthesize messageService=_messageService;
- (id)messageViewModelsFromThread:(id)arg1 viewWidth:(double)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (id)reactionsViewModelForMessage:(id)arg1;
- (id)sectionControllerForObject:(id)arg1;
@property(retain, nonatomic) IGDirectThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) NSMapTable *viewModelsToMessages; // @synthesize viewModelsToMessages=_viewModelsToMessages;
- (id)timestampViewModelForMessage:(id)arg1 previousMessage:(id)arg2;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (id)usernameViewModelForMessage:(id)arg1 viewModelMetadata:(id)arg2;
- (id)viewModelFromMessage:(id)arg1 viewModelMetadata:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

