//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectAsyncCaching.h"
#import "IGDirectSyncCaching.h"
#import "IGUserSessionClearableObject.h"

@class IGDirectInboxMetadata, IGDirectInboxPendingRequests, IGDirectMemoryCache, IGDirectSQLiteCache, IGDirectThreadMerger, IGDirectThreadStore, NSDate, NSString;

@interface IGDirectCache : NSObject <IGDirectSyncCaching, IGDirectAsyncCaching, IGUserSessionClearableObject>
{
    IGDirectInboxMetadata *_inbox;
    IGDirectInboxPendingRequests *_pendingRequests;
    NSString *_userPK;
    IGDirectThreadMerger *_threadMerger;
    IGDirectThreadStore *_threadStore;
    IGDirectMemoryCache *_memoryCache;
    IGDirectSQLiteCache *_sqliteCache;
    NSDate *_timeInboxLastCached;
    NSDate *_timePendingInboxLastCached;
    unsigned long long _threadsTrimmingBackgroundTask;
}

+ (id)cacheFileURLForUserPK:(id)arg1 suffix:(id)arg2;
+ (void)clearCacheForUserPK:(id)arg1;
+ (void)clearForUserPK:(id)arg1;
+ (id)inboxCacheFileURLForUserPK:(id)arg1;
+ (id)pendingRequestsCacheFileURLForUserPK:(id)arg1;
+ (id)seenMarksCacheFileURLForUserPK:(id)arg1;
+ (id)storyDefaultRecipientsCacheFileURLForUserPK:(id)arg1;
- (void).cxx_destruct;
- (void)addListener:(id)arg1;
- (id)allPendingMessages;
- (id)allSeenMarks;
- (void)archiveObject:(id)arg1 fileURL:(id)arg2;
- (_Bool)cacheIsValidWithLastCacheTime:(id)arg1;
- (void)createLocalThreadWithUsers:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)deleteSeenMark:(id)arg1;
- (id)directStories;
- (void)fetchInboxCompletion:(CDUnknownBlockType)arg1;
- (void)fetchThreadPageFromCursor:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchThreadWithId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchThreadsWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) IGDirectInboxMetadata *inbox; // @synthesize inbox=_inbox;
- (_Bool)inboxCacheIsFresh;
- (id)initWithUserPK:(id)arg1 directThreadStore:(id)arg2;
- (void)markSeenForMessageId:(id)arg1 threadId:(id)arg2;
@property(readonly, nonatomic) IGDirectMemoryCache *memoryCache; // @synthesize memoryCache=_memoryCache;
- (id)messageWithId:(id)arg1 threadId:(id)arg2;
- (void)onUserSwitchAndAppBackground;
- (_Bool)pendingInboxCacheIsFresh;
@property(copy, nonatomic) IGDirectInboxPendingRequests *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
- (void)readInboxFromDisk:(CDUnknownBlockType)arg1;
- (void)readPendingRequestsFromDisk:(CDUnknownBlockType)arg1;
- (void)readSeenMarksFromDisk;
- (void)readStoryRecipientsWithHandler:(CDUnknownBlockType)arg1;
- (void)removeListener:(id)arg1;
- (void)removePendingMessage:(id)arg1;
- (void)removeStoryMessageWithId:(id)arg1 storyId:(id)arg2 updateType:(unsigned long long)arg3;
- (void)removeStoryWithId:(id)arg1 forUpdateType:(unsigned long long)arg2;
- (void)removeThreadWithId:(id)arg1;
- (void)replaceContent:(id)arg1 forThreadId:(id)arg2 needsForceUpdate:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)saveInbox:(id)arg1 threads:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)saveInboxMetaData:(id)arg1;
- (void)savePendingInboxWithRequests:(id)arg1 threads:(id)arg2;
- (void)savePendingRequests:(id)arg1;
- (void)saveSeenMark:(id)arg1;
- (void)saveSeenMarksToDisk;
- (void)saveStories:(id)arg1 shouldFlush:(_Bool)arg2 forUpdateType:(unsigned long long)arg3;
- (void)saveStory:(id)arg1 option:(unsigned long long)arg2 forUpdateType:(unsigned long long)arg3;
- (void)saveStoryRecipients:(id)arg1;
- (void)saveThreads:(id)arg1 mergeOption:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic) unsigned long long threadsTrimmingBackgroundTask; // @synthesize threadsTrimmingBackgroundTask=_threadsTrimmingBackgroundTask;
@property(retain, nonatomic) NSDate *timeInboxLastCached; // @synthesize timeInboxLastCached=_timeInboxLastCached;
@property(retain, nonatomic) NSDate *timePendingInboxLastCached; // @synthesize timePendingInboxLastCached=_timePendingInboxLastCached;
@property(readonly, nonatomic) IGDirectSQLiteCache *sqliteCache; // @synthesize sqliteCache=_sqliteCache;
- (_Bool)sqliteQEEnabled;
- (void)storeThread:(id)arg1;
- (id)storyForId:(id)arg1;
@property(readonly, nonatomic) IGDirectThreadMerger *threadMerger; // @synthesize threadMerger=_threadMerger;
@property(readonly, nonatomic) IGDirectThreadStore *threadStore; // @synthesize threadStore=_threadStore;
- (id)threadWithId:(id)arg1;
- (id)threadWithUsers:(id)arg1;
- (id)threadsWithOptions:(id)arg1;
- (void)trimCache;
- (void)trimThreads:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unarchiveFileURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updatePendingMessage:(id)arg1 forThreadId:(id)arg2;
- (_Bool)updateStatusMetadata:(id)arg1 forStoryWithId:(id)arg2 forUpdateType:(unsigned long long)arg3;
- (void)updateThreadWithId:(id)arg1 draftMessage:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)updatedThreadWithThread:(id)arg1 mergeOption:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSString *userPK; // @synthesize userPK=_userPK;
- (void)warmUpCache;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

