//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGProfilePictureImageView, UILabel, UIView;

@interface IGDirectTypingIndicator : UICollectionViewCell
{
    UILabel *_statusLabel;
    UIView *_statusLabelContainer;
    IGProfilePictureImageView *_profilePictureImageView;
    UIView *_profileViewBackgroundView;
}

- (void).cxx_destruct;
- (void)animateAvatarBackground;
- (void)animateProfileImage;
- (void)animateStatusLabel;
- (double)avatarBackgroundSize;
- (double)avatarSize;
- (void)configureWithViewModel:(id)arg1;
- (void)continueAnimation;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutAvatarBackground;
@property(retain, nonatomic) IGProfilePictureImageView *profilePictureImageView; // @synthesize profilePictureImageView=_profilePictureImageView;
@property(retain, nonatomic) UIView *profileViewBackgroundView; // @synthesize profileViewBackgroundView=_profileViewBackgroundView;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIView *statusLabelContainer; // @synthesize statusLabelContainer=_statusLabelContainer;
- (void)setupProfilePicture;
- (void)setupStatusLabel;
- (void)startAnimating;

@end

