//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGDirectContentCellUploadDecorator;

@protocol IGDirectContentUploadCell
@property(nonatomic) __weak id <IGDirectContentUpoadCellDelegate> delegate;
- (void)handleUploadCellTap;
- (void)performDelete;
- (void)performRetry;
@property(retain, nonatomic) IGDirectContentCellUploadDecorator *uploadDecorator;
- (void)showUploadFailedUI;
- (void)showUploadSendingUI;
- (void)uploadDecoratorShowFailedUI:(IGDirectContentCellUploadDecorator *)arg1;
@end

