//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface IGDirectShareHeaderViewLayout : NSObject
{
    _Bool _shouldShowUserProfile;
    double _sideImageWidth;
    double _sideImageHeight;
    double _sideImageHorizontalPadding;
    double _sideImageVerticalPadding;
    UIImage *_iconImage;
}

+ (id)shareHeaderViewConfigHashTagStyle;
+ (id)shareHeaderViewConfigLocationStyle;
+ (id)shareHeaderViewConfigPostStyle;
+ (id)shareHeaderViewConfigProfileStyle;
- (id)description;
@property(nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
- (id)initWithSideImageWidth:(double)arg1 sideImageHeight:(double)arg2 sideImageHorizontalPadding:(double)arg3 sideImageVerticalPadding:(double)arg4 shouldShowUserProfile:(_Bool)arg5;
@property(nonatomic) _Bool shouldShowUserProfile; // @synthesize shouldShowUserProfile=_shouldShowUserProfile;
@property(nonatomic) double sideImageHeight; // @synthesize sideImageHeight=_sideImageHeight;
@property(nonatomic) double sideImageHorizontalPadding; // @synthesize sideImageHorizontalPadding=_sideImageHorizontalPadding;
@property(nonatomic) double sideImageVerticalPadding; // @synthesize sideImageVerticalPadding=_sideImageVerticalPadding;
@property(nonatomic) double sideImageWidth; // @synthesize sideImageWidth=_sideImageWidth;

@end

