//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStoryCreationAnimationType.h"

@class IGStoryCameraViewController, NSString;

@interface IGDirectStoryTextCreationAnimationController : NSObject <IGStoryCreationAnimationType>
{
    _Bool _presenting;
    IGStoryCameraViewController *_cameraViewController;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
@property(retain, nonatomic) IGStoryCameraViewController *cameraViewController; // @synthesize cameraViewController=_cameraViewController;
@property(nonatomic) _Bool presenting; // @synthesize presenting=_presenting;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

