//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectThreadInfoViewController, NSString;

@protocol IGDirectThreadInfoViewControllerDelegate <NSObject>
- (void)threadInfoViewController:(IGDirectThreadInfoViewController *)arg1 didAddUsersToThreadWithId:(NSString *)arg2;
- (void)threadInfoViewController:(IGDirectThreadInfoViewController *)arg1 didLeaveThreadWithId:(NSString *)arg2;
- (void)threadInfoViewController:(IGDirectThreadInfoViewController *)arg1 didMuteThreadWithId:(NSString *)arg2 muted:(_Bool)arg3;
- (void)threadInfoViewController:(IGDirectThreadInfoViewController *)arg1 didRenameThreadWithId:(NSString *)arg2 toName:(NSString *)arg3;
@end

