//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGDirectMessageCell.h"

#import "IGDirectMediaViewerCellProtocol.h"
#import "IGHeartAnimatable.h"

@class IGBlurredImageView, IGImageProgressView, NSString;

@interface IGDirectPhotoMessageCell : IGDirectMessageCell <IGDirectMediaViewerCellProtocol, IGHeartAnimatable>
{
    IGImageProgressView *_imageView;
    IGBlurredImageView *_blurredImageView;
    struct CGSize _imageSize;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGBlurredImageView *blurredImageView; // @synthesize blurredImageView=_blurredImageView;
- (void)configureWithViewModel:(id)arg1;
- (id)contentViewForHeartAnimation;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(readonly, nonatomic) IGImageProgressView *imageView; // @synthesize imageView=_imageView;
- (id)imageViewForMediaViewer;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)previewImageForMediaViewer;
- (void)setupSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

