//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class IGTapButton, NSString, UIImageView, UITextField;

@interface IGDirectSearchBar : UIView <UITextFieldDelegate>
{
    id <IGDirectSearchBarDelegate> _delegate;
    UITextField *_textField;
    UIImageView *_queryImageView;
    IGTapButton *_clearButton;
    struct UIEdgeInsets _insets;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGTapButton *clearButton; // @synthesize clearButton=_clearButton;
- (void)clearButtonTapped:(id)arg1;
- (void)clearText;
@property(nonatomic) __weak id <IGDirectSearchBarDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIImageView *queryImageView; // @synthesize queryImageView=_queryImageView;
- (void)setupClearButton;
- (void)setupQueryImageView;
- (void)setupTextfield;
- (id)text;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)textFieldChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

