//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGProfilePictureImageView, UIImageView, UILabel;

@interface IGDirectReshareMessageHeaderView : UIView
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_chevron;
    IGProfilePictureImageView *_profilePicture;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *chevron; // @synthesize chevron=_chevron;
- (void)configureWithViewModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) IGProfilePictureImageView *profilePicture; // @synthesize profilePicture=_profilePicture;
- (void)reset;
- (void)setBackgroundColor:(id)arg1;
- (void)setupChevron;
- (void)setupProfilePicture;
- (void)setupSubtitleLabel;
- (void)setupSubviews;
- (void)setupTitleLabel;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

