//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface IGDirectRecipientSearch : NSObject
{
    _Bool _resultIsFiltered;
    NSString *_query;
    NSArray *_recipients;
    CDUnknownBlockType _successHandler;
    CDUnknownBlockType _failureHandler;
}

- (void).cxx_destruct;
- (id)description;
@property(readonly, copy, nonatomic) CDUnknownBlockType failureHandler; // @synthesize failureHandler=_failureHandler;
- (unsigned long long)hash;
- (id)initWithQuery:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(copy, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic) _Bool resultIsFiltered; // @synthesize resultIsFiltered=_resultIsFiltered;
- (id)searchWithResultList:(id)arg1 resultIsFiltered:(_Bool)arg2;
@property(readonly, copy, nonatomic) CDUnknownBlockType successHandler; // @synthesize successHandler=_successHandler;

@end

