//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGDirectShareRecipient, NSHashTable, NSProgress, NSString;

@interface IGDirectContentUploadInfo : NSObject <NSCoding, NSCopying>
{
    _Bool _isViaRealtime;
    IGDirectShareRecipient *_recipient;
    NSString *_threadID;
    NSString *_uploadIndexKey;
    long long _uploadStatus;
    NSProgress *_uploadProgress;
    unsigned long long _autoRetryCount;
    NSHashTable *_observers;
}

- (void).cxx_destruct;
- (void)addObserver:(id)arg1;
@property(nonatomic) unsigned long long autoRetryCount; // @synthesize autoRetryCount=_autoRetryCount;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)digestDescriptionWithCurrentUser:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRecipient:(id)arg1;
- (_Bool)isUploading;
@property(nonatomic) _Bool isViaRealtime; // @synthesize isViaRealtime=_isViaRealtime;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) IGDirectShareRecipient *recipient; // @synthesize recipient=_recipient;
- (void)removeUploadObserver:(id)arg1;
@property(retain, nonatomic) NSString *threadID; // @synthesize threadID=_threadID;
@property(copy, nonatomic) NSString *uploadIndexKey; // @synthesize uploadIndexKey=_uploadIndexKey;
@property(retain, nonatomic) NSProgress *uploadProgress; // @synthesize uploadProgress=_uploadProgress;
@property(nonatomic) long long uploadStatus; // @synthesize uploadStatus=_uploadStatus;
- (id)stringForUploadStatus:(long long)arg1;

@end

