//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGContext, IGDrawMappedBufferRange;

@protocol IGDrawMappedBuffer <NSObject>
+ (id)new;
@property(readonly, nonatomic) unsigned long long available;
- (void)bind;
@property(readonly, nonatomic) void *data;
- (void)doneModifyingRange:(IGDrawMappedBufferRange *)arg1;
- (void)flushStart:(unsigned long long)arg1 amount:(unsigned long long)arg2;
- (IGDrawMappedBufferRange *)getRangeForUse;
@property(nonatomic) void *head;
- (id)init;
- (id)initWithContext:(IGContext *)arg1 size:(unsigned long long)arg2;
@property(readonly, nonatomic) _Bool locked;
@property(readonly, nonatomic) unsigned int name;
@property(readonly, nonatomic) unsigned long long offset;
@property(readonly, nonatomic) unsigned long long size;
@end

