//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class IGNetworker, NSLock, NSMutableDictionary, NSString;

@interface IGEditProfileReactFetcher : NSObject <IGUserSessionClearableObject>
{
    NSMutableDictionary *_unresolvedCallbacks;
    NSLock *_unresolvedCallbacksLock;
    IGNetworker *_networker;
}

+ (void)clearForUserPK:(id)arg1;
- (void).cxx_destruct;
- (void)cancelAllOngoingFetches;
- (void)didReceiveNetworkFailureResponseWithError:(id)arg1 forIdentifier:(id)arg2;
- (void)didReceiveSuccessfulNetworkResponse:(id)arg1 forIdentifier:(id)arg2;
- (id)fetch;
- (id)initWithNetworker:(id)arg1;
- (void)resolveWhenReadyWithFetchIdentifier:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

