//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItem, IGLocation, IGUsertagGroup, NSString;

@interface IGEditedPost : NSObject
{
    IGLocation *_location;
    NSString *_caption;
    IGUsertagGroup *_usertags;
    IGFeedItem *_feedItem;
}

- (void).cxx_destruct;
- (void)addParametersToRequestBuilder:(id)arg1 userSession:(id)arg2;
@property(retain, nonatomic) NSString *caption; // @synthesize caption=_caption;
@property(retain, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (_Bool)hasChanged;
- (_Bool)hasChangedCaption;
- (_Bool)hasChangedLocation;
- (_Bool)hasChangedUsertags;
- (id)initWithFeedItem:(id)arg1;
@property(retain, nonatomic) IGLocation *location; // @synthesize location=_location;
- (id)pk;
@property(retain, nonatomic) IGUsertagGroup *usertags; // @synthesize usertags=_usertags;

@end

