//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGAutocompleteControllerTextInput.h"
#import "UITextViewDelegate.h"

@class NSString, UIControl, UILabel, UITextView;

@interface IGEditPostTextViewController : UIViewController <UITextViewDelegate, IGAutocompleteControllerTextInput>
{
    id <IGEditPostTextViewControllerDelegate> _delegate;
    UITextView *_textView;
    UIControl *_textViewContainer;
    UILabel *_placeholderLabel;
    double _height;
}

+ (double)leadingHeight;
- (void).cxx_destruct;
- (id)accessibilityValue;
- (_Bool)becomeFirstResponder;
- (void)beginEditing;
- (id)beginningOfDocument;
- (struct CGRect)caretRect;
- (void)clearText;
- (id)closestPositionToPoint:(struct CGPoint)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <IGEditPostTextViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double height; // @synthesize height=_height;
- (id)inputTextView;
@property(readonly, nonatomic) _Bool isEditingText;
- (void)loadView;
- (long long)offsetFromPosition:(id)arg1 toPosition:(id)arg2;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(copy, nonatomic) NSString *placeholderText;
- (id)positionFromPosition:(id)arg1 offset:(long long)arg2;
- (_Bool)resignFirstResponder;
@property(nonatomic) struct _NSRange selectedRange;
- (void)setSelectedTextRange:(id)arg1;
@property(nonatomic) long long spellCheckingType;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIControl *textViewContainer; // @synthesize textViewContainer=_textViewContainer;
- (double)textContentLayoutHeight;
- (double)textContentLayoutHeightForWidth:(double)arg1;
- (double)textHeightForWidth:(double)arg1;
- (id)textRangeFromPosition:(id)arg1 toPosition:(id)arg2;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)updatePlaceholderVisibility;
- (void)updateViewHeight;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(nonatomic) long long autocapitalizationType;
@property(nonatomic) long long autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long keyboardType;
@property(nonatomic) long long returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

