//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGBlurredImageView, IGEmptyProfileMediaOverlay, NSURL;

@interface IGEmptyProfileMediaViewCell : UICollectionViewCell
{
    NSURL *_profilePhotoURL;
    IGBlurredImageView *_profilePhotoView;
    IGEmptyProfileMediaOverlay *_overlay;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) IGEmptyProfileMediaOverlay *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) NSURL *profilePhotoURL; // @synthesize profilePhotoURL=_profilePhotoURL;
@property(retain, nonatomic) IGBlurredImageView *profilePhotoView; // @synthesize profilePhotoView=_profilePhotoView;

@end

