//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGProfilePictureImageView, UIButton, UIImageView, UILabel;

@interface IGEventViewerAttributionHeaderCell : UICollectionViewCell
{
    id <IGEventViewerAttributionHeaderCellDelegate> _delegate;
    IGProfilePictureImageView *_profileImageView;
    UIImageView *_verifiedBadgeImageView;
    UILabel *_usernameLabel;
    UIButton *_moreButton;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
- (void)configureView;
- (void)configureWithImageURL:(id)arg1 username:(id)arg2 isVerified:(_Bool)arg3;
@property(nonatomic) __weak id <IGEventViewerAttributionHeaderCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveTapGesture:(id)arg1;
- (void)didTapMoreButton:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutMoreButton;
- (void)layoutSubviews;
@property(nonatomic) __weak UIButton *moreButton; // @synthesize moreButton=_moreButton;
- (void)prepareForReuse;
@property(nonatomic) __weak IGProfilePictureImageView *profileImageView; // @synthesize profileImageView=_profileImageView;
- (void)setBackgroundColor:(id)arg1;
@property(nonatomic) __weak UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(nonatomic) __weak UIImageView *verifiedBadgeImageView; // @synthesize verifiedBadgeImageView=_verifiedBadgeImageView;
- (void)setupSubviews;
- (id)textAttributes;

@end

