//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItemMediaCell<IGEventViewerCellType>, UIView;

@interface IGEventViewerMediaPauseViewPresenter : NSObject
{
    UIView *_pauseView;
    IGFeedItemMediaCell<IGEventViewerCellType> *_mediaCell;
    id <IGEventViewerMediaContextViewDelegate> _contextViewDelegate;
}

- (void).cxx_destruct;
- (void)cancelImageLoadingForBlurringView;
@property(nonatomic) __weak id <IGEventViewerMediaContextViewDelegate> contextViewDelegate; // @synthesize contextViewDelegate=_contextViewDelegate;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithContextViewDelegate:(id)arg1;
@property(readonly, nonatomic) _Bool isPauseViewPresented;
@property(nonatomic) __weak IGFeedItemMediaCell<IGEventViewerCellType> *mediaCell; // @synthesize mediaCell=_mediaCell;
@property(retain, nonatomic) UIView *pauseView; // @synthesize pauseView=_pauseView;
- (id)setUpPauseViewWithMediaCell:(id)arg1 feedItem:(id)arg2;
- (void)showInMediaCell:(id)arg1 feedItem:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (id)styledStringForFeedItem:(id)arg1 width:(double)arg2;

@end

