//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGNetworkSourceDelegate.h"

@class IGEventFeedDataCache, IGEventServiceConfiguration, IGNetworkSource, NSString;

@interface IGEventService : NSObject <IGNetworkSourceDelegate>
{
    IGNetworkSource *_networkSource;
    NSString *_eventTitle;
    id <IGEventServiceNetworkDelegate> _networkDelegate;
    IGEventFeedDataCache *_feedDataCache;
    IGEventServiceConfiguration *_configuration;
    NSString *_eventId;
    NSString *_eventHeader;
    NSString *_currentUserPK;
}

+ (void)reportUserDismissChannelId:(id)arg1 channelType:(id)arg2 networker:(id)arg3;
+ (void)reportUserDismissPost:(id)arg1 networker:(id)arg2;
+ (void)reportUserUndoDismissPost:(id)arg1 networker:(id)arg2;
- (void).cxx_destruct;
- (void)cacheEventFeedData:(id)arg1;
- (id)cachedPosts;
- (void)cancelRequest;
@property(readonly, nonatomic) IGEventServiceConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) NSString *currentUserPK; // @synthesize currentUserPK=_currentUserPK;
@property(readonly, nonatomic) NSString *eventHeader; // @synthesize eventHeader=_eventHeader;
@property(readonly, nonatomic) NSString *eventId; // @synthesize eventId=_eventId;
@property(readonly, nonatomic) NSString *eventTitle; // @synthesize eventTitle=_eventTitle;
@property(readonly, nonatomic) IGEventFeedDataCache *feedDataCache; // @synthesize feedDataCache=_feedDataCache;
- (void)fetchMorePosts;
- (void)fetchPosts;
- (id)initWithConfiguration:(id)arg1 feedDataCache:(id)arg2 userSession:(id)arg3;
- (_Bool)isLoading;
@property(nonatomic) __weak id <IGEventServiceNetworkDelegate> networkDelegate; // @synthesize networkDelegate=_networkDelegate;
- (void)networkSource:(id)arg1 didFailWithError:(id)arg2;
- (void)networkSource:(id)arg1 didFetchMoreWithObject:(id)arg2;
- (void)networkSource:(id)arg1 didFetchObject:(id)arg2;
- (id)requestWithMaxID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

