//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface IGFeedNetworkSourceRequestConfig : NSObject
{
    NSDictionary *_requestParameters;
    long long _fetchAction;
    unsigned long long _behavior;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long behavior; // @synthesize behavior=_behavior;
@property(readonly, nonatomic) long long fetchAction; // @synthesize fetchAction=_fetchAction;
- (id)initWithRequestParameters:(id)arg1 fetchAction:(long long)arg2 behavior:(unsigned long long)arg3;
@property(readonly, nonatomic) NSDictionary *requestParameters; // @synthesize requestParameters=_requestParameters;

@end

