//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedNetworkSource, IGFeedNetworkSourceRequestConfig, NSArray, NSDictionary;

@protocol IGFeedNetworkSourceDelegate <NSObject>

@optional
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didChangeToObjects:(NSArray *)arg2;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didFailToLoadForFetchAction:(long long)arg2;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didFinishLoadingObjects:(NSArray *)arg2 forFetchAction:(long long)arg3;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didReceiveResponseForConfig:(IGFeedNetworkSourceRequestConfig *)arg2;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didRefreshObjects:(NSArray *)arg2 allObjects:(NSArray *)arg3;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 didStartLoadingForFetchAction:(long long)arg2;
- (void)feedNetworkSource:(IGFeedNetworkSource *)arg1 willLoadItemsFromResponse:(NSDictionary *)arg2;
@end

