//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface IGFeedPrebufferingHelper : NSObject
{
    _Bool _videoPreloadingEnabled;
    NSMutableDictionary *_prebufferingURLs;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)cancelPrebufferForVideo:(id)arg1;
- (id)init;
- (id)keyForVideo:(id)arg1;
- (void)prebufferVideoForURL:(id)arg1 video:(id)arg2;
- (id)prebufferVideoURLForVideo:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *prebufferingURLs; // @synthesize prebufferingURLs=_prebufferingURLs;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool videoPreloadingEnabled; // @synthesize videoPreloadingEnabled=_videoPreloadingEnabled;

@end

