//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface IGFeedItemViewingSessionManager : NSObject
{
    NSMutableDictionary *_sessions;
}

- (void).cxx_destruct;
- (id)keyForFeedItem:(id)arg1;
- (id)sessionForFeedItem:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *sessions; // @synthesize sessions=_sessions;
- (void)updateSessionsWithFeedItems:(id)arg1;

@end

