//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGZoomLoggerProtocol.h"

@class IGFeedItemZoomHandler, NSString;

@interface IGFeedItemZoomLogger : NSObject <IGZoomLoggerProtocol>
{
    _Bool _zoomEnabled;
    IGFeedItemZoomHandler *_zoomHandler;
    id <IGFeedItemDirectResponseLoggingProviderDelegate> _loggingProvider;
}

- (void).cxx_destruct;
- (id)buildDirectResponseInfoForCell:(id)arg1;
- (id)initWithZoomHandler:(id)arg1 loggingProvider:(id)arg2;
- (void)logZoomDidBeginWithZoomController:(id)arg1 extras:(id)arg2;
- (void)logZoomDidEndWithZoomController:(id)arg1 extras:(id)arg2;
- (void)logZoomWillBeginWithZoomController:(id)arg1 extras:(id)arg2;
- (void)logZoomWillEndWithZoomController:(id)arg1 extras:(id)arg2;
@property(nonatomic) __weak id <IGFeedItemDirectResponseLoggingProviderDelegate> loggingProvider; // @synthesize loggingProvider=_loggingProvider;
@property(nonatomic) __weak IGFeedItemZoomHandler *zoomHandler; // @synthesize zoomHandler=_zoomHandler;
@property(readonly, nonatomic) _Bool zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

