//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedSectionControllerTrackingComponentsProtocol.h"

@class NSString;

@interface IGFeedSectionControllerNoOpTrackingComponents : NSObject <IGFeedSectionControllerTrackingComponentsProtocol>
{
}

- (void)adapterDidCompleteUpdate;
- (void)scrollViewDidEndScrolling;
- (void)scrollViewDidScroll;
- (void)viewDidAppear;
- (void)viewWillDisappear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

