//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol IGFeedItemVisibilityTracking <NSObject>
- (void)updateWithCellTrackingData:(NSArray *)arg1 sectionHeaderTrackingData:(NSArray *)arg2 visibleContentRect:(struct CGRect)arg3;
@end

