//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItemPhotoCell;

@protocol IGFeedItemPhotoCellDelegate <NSObject>
- (void)feedItemPhotoCellDidDoubleTapToLike:(IGFeedItemPhotoCell *)arg1;
- (void)feedItemPhotoCellDidShowTags:(IGFeedItemPhotoCell *)arg1;
- (void)feedItemPhotoCellDidSingleTap:(IGFeedItemPhotoCell *)arg1;
- (void)feedItemPhotoCellImageDidLoadImage:(IGFeedItemPhotoCell *)arg1;
- (void)feedItemPhotoCellPercentVisibleDidChange:(IGFeedItemPhotoCell *)arg1 percentVisible:(double)arg2;
@end

