//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItemBusinessCell;

@protocol IGFeedItemBusinessCellDelegate <NSObject>
- (void)feedItemBusinessCellDidTapPromote:(IGFeedItemBusinessCell *)arg1;
- (void)feedItemBusinessCellDidTapViewAdGuideline:(IGFeedItemBusinessCell *)arg1;
- (void)feedItemBusinessCellDidTapViewInsights:(IGFeedItemBusinessCell *)arg1;
@end

