//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGAppInstallationsHelper, IGUserSession, NSAttributedString, NSMutableAttributedString, NSString, NSURL, UIImage;

@interface IGFeedPromotionBannerConfiguration : NSObject
{
    _Bool _showDismissButton;
    _Bool _promotionDismissed;
    NSString *_title;
    NSString *_subtitle;
    NSString *_buttonText;
    long long _feedPromotionBannerType;
    UIImage *_icon;
    CDUnknownBlockType _cellTapActionBlock;
    CDUnknownBlockType _cellImpressionActionBlock;
    CDUnknownBlockType _cellDismssActionBlock;
    CDUnknownBlockType _cellPromotionButtonTappedActionBlock;
    IGUserSession *_userSession;
    IGAppInstallationsHelper *_appInstallationsHelper;
    NSMutableAttributedString *_mutableCenterText;
    NSURL *_iconURL;
    NSString *_appId;
    NSString *_uuid;
}

+ (id)iconImageForPromotionType:(long long)arg1;
+ (void)logForAction:(id)arg1 reason:(id)arg2 type:(id)arg3 uuid:(id)arg4 networker:(id)arg5;
+ (id)stringForPromotionType:(long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) IGAppInstallationsHelper *appInstallationsHelper; // @synthesize appInstallationsHelper=_appInstallationsHelper;
- (void)buildCenterTextWithTextRuns:(id)arg1;
@property(retain, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(copy, nonatomic) CDUnknownBlockType cellDismssActionBlock; // @synthesize cellDismssActionBlock=_cellDismssActionBlock;
@property(copy, nonatomic) CDUnknownBlockType cellImpressionActionBlock; // @synthesize cellImpressionActionBlock=_cellImpressionActionBlock;
@property(copy, nonatomic) CDUnknownBlockType cellPromotionButtonTappedActionBlock; // @synthesize cellPromotionButtonTappedActionBlock=_cellPromotionButtonTappedActionBlock;
@property(copy, nonatomic) CDUnknownBlockType cellTapActionBlock; // @synthesize cellTapActionBlock=_cellTapActionBlock;
@property(readonly, nonatomic) NSAttributedString *centerText;
@property(nonatomic) long long feedPromotionBannerType; // @synthesize feedPromotionBannerType=_feedPromotionBannerType;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSURL *iconURL; // @synthesize iconURL=_iconURL;
- (id)initWithButtonText:(id)arg1 centerText:(id)arg2 icon:(id)arg3 userSession:(id)arg4;
- (id)initWithDictionary:(id)arg1 userSession:(id)arg2;
- (id)initWithUserSession:(id)arg1;
- (void)logBannerButtonTapped;
- (void)logBannerDismissal;
- (void)logBannerImpression;
@property(retain, nonatomic) NSMutableAttributedString *mutableCenterText; // @synthesize mutableCenterText=_mutableCenterText;
- (id)nameOfFeedPromotionBannerType;
@property(nonatomic) _Bool promotionDismissed; // @synthesize promotionDismissed=_promotionDismissed;
@property(readonly, nonatomic) NSString *reuseIdentifier;
@property(nonatomic) _Bool showDismissButton; // @synthesize showDismissButton=_showDismissButton;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)setupActionBlockForBoomerang;
- (void)setupActionBlockForFollowDestination;
- (void)setupActionBlockForHyperlapse;
- (void)setupActionBlockForLayout;
- (void)setupActionBlocksForPromotionWithType:(long long)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

@end

