//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedItemVisibilityTracking.h"
#import "IGItemDiffingDelegate.h"

@class IGItemDiffing, NSString;

@interface IGFeedItemViewableImpressionTracker : NSObject <IGItemDiffingDelegate, IGFeedItemVisibilityTracking>
{
    IGItemDiffing *_tracker;
    id <IGFeedItemLoggingProviderDelegate> _loggingDelegate;
    id <IGAnalyticsModule> _analyticsModule;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <IGAnalyticsModule> analyticsModule; // @synthesize analyticsModule=_analyticsModule;
- (id)initWithLoggingProviderDelegate:(id)arg1 analyticsModule:(id)arg2;
- (void)itemDiffing:(id)arg1 didChangeWithItemAdded:(id)arg2;
- (void)itemDiffing:(id)arg1 didChangeWithItemRemoved:(id)arg2;
@property(readonly, nonatomic) __weak id <IGFeedItemLoggingProviderDelegate> loggingDelegate; // @synthesize loggingDelegate=_loggingDelegate;
@property(readonly, nonatomic) IGItemDiffing *tracker; // @synthesize tracker=_tracker;
- (void)updateWithCellTrackingData:(id)arg1 sectionHeaderTrackingData:(id)arg2 visibleContentRect:(struct CGRect)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

