//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileManager, NSURL;

@interface IGFileCoordinator : NSObject
{
    NSFileManager *_fileManager;
    NSURL *_filePathURL;
}

+ (_Bool)removeFileAtURL:(id)arg1;
+ (_Bool)removeFileAtURL:(id)arg1 withManager:(id)arg2;
- (void).cxx_destruct;
- (_Bool)archiveObject:(id)arg1;
@property(readonly, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, nonatomic) NSURL *filePathURL; // @synthesize filePathURL=_filePathURL;
- (id)initWithFileManager:(id)arg1 filePathURL:(id)arg2;
- (id)initWithFilePathURL:(id)arg1;
- (_Bool)removeFile;
- (id)unarchiveObject;

@end

