//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFilter.h"

#import "NSCopying.h"

@class NSMutableArray, NSMutableIndexSet;

@interface IGFilterGroup : IGFilter <NSCopying>
{
    NSMutableArray *_filters;
    unsigned long long _surfaceIdx;
    NSMutableIndexSet *_disabledFilters;
}

- (void).cxx_destruct;
- (void)addFilter:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)count;
- (id)firstFilter;
- (id)init;
- (void)insertFilter:(id)arg1 atIndex:(unsigned long long)arg2;
- (_Bool)isFilterAtIndexEnabled:(unsigned long long)arg1;
- (id)lastFilter;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)removeFilterAtIndex:(unsigned long long)arg1;
- (void)removeLastFilter;
- (void)render:(id)arg1 to:(id)arg2;
- (void)render:(id)arg1 to:(id *)arg2 consumeSource:(_Bool)arg3;
- (id)renderByConsumingSource:(id)arg1;
- (void)setFilterAtIndex:(unsigned long long)arg1 enabled:(_Bool)arg2;
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;

@end

