//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGSimpleButton, IGTextButton, IGUser, IGUserSession, NSString, UILabel;

@interface IGFriendRequestHeaderView : UIView
{
    _Bool _incomingRequestPending;
    IGUser *_user;
    id <IGFriendRequestHeaderViewDelegate> _delegate;
    IGUserSession *_userSession;
    IGSimpleButton *_approveButton;
    IGSimpleButton *_ignoreButton;
    IGTextButton *_approveTextButton;
    IGTextButton *_ignoreTextButton;
    UILabel *_followLabel;
    NSString *_buttonRedesignStyle;
}

- (void).cxx_destruct;
- (id)accessibilityElements;
- (void)addSubviews;
@property(readonly, nonatomic) IGSimpleButton *approveButton; // @synthesize approveButton=_approveButton;
- (double)approveButtonWidth;
@property(readonly, nonatomic) IGTextButton *approveTextButton; // @synthesize approveTextButton=_approveTextButton;
@property(copy, nonatomic) NSString *buttonRedesignStyle; // @synthesize buttonRedesignStyle=_buttonRedesignStyle;
- (void)dealloc;
@property(nonatomic) __weak id <IGFriendRequestHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UILabel *followLabel; // @synthesize followLabel=_followLabel;
- (void)hide;
@property(readonly, nonatomic) IGSimpleButton *ignoreButton; // @synthesize ignoreButton=_ignoreButton;
- (double)ignoreButtonWidth;
@property(readonly, nonatomic) IGTextButton *ignoreTextButton; // @synthesize ignoreTextButton=_ignoreTextButton;
- (id)initWithUserSession:(id)arg1;
- (void)layoutSubviews;
- (void)onApproveButtonTapped:(id)arg1;
- (void)onIgnoreButtonTapped:(id)arg1;
- (void)setUpApproveButton;
- (void)setUpApproveTextButton;
- (void)setUpFollowLabel;
- (void)setUpIgnoreButton;
- (void)setUpIgnoreTextButton;
- (void)setUpSubviews;
@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;
- (void)show;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateFollowStatus:(id)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

@end

