//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGProfilePictureImageView, UILabel;

@interface IGHideHeaderView : UIView
{
    _Bool _showUser;
    IGProfilePictureImageView *_profilePic;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
- (void)configureWithItem:(id)arg1;
- (void)configureWithTitle:(id)arg1 user:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) IGProfilePictureImageView *profilePic; // @synthesize profilePic=_profilePic;
@property(nonatomic) _Bool showUser; // @synthesize showUser=_showUser;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

