//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGHybridWebViewHeaderDelegate.h"
#import "UIWebViewDelegate.h"

@class IGHybridWebViewHeader, IGUserSession, NSString, UIActivityIndicatorView, UIWebView;

@interface IGHybridWebView : UIView <UIWebViewDelegate, IGHybridWebViewHeaderDelegate>
{
    id <IGHybridWebViewDelegate> _delegate;
    IGUserSession *_userSession;
    UIWebView *_webView;
    UIView *_loadingOverlayView;
    IGHybridWebViewHeader *_header;
    UIActivityIndicatorView *_spinner;
    id <IGHybridWebViewConfig> _config;
}

- (void).cxx_destruct;
- (unsigned long long)actionForScreen:(id)arg1 isRootScreen:(_Bool)arg2;
- (void)callToJS:(id)arg1;
- (void)clearTemporaryAuthCookies;
@property(readonly, nonatomic) id <IGHybridWebViewConfig> config; // @synthesize config=_config;
@property(nonatomic) __weak id <IGHybridWebViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disableLongPressGestures:(id)arg1;
@property(readonly, nonatomic) IGHybridWebViewHeader *header; // @synthesize header=_header;
- (void)hideSpinner;
- (id)initWithConfig:(id)arg1 userSession:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2 userSession:(id)arg3;
- (void)layoutSubviews;
- (void)loadRequest:(id)arg1;
@property(readonly, nonatomic) UIView *loadingOverlayView; // @synthesize loadingOverlayView=_loadingOverlayView;
- (void)setUpHeaderBar;
- (void)setUpNavigationBarWithParams:(id)arg1;
- (void)setUpViewHierarchy;
- (void)showSpinner;
@property(readonly, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
- (void)updateHeaderForCurrentStateWithParams:(id)arg1;
- (void)updateHeaderToLoadingView:(_Bool)arg1 withGreyOverlay:(_Bool)arg2 leftButtonEnabled:(_Bool)arg3;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewHeader:(id)arg1 didTapBackWithItem:(id)arg2;
- (void)webViewHeader:(id)arg1 didTapCloseWithItem:(id)arg2;
- (void)webViewHeader:(id)arg1 didTapRightButtonWithItem:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

