//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"

@class NSArray;

@interface IGInsightsMediaSectionModel : NSObject <IGListDiffable>
{
    NSArray *_feedItems;
}

- (void).cxx_destruct;
- (id)diffIdentifier;
@property(readonly, nonatomic) NSArray *feedItems; // @synthesize feedItems=_feedItems;
- (id)initWithFeedItems:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;

@end

