//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGInstaVideoCommentsContainerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class IGInstaVideoCommentsContainerView, IGTapButton, NSString, UITextField;

@interface IGInstaVideoBroadcastInteractionFooterView : UIView <UITextFieldDelegate, IGInstaVideoCommentsContainerViewDelegate>
{
    _Bool _commentsDisabled;
    id <IGInstaVideoBroadcastInteractionFooterViewDelegate> _delegate;
    UIView *_commentsDisabledLabel;
    UIView *_dividerView;
    UITextField *_commentTextField;
    UIView *_textFieldButtonContainer;
    IGTapButton *_moreButton;
    IGTapButton *_switchCameraButton;
    IGTapButton *_drawingButton;
    IGTapButton *_sendButton;
    IGInstaVideoCommentsContainerView *_commentsView;
    double _sidePadding;
}

+ (double)borderHeight;
- (void).cxx_destruct;
- (void)addComments:(id)arg1;
@property(readonly, nonatomic) UITextField *commentTextField; // @synthesize commentTextField=_commentTextField;
- (void)commentsContainerView:(id)arg1 didReceiveTapOnComment:(id)arg2 isPinned:(_Bool)arg3;
- (void)commentsContainerView:(id)arg1 didReceiveUnpinTapOnComment:(id)arg2;
- (void)commentsContainerViewHeightDidChange:(id)arg1;
@property(nonatomic) _Bool commentsDisabled; // @synthesize commentsDisabled=_commentsDisabled;
@property(readonly, nonatomic) UIView *commentsDisabledLabel; // @synthesize commentsDisabledLabel=_commentsDisabledLabel;
@property(readonly, nonatomic) IGInstaVideoCommentsContainerView *commentsView; // @synthesize commentsView=_commentsView;
- (void)configureDividerVisibility;
- (void)configureDrawingButton;
- (void)configureMoreButton;
- (void)configureSendButton;
- (void)configureSendButtonVisibility;
- (void)configureSwitchCameraButton;
- (id)currentPinnedComment;
@property(nonatomic) __weak id <IGInstaVideoBroadcastInteractionFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)displayLikerProfileImage:(id)arg1 likeCount:(long long)arg2 overDuration:(double)arg3;
- (void)displayNumLikes:(long long)arg1 fromSelf:(_Bool)arg2 overDuration:(double)arg3;
@property(readonly, nonatomic) UIView *dividerView; // @synthesize dividerView=_dividerView;
@property(readonly, nonatomic) IGTapButton *drawingButton; // @synthesize drawingButton=_drawingButton;
- (void)drawingButtonTapped;
- (struct CGRect)heartFrameWithSize:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1 sidePadding:(double)arg2;
- (_Bool)isEditingComment;
- (void)layoutSubviews;
@property(readonly, nonatomic) IGTapButton *moreButton; // @synthesize moreButton=_moreButton;
- (void)moreButtonTapped;
- (void)pinComment:(id)arg1;
- (void)removeAllCommentsFromUserPk:(id)arg1;
- (void)removeCommentWithPk:(id)arg1;
@property(readonly, nonatomic) IGTapButton *sendButton; // @synthesize sendButton=_sendButton;
- (void)sendButtonTapped;
- (void)showCommentTextField;
@property(readonly, nonatomic) double sidePadding; // @synthesize sidePadding=_sidePadding;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) IGTapButton *switchCameraButton; // @synthesize switchCameraButton=_switchCameraButton;
- (void)switchCamerasButtonTapped;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
@property(readonly, nonatomic) UIView *textFieldButtonContainer; // @synthesize textFieldButtonContainer=_textFieldButtonContainer;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)unpinComment;
- (void)updateCommentPk:(id)arg1 withComment:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

