//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGCountdownView, IGTapButton, UILabel;

@interface IGInstaVideoBroadcastSetupView : UIView
{
    id <IGInstaVideoBroadcastSetupViewDelegate> _delegate;
    UILabel *_statusLabel;
    UILabel *_startingLabel;
    IGTapButton *_cancelButton;
    IGCountdownView *_countdownView;
    UIView *_darkenView;
}

+ (id)createTextLabel;
- (void).cxx_destruct;
@property(readonly, nonatomic) IGTapButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)cancelButtonTapped;
- (void)cleanupFadingToggleAnimation;
@property(readonly, nonatomic) IGCountdownView *countdownView; // @synthesize countdownView=_countdownView;
@property(readonly, nonatomic) UIView *darkenView; // @synthesize darkenView=_darkenView;
@property(nonatomic) __weak id <IGInstaVideoBroadcastSetupViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doubleTapped:(id)arg1;
- (void)endRingAnimationAndHideIfNeeded;
- (void)enterStartingState;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setCount:(long long)arg1;
- (void)startRingAnimationIfNeeded;
@property(readonly, nonatomic) UILabel *startingLabel; // @synthesize startingLabel=_startingLabel;
@property(readonly, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;

@end

