//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGInsightsQuery;

@interface IGInsightsNavigationAction : NSObject
{
    long long _actionType;
    long long _clientNavigationType;
    IGInsightsQuery *_query;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(readonly, nonatomic) long long clientNavigationType; // @synthesize clientNavigationType=_clientNavigationType;
- (long long)clientNavigationTypeFromString:(id)arg1;
- (id)destinationViewControllerWithUserSession:(id)arg1 insightsLoggingHelper:(id)arg2;
- (id)initWithDictionary:(id)arg1 actionType:(long long)arg2;
@property(readonly, nonatomic) IGInsightsQuery *query; // @synthesize query=_query;

@end

