//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGInstaVideoBroadcastMainViewController, NSString;

@protocol IGInstaVideoBroadcastMainViewControllerDelegate <NSObject>
- (void)instaVideoMainViewController:(IGInstaVideoBroadcastMainViewController *)arg1 didFailWithMessage:(NSString *)arg2;
- (void)instaVideoMainViewControllerDidFinishSession:(IGInstaVideoBroadcastMainViewController *)arg1 afterSuccessfulBroadcasting:(_Bool)arg2;
@end

