//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGInstaVideoViewHelper : NSObject
{
}

+ (id)commentTextField;
+ (id)commentsDisabledLabel;
+ (id)dividerView;
+ (struct UIOffset)extraTapAreaNeededForButtonSize:(struct CGSize)arg1;
+ (id)goLiveButtonWithHeight:(double)arg1;
+ (id)sendButton;
+ (_Bool)shouldAllowCharactersChangeInRange:(struct _NSRange)arg1 textField:(id)arg2 replacementString:(id)arg3;
+ (id)topBannerLabelWithWidth:(double)arg1;

@end

