//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class IGInsightsHeaderView, IGInsightsLoggingHelper, IGInsightsParagraphComponent, IGTooltipView, IGUserSession, NSString, UICollectionView, UIPageControl;

@interface IGInsightsCenteredParagraphPageView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    _Bool _viewLoaded;
    id <IGInsightsToolTipDelegate> _toolTipDelegate;
    id <IGInsightsComponentUserInteractionDelegate> _userInteractionDelegate;
    UICollectionView *_collectionView;
    UIPageControl *_pageControl;
    IGInsightsParagraphComponent *_paragraphComponent;
    long long _currentLayoutIndex;
    UIView *_bottomSeparator;
    IGInsightsLoggingHelper *_loggingHelper;
    unsigned long long _surface;
    IGInsightsHeaderView *_headerView;
    unsigned long long _currentSelectedPage;
    IGTooltipView *_currentToolTip;
    IGUserSession *_userSession;
    id <IGInsightsCenteredParagraphWithImageViewDelegate> _paragraphViewDelegate;
    struct CGSize _unitSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (double)contentHeightForParagraphImageViewWithWidth:(double)arg1;
- (double)contentHeightForParagraphViewWithWidth:(double)arg1;
@property(nonatomic) long long currentLayoutIndex; // @synthesize currentLayoutIndex=_currentLayoutIndex;
@property(nonatomic) unsigned long long currentSelectedPage; // @synthesize currentSelectedPage=_currentSelectedPage;
@property(retain, nonatomic) IGTooltipView *currentToolTip; // @synthesize currentToolTip=_currentToolTip;
- (void)didDisplayParagraphViewAtIndex:(unsigned long long)arg1;
- (id)getCollectionViewFlowLayout;
@property(retain, nonatomic) IGInsightsHeaderView *headerView; // @synthesize headerView=_headerView;
- (id)initWithParagraphComponent:(id)arg1 loggingHelper:(id)arg2 surface:(unsigned long long)arg3 paragraphViewDelegate:(id)arg4 userSession:(id)arg5;
- (void)initializePageControl;
- (void)layoutSubviews;
- (void)logPageDisplayedAtIndex:(unsigned long long)arg1;
@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
- (double)pageCollectionViewHeightForBoundWidth:(double)arg1;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
- (void)pageControlValueChanged:(id)arg1;
@property(retain, nonatomic) IGInsightsParagraphComponent *paragraphComponent; // @synthesize paragraphComponent=_paragraphComponent;
@property(readonly, nonatomic) __weak id <IGInsightsCenteredParagraphWithImageViewDelegate> paragraphViewDelegate; // @synthesize paragraphViewDelegate=_paragraphViewDelegate;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setHeaderDelegate:(id)arg1;
@property(nonatomic) unsigned long long surface; // @synthesize surface=_surface;
@property(nonatomic) __weak id <IGInsightsToolTipDelegate> toolTipDelegate; // @synthesize toolTipDelegate=_toolTipDelegate;
@property(nonatomic) struct CGSize unitSize; // @synthesize unitSize=_unitSize;
@property(nonatomic) __weak id <IGInsightsComponentUserInteractionDelegate> userInteractionDelegate; // @synthesize userInteractionDelegate=_userInteractionDelegate;
@property(nonatomic) _Bool viewLoaded; // @synthesize viewLoaded=_viewLoaded;
- (void)showToolTipAtIndex:(unsigned long long)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateWidth:(double)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

