//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBVideoBroadcastSessionDelegate.h"

@class FBTimer, IGInstaVideoBroadcastLoggingContext, IGInstaVideoBroadcastMonitorService, IGInstaVideoSessionConfig, IGUserSession, NSString;

@interface IGInstaVideoBroadcastController : NSObject <FBVideoBroadcastSessionDelegate>
{
    _Bool _isSessionPaused;
    long long _status;
    id <IGInstaVideoBroadcastControllerDelegate> _delegate;
    double _maxDurationInSeconds;
    IGUserSession *_userSession;
    id <FBVideoBroadcastSession> _broadcastSession;
    IGInstaVideoSessionConfig *_config;
    double _pauseStartTimestamp;
    FBTimer *_speedTestTimeoutTimer;
    IGInstaVideoBroadcastLoggingContext *_loggingContext;
    IGInstaVideoBroadcastMonitorService *_broadcastMonitor;
    CDStruct_1b6d18a9 _baseTimestamp;
    CDStruct_1b6d18a9 _broadcastDuration;
    CDStruct_1b6d18a9 _recordingStartPTS;
    CDStruct_315660d5 _broadcastConfig;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) CDStruct_1b6d18a9 baseTimestamp; // @synthesize baseTimestamp=_baseTimestamp;
@property(nonatomic) CDStruct_315660d5 broadcastConfig; // @synthesize broadcastConfig=_broadcastConfig;
- (void)broadcastDidUpdateWithDuration:(CDStruct_1b6d18a9)arg1;
@property CDStruct_1b6d18a9 broadcastDuration; // @synthesize broadcastDuration=_broadcastDuration;
@property(readonly, nonatomic) double broadcastDurationInSeconds;
- (id)broadcastId;
@property(readonly, nonatomic) IGInstaVideoBroadcastMonitorService *broadcastMonitor; // @synthesize broadcastMonitor=_broadcastMonitor;
@property(retain, nonatomic) id <FBVideoBroadcastSession> broadcastSession; // @synthesize broadcastSession=_broadcastSession;
- (void)broadcastSession:(id)arg1 completedSpeedTestWithStatus:(struct FBNetworkSpeedTestStatus)arg2;
- (void)broadcastSession:(id)arg1 didDropPackets:(shared_ptr_896bc00e)arg2 dropReason:(id)arg3;
- (void)broadcastSession:(id)arg1 didUpdateStreamingInfo:(CDStruct_183fa7cb)arg2;
- (void)broadcastSessionDidChangeBitrate:(shared_ptr_44918ef6)arg1;
- (void)broadcastSessionDidFail:(id)arg1 withLoggingInfo:(struct FBVideoBroadcastSessionLoggingInfo)arg2;
- (void)broadcastSessionDidFinish:(id)arg1 withResult:(id)arg2;
- (void)broadcastSessionDidLoseConnection:(id)arg1 withReason:(id)arg2 error:(id)arg3;
- (void)broadcastSessionDidReconnect:(id)arg1 withReason:(id)arg2;
- (void)broadcastSessionDidStart:(id)arg1 withSpeedTestStatus:(struct FBNetworkSpeedTestStatus)arg2;
- (void)broadcastSessionSendDidTimeout:(id)arg1;
- (void)cameraDidChange;
- (void)cameraWillChange;
@property(retain, nonatomic) IGInstaVideoSessionConfig *config; // @synthesize config=_config;
- (void)createSessionWithVideoDimensions:(struct CGSize)arg1 audioQueue:(id)arg2 videoQueue:(id)arg3;
- (void)dealloc;
@property(nonatomic) __weak id <IGInstaVideoBroadcastControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endSessionWithReason:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fixBaseTimestamp;
- (id)initWithUserSession:(id)arg1 loggingContext:(id)arg2;
- (void)interpretSpeedTestStatus:(struct FBNetworkSpeedTestStatus)arg1;
- (void)invalidateSpeedTestTimer;
@property(readonly, nonatomic) _Bool isConnected;
@property _Bool isSessionPaused; // @synthesize isSessionPaused=_isSessionPaused;
@property(readonly, nonatomic) IGInstaVideoBroadcastLoggingContext *loggingContext; // @synthesize loggingContext=_loggingContext;
@property(readonly, nonatomic) double maxDurationInSeconds; // @synthesize maxDurationInSeconds=_maxDurationInSeconds;
- (void)pauseSessionWithReason:(long long)arg1;
@property(nonatomic) double pauseStartTimestamp; // @synthesize pauseStartTimestamp=_pauseStartTimestamp;
- (void)processAudio:(struct opaqueCMSampleBuffer *)arg1;
- (void)processVideo:(struct opaqueCMSampleBuffer *)arg1;
@property(nonatomic) CDStruct_1b6d18a9 recordingStartPTS; // @synthesize recordingStartPTS=_recordingStartPTS;
- (void)resumeSession;
@property(retain, nonatomic) FBTimer *speedTestTimeoutTimer; // @synthesize speedTestTimeoutTimer=_speedTestTimeoutTimer;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void)startBroadcast;
- (void)updateTimestampWithSampleBufferIfNeeded:(struct opaqueCMSampleBuffer *)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

