//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGInsightsCenteredTitleTabPageView, NSString, UIView;

@protocol IGInsightsCenteredTitleTabPageViewDataSource <NSObject>
- (NSString *)insightsCenteredTitleTabPageView:(IGInsightsCenteredTitleTabPageView *)arg1 titleForTabAtIndex:(unsigned long long)arg2;
- (UIView *)insightsCenteredTitleTabPageView:(IGInsightsCenteredTitleTabPageView *)arg1 viewForTabAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfContentViewsForInsightsCenteredTitleTabPageView:(IGInsightsCenteredTitleTabPageView *)arg1;
@end

