//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGStoryGradientRingView, UILabel;

@interface IGInstaVideoBroadcastEndingSummaryView : UIView
{
    UILabel *_summaryTitleLabel;
    UILabel *_totalViewerCountLabel;
    UIView *_finalViewerCellsContainer;
    IGStoryGradientRingView *_spinnerRing;
    long long _finalViewerCount;
}

+ (id)fadeInAnimationWithSpringtoValue:(double)arg1 beginTime:(double)arg2;
+ (id)newContentTitleLabelWithText:(id)arg1;
+ (double)profileImageSizeForWidth:(double)arg1;
+ (id)scaleUpAnimationWithSpringFromScale:(double)arg1 toScale:(double)arg2 beginTime:(double)arg3;
+ (id)totalViewerCountString:(long long)arg1;
+ (double)xOffsetForHorizontalCenteredViewWidth:(double)arg1 totalWidth:(double)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *finalViewerCellsContainer; // @synthesize finalViewerCellsContainer=_finalViewerCellsContainer;
- (double)finalViewerCellsContainerHeightForWidth:(double)arg1;
@property(nonatomic) long long finalViewerCount; // @synthesize finalViewerCount=_finalViewerCount;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setFinalSummaryViewViewerList:(id)arg1 andFinalViewerCount:(long long)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) IGStoryGradientRingView *spinnerRing; // @synthesize spinnerRing=_spinnerRing;
- (void)startSpinner;
@property(readonly, nonatomic) UILabel *summaryTitleLabel; // @synthesize summaryTitleLabel=_summaryTitleLabel;
@property(readonly, nonatomic) UILabel *totalViewerCountLabel; // @synthesize totalViewerCountLabel=_totalViewerCountLabel;

@end

