//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGInsightsCollectionViewDelegate.h"
#import "IGInsightsComponentViewController.h"
#import "IGInsightsHeaderViewDelegate.h"

@class IGInsightsCollectionView, IGInsightsLoggingHelper, IGInsightsQuery, IGUserSession, NSString;

@interface IGInsightsCollectionViewController : UIViewController <IGInsightsCollectionViewDelegate, IGInsightsHeaderViewDelegate, IGInsightsComponentViewController>
{
    id <IGInsightsComponentViewControllerNavigationDelegate> navigationDelegate;
    IGInsightsCollectionView *_insightsCollectionView;
    NSString *_header;
    IGInsightsQuery *_buttonQuery;
    IGInsightsLoggingHelper *_loggingHelper;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGInsightsQuery *buttonQuery; // @synthesize buttonQuery=_buttonQuery;
- (void)dealloc;
- (void)didSelectCellOnCollectionView:(id)arg1 ForFeedItem:(id)arg2;
- (void)didTapButtonOnHeaderView:(id)arg1;
@property(readonly, copy, nonatomic) NSString *header; // @synthesize header=_header;
- (id)initWithHeader:(id)arg1 buttonText:(id)arg2 buttonQuery:(id)arg3 mediaItemCount:(long long)arg4 loggingHelper:(id)arg5 userSession:(id)arg6;
@property(retain, nonatomic) IGInsightsCollectionView *insightsCollectionView; // @synthesize insightsCollectionView=_insightsCollectionView;
@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(nonatomic) __weak id <IGInsightsComponentViewControllerNavigationDelegate> navigationDelegate; // @synthesize navigationDelegate;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

