//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGInsightsComponentAdapter.h"
#import "IGInsightsComponentViewControllerNavigationDelegate.h"

@class IGInsightsChartComponent, IGInsightsChartView, IGInsightsChartViewController, IGInsightsLoggingHelper, IGUserSession, NSString;

@interface IGInsightsChartComponentAdapter : NSObject <IGInsightsComponentViewControllerNavigationDelegate, IGInsightsComponentAdapter>
{
    id <IGInsightsComponentNavigationDelegate> navigationDelegate;
    IGUserSession *_userSession;
    IGInsightsChartComponent *_component;
    IGInsightsChartView *_componentView;
    IGInsightsChartViewController *_chartViewController;
    IGInsightsLoggingHelper *_loggingHelper;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGInsightsChartViewController *chartViewController; // @synthesize chartViewController=_chartViewController;
@property(retain, nonatomic) IGInsightsChartComponent *component; // @synthesize component=_component;
@property(retain, nonatomic) IGInsightsChartView *componentView; // @synthesize componentView=_componentView;
- (void)didSelectNavigateInComponentViewController:(id)arg1 toViewController:(id)arg2 animated:(_Bool)arg3;
- (id)initWithComponent:(id)arg1 loggingHelper:(id)arg2 surface:(unsigned long long)arg3 userSession:(id)arg4;
- (_Bool)isComponentValid;
@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(nonatomic) __weak id <IGInsightsComponentNavigationDelegate> navigationDelegate; // @synthesize navigationDelegate;
- (void)showToolTip;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

