//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface IGInsightsHeaderView : UIView
{
    id <IGInsightsHeaderViewDelegate> _delegate;
    UILabel *_titleLabel;
    UIButton *_button;
    UIImageView *_iconView;
}

- (void).cxx_destruct;
- (void)_buttonClick:(id)arg1;
- (void)_layoutActionButton;
@property(readonly, nonatomic) UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak id <IGInsightsHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)initWithTitle:(id)arg1 buttonText:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

