//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface IGInsightsProgressView : UIView
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIView *_progressActiveRectView;
    UIView *_progressBackgroudRectView;
    double _percentage;
}

- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 percentage:(double)arg3;
- (void)layoutProgressCharts;
- (void)layoutSubviews;
- (void)layoutTitles;
@property(readonly, nonatomic) double percentage; // @synthesize percentage=_percentage;
@property(readonly, nonatomic) UIView *progressActiveRectView; // @synthesize progressActiveRectView=_progressActiveRectView;
@property(readonly, nonatomic) UIView *progressBackgroudRectView; // @synthesize progressBackgroudRectView=_progressBackgroudRectView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

