//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGInviteFriendsDataSource, NSArray;

@protocol IGInviteFriendsDataSourceDelegate <NSObject>
- (void)inviteFriendsDataSource:(IGInviteFriendsDataSource *)arg1 didLoadFriendsList:(NSArray *)arg2;
- (void)inviteFriendsDataSourceDidFailToLoad:(IGInviteFriendsDataSource *)arg1;
@end

