//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCommentModel, IGInstaVideoBroadcastInteractionFooterView, NSString;

@protocol IGInstaVideoBroadcastInteractionFooterViewDelegate <NSObject>
- (void)drawingButtonTappedInInteractionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1;
- (void)interactionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1 didEnterCommentText:(NSString *)arg2;
- (void)interactionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1 didReceiveTapOnComment:(IGCommentModel *)arg2 isPinned:(_Bool)arg3;
- (void)interactionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1 didReceiveUnpinTapOnComment:(IGCommentModel *)arg2;
- (void)interactionFooterViewHeightDidChange:(IGInstaVideoBroadcastInteractionFooterView *)arg1;
- (void)moreButtonTappedInInteractionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1;
- (void)switchCameraButtonTappedInInteractionFooterView:(IGInstaVideoBroadcastInteractionFooterView *)arg1;
@end

