//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCommentModel, IGInstaVideoBroadcast, IGInstaVideoViewerActionSheetController;

@protocol IGInstaVideoViewerActionSheetControllerDelegate <NSObject>
- (void)actionSheetController:(IGInstaVideoViewerActionSheetController *)arg1 didReportBroadcast:(IGInstaVideoBroadcast *)arg2 isSpam:(_Bool)arg3;
- (void)actionSheetController:(IGInstaVideoViewerActionSheetController *)arg1 didReportComment:(IGCommentModel *)arg2 inBroadcast:(IGInstaVideoBroadcast *)arg3 isSpam:(_Bool)arg4;
@end

