//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGInsightsFilterUnit, NSArray;

@interface IGInsightsMediaFilter : NSObject
{
    NSArray *_mediaTypes;
    NSArray *_dataOrderings;
    NSArray *_timeframes;
    unsigned long long _initialMediaTypeIndex;
    unsigned long long _initialDataOrderingIndex;
    unsigned long long _initialTimeFrameIndex;
    NSArray *_mediaTypeQueryItems;
    NSArray *_dataOrderingQueryItems;
    NSArray *_timeframeQueryItems;
    long long _mediaCellCategory;
    IGInsightsFilterUnit *_filterUnit;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *dataOrderingQueryItems; // @synthesize dataOrderingQueryItems=_dataOrderingQueryItems;
@property(copy, nonatomic) NSArray *dataOrderings; // @synthesize dataOrderings=_dataOrderings;
@property(retain, nonatomic) IGInsightsFilterUnit *filterUnit; // @synthesize filterUnit=_filterUnit;
- (unsigned long long)getInitialIndexForDataOrdering:(id)arg1;
- (unsigned long long)getInitialIndexForMediaType:(id)arg1;
- (unsigned long long)getInitialIndexForTimeframe:(id)arg1;
- (id)initWithFilterUnit:(id)arg1;
@property(nonatomic) unsigned long long initialDataOrderingIndex; // @synthesize initialDataOrderingIndex=_initialDataOrderingIndex;
@property(nonatomic) unsigned long long initialMediaTypeIndex; // @synthesize initialMediaTypeIndex=_initialMediaTypeIndex;
@property(nonatomic) unsigned long long initialTimeFrameIndex; // @synthesize initialTimeFrameIndex=_initialTimeFrameIndex;
@property(nonatomic) long long mediaCellCategory; // @synthesize mediaCellCategory=_mediaCellCategory;
@property(copy, nonatomic) NSArray *mediaTypeQueryItems; // @synthesize mediaTypeQueryItems=_mediaTypeQueryItems;
@property(copy, nonatomic) NSArray *mediaTypes; // @synthesize mediaTypes=_mediaTypes;
- (void)parseFilterUnit:(id)arg1;
@property(copy, nonatomic) NSArray *timeframeQueryItems; // @synthesize timeframeQueryItems=_timeframeQueryItems;
@property(copy, nonatomic) NSArray *timeframes; // @synthesize timeframes=_timeframes;
- (void)setupMediaTypes;
- (unsigned long long)updateInitialMediaType;
- (unsigned long long)updateInitialOrdering;
- (unsigned long long)updateInitialTimeframe;
- (void)updateOrderingAndTimeframeForMediaTypeAtIndex:(unsigned long long)arg1;

@end

