//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBTimer, NSString;

@interface IGInstaVideoLikePostingService : NSObject
{
    id <IGInstaVideoLikePostingServiceDelegate> _delegate;
    id <IGAPIClient> _networker;
    NSString *_mediaId;
    FBTimer *_batchLikeTimer;
    long long _numLikesInBatch;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FBTimer *batchLikeTimer; // @synthesize batchLikeTimer=_batchLikeTimer;
@property(nonatomic) __weak id <IGInstaVideoLikePostingServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleFiredTimer;
- (id)initWithMediaId:(id)arg1 networker:(id)arg2;
@property(readonly, copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(readonly, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(nonatomic) long long numLikesInBatch; // @synthesize numLikesInBatch=_numLikesInBatch;
- (void)postLike;

@end

