//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCommentModel, IGInstaVideoCommentPullingService, IGUser, NSArray, NSNumber;

@protocol IGInstaVideoCommentPullingServiceDelegate <NSObject>
- (void)pullingService:(IGInstaVideoCommentPullingService *)arg1 currentUser:(IGUser *)arg2 didFetchComments:(NSArray *)arg3 systemComments:(NSArray *)arg4 secondsPerComment:(NSNumber *)arg5 pinnedComment:(IGCommentModel *)arg6 isInitialFetch:(_Bool)arg7;
- (void)pullingService:(IGInstaVideoCommentPullingService *)arg1 didReceiveCommentMutedStatus:(_Bool)arg2;
@end

