//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListAdapterDataSource.h"

@class IGInsightsMediaSectionModel, IGInsightsSeeAllPostsTabContentViewDataSource, NSString;

@interface IGInsightsMediaListAdapterDataSource : NSObject <IGListAdapterDataSource>
{
    long long _queriedMediaCellCategory;
    IGInsightsSeeAllPostsTabContentViewDataSource *_dataSource;
    IGInsightsMediaSectionModel *_sectionModel;
    long long _mediaFeedType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGInsightsSeeAllPostsTabContentViewDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)initWithDataSource:(id)arg1 mediaFeedType:(long long)arg2;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
@property(readonly, nonatomic) long long mediaFeedType; // @synthesize mediaFeedType=_mediaFeedType;
- (id)objectsForListAdapter:(id)arg1;
@property(nonatomic) long long queriedMediaCellCategory; // @synthesize queriedMediaCellCategory=_queriedMediaCellCategory;
@property(readonly, copy, nonatomic) IGInsightsMediaSectionModel *sectionModel; // @synthesize sectionModel=_sectionModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

