//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSMutableArray;

@interface IGListGridCollectionViewLayout : UICollectionViewLayout
{
    double _minimumLineSpacing;
    double _minimumInteritemSpacing;
    NSMutableArray *_lineCache;
    NSMutableArray *_lineForItem;
    long long _itemPerLine;
    long long _lineNumber;
    struct CGSize _itemSize;
}

- (void).cxx_destruct;
- (struct CGSize)collectionViewContentSize;
- (void)commonInit;
@property(readonly, nonatomic) double contentHeight;
@property(readonly, nonatomic) double contentWidth;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) long long itemPerLine; // @synthesize itemPerLine=_itemPerLine;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
@property(readonly, copy, nonatomic) NSMutableArray *lineCache; // @synthesize lineCache=_lineCache;
@property(readonly, copy, nonatomic) NSMutableArray *lineForItem; // @synthesize lineForItem=_lineForItem;
@property(nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(nonatomic) double minimumInteritemSpacing; // @synthesize minimumInteritemSpacing=_minimumInteritemSpacing;
@property(nonatomic) double minimumLineSpacing; // @synthesize minimumLineSpacing=_minimumLineSpacing;
- (void)prepareLayout;
- (void)reloadLayout;
- (void)reloadLayoutWithConstantItemSize:(struct CGSize)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;

@end

