//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGListSectionController<IGListSectionType>, NSArray, NSBundle, NSIndexSet, NSString, UICollectionReusableView, UICollectionViewCell;

@protocol IGListCollectionContext <NSObject>
- (UICollectionViewCell *)cellForItemAtIndex:(long long)arg1 sectionController:(IGListSectionController<IGListSectionType> *)arg2;
@property(readonly, nonatomic) struct CGSize containerSize;
- (void)deleteInSectionController:(IGListSectionController<IGListSectionType> *)arg1 atIndexes:(NSIndexSet *)arg2;
- (UICollectionViewCell *)dequeueReusableCellFromStoryboardWithIdentifier:(NSString *)arg1 forSectionController:(IGListSectionController<IGListSectionType> *)arg2 atIndex:(long long)arg3;
- (UICollectionViewCell *)dequeueReusableCellOfClass:(Class)arg1 forSectionController:(IGListSectionController<IGListSectionType> *)arg2 atIndex:(long long)arg3;
- (UICollectionViewCell *)dequeueReusableCellWithNibName:(NSString *)arg1 bundle:(NSBundle *)arg2 forSectionController:(IGListSectionController<IGListSectionType> *)arg3 atIndex:(long long)arg4;
- (UICollectionReusableView *)dequeueReusableSupplementaryViewFromStoryboardOfKind:(NSString *)arg1 withIdentifier:(NSString *)arg2 forSectionController:(IGListSectionController<IGListSectionType> *)arg3 atIndex:(long long)arg4;
- (UICollectionReusableView *)dequeueReusableSupplementaryViewOfKind:(NSString *)arg1 forSectionController:(IGListSectionController<IGListSectionType> *)arg2 class:(Class)arg3 atIndex:(long long)arg4;
- (UICollectionReusableView *)dequeueReusableSupplementaryViewOfKind:(NSString *)arg1 forSectionController:(IGListSectionController<IGListSectionType> *)arg2 nibName:(NSString *)arg3 bundle:(NSBundle *)arg4 atIndex:(long long)arg5;
- (void)deselectItemAtIndex:(long long)arg1 sectionController:(IGListSectionController<IGListSectionType> *)arg2 animated:(_Bool)arg3;
- (long long)indexForCell:(UICollectionViewCell *)arg1 sectionController:(IGListSectionController<IGListSectionType> *)arg2;
- (void)insertInSectionController:(IGListSectionController<IGListSectionType> *)arg1 atIndexes:(NSIndexSet *)arg2;
- (void)performBatchAnimated:(_Bool)arg1 updates:(void (^)(void))arg2 completion:(void (^)(_Bool))arg3;
- (void)reloadInSectionController:(IGListSectionController<IGListSectionType> *)arg1 atIndexes:(NSIndexSet *)arg2;
- (void)reloadSectionController:(IGListSectionController<IGListSectionType> *)arg1;
- (void)scrollToSectionController:(IGListSectionController<IGListSectionType> *)arg1 atIndex:(long long)arg2 scrollPosition:(unsigned long long)arg3 animated:(_Bool)arg4;
- (long long)sectionForSectionController:(IGListSectionController<IGListSectionType> *)arg1;
- (NSArray *)visibleCellsForSectionController:(IGListSectionController<IGListSectionType> *)arg1;
@end

