//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexSet, NSSet;

@interface IGListBatchUpdateData : NSObject
{
    NSIndexSet *_insertSections;
    NSIndexSet *_deleteSections;
    NSSet *_moveSections;
    NSSet *_insertIndexPaths;
    NSSet *_deleteIndexPaths;
    NSSet *_reloadIndexPaths;
}

+ (void)cleanIndexPathsWithMap:(const unordered_map_e7911709 *)arg1 moves:(id)arg2 indexPaths:(id)arg3 deletes:(id)arg4 inserts:(id)arg5;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSSet *deleteIndexPaths; // @synthesize deleteIndexPaths=_deleteIndexPaths;
@property(readonly, nonatomic) NSIndexSet *deleteSections; // @synthesize deleteSections=_deleteSections;
- (id)description;
- (id)initWithInsertSections:(id)arg1 deleteSections:(id)arg2 moveSections:(id)arg3 insertIndexPaths:(id)arg4 deleteIndexPaths:(id)arg5 reloadIndexPaths:(id)arg6;
@property(readonly, nonatomic) NSSet *insertIndexPaths; // @synthesize insertIndexPaths=_insertIndexPaths;
@property(readonly, nonatomic) NSIndexSet *insertSections; // @synthesize insertSections=_insertSections;
@property(readonly, nonatomic) NSSet *moveSections; // @synthesize moveSections=_moveSections;
@property(readonly, nonatomic) NSSet *reloadIndexPaths; // @synthesize reloadIndexPaths=_reloadIndexPaths;

@end

