//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "IGImageViewDelegate.h"

@class IGInstaVideoIndicatorView, IGLiveCuratorAnimationCoordinator, IGLiveRippleEffectView, IGProfilePictureImageView, IGStoryGradientRingView, NSString, UIView;

@interface IGLiveCuratorContainerView : UIControl <IGImageViewDelegate>
{
    IGLiveCuratorAnimationCoordinator *_animationCoordinator;
    IGStoryGradientRingView *_ringView;
    IGLiveRippleEffectView *_rippleView;
    IGProfilePictureImageView *_curatorView;
    UIView *_dimmerView;
    IGInstaVideoIndicatorView *_instaVideoLabel;
    long long _highlightStyle;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGLiveCuratorAnimationCoordinator *animationCoordinator; // @synthesize animationCoordinator=_animationCoordinator;
- (void)configureWithCurators:(id)arg1;
- (void)configureWithUser:(id)arg1;
@property(readonly, nonatomic) IGProfilePictureImageView *curatorView; // @synthesize curatorView=_curatorView;
@property(readonly, nonatomic) UIView *dimmerView; // @synthesize dimmerView=_dimmerView;
@property(readonly, nonatomic) long long highlightStyle; // @synthesize highlightStyle=_highlightStyle;
- (void)imageViewLoadedImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 highlightStyle:(long long)arg2;
@property(readonly, nonatomic) IGInstaVideoIndicatorView *instaVideoLabel; // @synthesize instaVideoLabel=_instaVideoLabel;
@property(readonly, nonatomic) IGStoryGradientRingView *ringView; // @synthesize ringView=_ringView;
@property(readonly, nonatomic) IGLiveRippleEffectView *rippleView; // @synthesize rippleView=_rippleView;
- (void)setHighlighted:(_Bool)arg1;
- (void)startCuratorPulsingAnimation;
- (void)willMoveToSuperview:(id)arg1;
- (void)willMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

