//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStorableObject.h"

#import "IGDirectMessageProducer.h"
#import "IGListDiffable.h"

@class CLLocation, NSNumber, NSString;

@interface IGLocation : IGStorableObject <IGDirectMessageProducer, IGListDiffable>
{
    CLLocation *_locationCoord;
    NSString *_name;
    NSString *_streetAddress;
    NSNumber *_externalID;
    NSString *_externalIDSource;
    NSString *_externalSource;
    NSString *_foursquareV2ID;
    NSString *_facebookPlacesID;
    NSString *_facebookEventsID;
}

+ (id)centralizedStore;
+ (id)networkRequestParamsForLocation:(id)arg1;
+ (id)unmanagedLocationWithDictionary:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)diffIdentifier;
- (void)encodeWithCoder:(id)arg1;
@property(retain) NSNumber *externalID; // @synthesize externalID=_externalID;
@property(retain) NSString *externalIDSource; // @synthesize externalIDSource=_externalIDSource;
@property(copy) NSString *externalSource; // @synthesize externalSource=_externalSource;
@property(copy) NSString *facebookEventsID; // @synthesize facebookEventsID=_facebookEventsID;
@property(copy) NSString *facebookPlacesID; // @synthesize facebookPlacesID=_facebookPlacesID;
@property(copy) NSString *foursquareV2ID; // @synthesize foursquareV2ID=_foursquareV2ID;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;
@property(retain) CLLocation *locationCoord; // @synthesize locationCoord=_locationCoord;
@property(readonly) long long locationType;
@property(readonly, nonatomic) NSString *loggingId;
- (id)messageWithParameter:(id)arg1 mediaUploadManager:(id)arg2 currentUser:(id)arg3;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)relatedItemDisplayName;
- (id)relatedItemId;
- (id)relatedItemPath;
- (id)relatedItemType;
@property(copy) NSString *streetAddress; // @synthesize streetAddress=_streetAddress;
- (_Bool)updateWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

