//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableOrderedSet, NSObject<OS_dispatch_queue>;

@interface IGLRUCache : NSObject
{
    long long _totalCostLimit;
    NSMutableDictionary *_objects;
    NSMutableOrderedSet *_queue;
    long long _totalCost;
    NSObject<OS_dispatch_queue> *_accessQueue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
- (id)description;
- (void)evictCachedObjectsIfNeeded;
- (id)initWithTotalCostLimit:(long long)arg1;
- (id)objectForKey:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *objects; // @synthesize objects=_objects;
@property(readonly, nonatomic) NSMutableOrderedSet *queue; // @synthesize queue=_queue;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 cost:(long long)arg3;
@property(nonatomic) long long totalCost; // @synthesize totalCost=_totalCost;
@property(nonatomic) long long totalCostLimit; // @synthesize totalCostLimit=_totalCostLimit;

@end

