//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedNetworkSourceDelegate.h"

@class IGMainFeedHeaderController, IGMainFeedNetworkSource, IGScrollViewState, IGStoryDataController, IGStoryTrayLoggingContext, IGUserSession, NSString;

@interface IGMainFeedNetworkSourceController : NSObject <IGFeedNetworkSourceDelegate>
{
    IGMainFeedNetworkSource *_feedNetworkSource;
    _Bool _ignoreStoryRefresh;
    _Bool _delayStoriesAfterFeed;
    id <IGMainFeedNetworkSourceControllerDelegate> _delegate;
    id <IGFeedNetworkSourceDelegate> _feedDelegate;
    IGMainFeedHeaderController *_mainFeedHeaderController;
    IGScrollViewState *_scrollViewState;
    IGStoryDataController *_storyDataController;
    IGStoryTrayLoggingContext *_storyTrayLoggingContext;
    IGUserSession *_userSession;
    NSString *_analyticsModule;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
- (void)dealloc;
@property(nonatomic) __weak id <IGMainFeedNetworkSourceControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <IGFeedNetworkSourceDelegate> feedDelegate; // @synthesize feedDelegate=_feedDelegate;
@property(readonly, nonatomic) IGMainFeedNetworkSource *feedNetworkSource; // @synthesize feedNetworkSource=_feedNetworkSource;
- (void)feedNetworkSource:(id)arg1 didChangeToObjects:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didFailToLoadForFetchAction:(long long)arg2;
- (void)feedNetworkSource:(id)arg1 didFinishLoadingObjects:(id)arg2 forFetchAction:(long long)arg3;
- (void)feedNetworkSource:(id)arg1 didReceiveResponseForConfig:(id)arg2;
- (void)feedNetworkSource:(id)arg1 didRefreshObjects:(id)arg2 allObjects:(id)arg3;
- (void)feedNetworkSource:(id)arg1 didStartLoadingForFetchAction:(long long)arg2;
- (void)feedNetworkSource:(id)arg1 willLoadItemsFromResponse:(id)arg2;
- (void)fetchDataOnStoryTray;
- (void)fetchDataWithMainFeedFetchReason:(long long)arg1;
- (id)initWithUserSession:(id)arg1;
@property(nonatomic) __weak IGMainFeedHeaderController *mainFeedHeaderController; // @synthesize mainFeedHeaderController=_mainFeedHeaderController;
- (void)onApplicationWillEnterForegroundNotification:(id)arg1;
- (void)onFeedItemPosted:(id)arg1;
- (void)refreshFeedAndStoriesAtWarmStart;
@property(nonatomic) __weak IGScrollViewState *scrollViewState; // @synthesize scrollViewState=_scrollViewState;
- (_Bool)shouldFetchAfterBackgroundInterval:(double)arg1;
- (_Bool)shouldFetchAtHeaderWithBackgroundInterval:(double)arg1;
@property(readonly, nonatomic) IGStoryDataController *storyDataController; // @synthesize storyDataController=_storyDataController;
@property(readonly, nonatomic) IGStoryTrayLoggingContext *storyTrayLoggingContext; // @synthesize storyTrayLoggingContext=_storyTrayLoggingContext;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

