//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectMessageProducer.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"

@class IGEditsMetadata, IGLocationMetadata, IGPostUploadModel, IGUsertagsMetadata, IGVideoInfo, IGVideoMetadata, NSArray, NSDate, NSDictionary, NSSet, NSString, UIImage;

@interface IGMediaMetadata : NSObject <IGDirectMessageProducer, NSSecureCoding, NSCopying>
{
    _Bool _shouldKeepCaptionOnMediaChange;
    _Bool _disableComments;
    _Bool _isDraft;
    NSString *_mediaMetadataId;
    NSDate *_creationDate;
    UIImage *_originalImage;
    NSString *_caption;
    long long _shareType;
    NSSet *_directRecipients;
    IGLocationMetadata *_locationMetadata;
    IGUsertagsMetadata *_usertagsMetadata;
    NSArray *_storyMentions;
    NSArray *_storyLinks;
    NSArray *_storyLocationStickers;
    NSArray *_internalFeatures;
    long long _mediaType;
    long long _sourceType;
    NSString *_sourceMediaID;
    NSDictionary *_exifData;
    long long _cameraPosition;
    double _deviceAngle;
    IGVideoMetadata *_videoMetadata;
    NSArray *_preselectedIdentifiers;
    IGEditsMetadata *_editsMetadata;
    IGPostUploadModel *_post;
    NSDate *_uploadStartTime;
    NSDate *_sharedAtTime;
    UIImage *_snapshot;
    UIImage *_unfilteredSnapshot;
    long long _preselectedMediaBehavior;
    UIImage *_preparedImage;
    IGVideoInfo *_preparedVideoInfo;
    struct CGRect _originalImageCropRect;
}

+ (void)cancelCurrentUploadForMediaMetadata:(id)arg1 userSession:(id)arg2;
+ (id)derivedImageForMediaMetadata:(id)arg1 userSession:(id)arg2;
+ (_Bool)hasEditedShareInfoForMediaMetadata:(id)arg1 userSession:(id)arg2 shareListManager:(id)arg3;
+ (id)shareListManagerForMediaMetadata:(id)arg1 userSession:(id)arg2;
+ (id)sharingInfoForMediaMetadata:(id)arg1 userSession:(id)arg2 shareListManager:(id)arg3;
+ (_Bool)supportsSecureCoding;
+ (id)uploadForMediaMetadata:(id)arg1 userSession:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) long long cameraPosition; // @synthesize cameraPosition=_cameraPosition;
- (void)cancelCurrentPost;
@property(copy, nonatomic) NSString *caption; // @synthesize caption=_caption;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)createLocationMetadata;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(readonly, copy) NSString *description;
@property(nonatomic) double deviceAngle; // @synthesize deviceAngle=_deviceAngle;
@property(retain, nonatomic) NSSet *directRecipients; // @synthesize directRecipients=_directRecipients;
@property(nonatomic) _Bool disableComments; // @synthesize disableComments=_disableComments;
@property(retain, nonatomic) IGEditsMetadata *editsMetadata; // @synthesize editsMetadata=_editsMetadata;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSDictionary *exifData; // @synthesize exifData=_exifData;
- (void)fetchVenueForUserSession:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)init;
- (id)initBlank;
- (id)initWithCoder:(id)arg1;
- (id)initWithMediaMetadataId:(id)arg1;
- (id)initWithSourceType:(long long)arg1 sourceMediaID:(id)arg2;
@property(copy, nonatomic) NSArray *internalFeatures; // @synthesize internalFeatures=_internalFeatures;
@property(nonatomic) _Bool isDraft; // @synthesize isDraft=_isDraft;
- (_Bool)isEqual:(id)arg1;
@property(retain, nonatomic) IGLocationMetadata *locationMetadata; // @synthesize locationMetadata=_locationMetadata;
@property(retain, nonatomic) NSString *mediaMetadataId; // @synthesize mediaMetadataId=_mediaMetadataId;
@property(nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
- (id)messageWithParameter:(id)arg1 mediaUploadManager:(id)arg2 currentUser:(id)arg3;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(nonatomic) struct CGRect originalImageCropRect; // @synthesize originalImageCropRect=_originalImageCropRect;
@property(retain, nonatomic) IGPostUploadModel *post; // @synthesize post=_post;
- (void)prepareForNewMediaOfType:(long long)arg1 fromSource:(long long)arg2 EXIFDictionary:(id)arg3 cameraPosition:(long long)arg4 deviceAngle:(double)arg5 videoMetadata:(id)arg6;
- (void)prepareForNewPhotoFromSource:(long long)arg1 EXIFDictionary:(id)arg2 cameraPosition:(long long)arg3 deviceAngle:(double)arg4;
- (void)prepareForNewVideo:(id)arg1;
- (void)prepareToShare;
@property(retain, nonatomic) UIImage *preparedImage; // @synthesize preparedImage=_preparedImage;
@property(retain, nonatomic) IGVideoInfo *preparedVideoInfo; // @synthesize preparedVideoInfo=_preparedVideoInfo;
@property(retain, nonatomic) NSArray *preselectedIdentifiers; // @synthesize preselectedIdentifiers=_preselectedIdentifiers;
@property(nonatomic) long long preselectedMediaBehavior; // @synthesize preselectedMediaBehavior=_preselectedMediaBehavior;
@property(nonatomic) long long shareType; // @synthesize shareType=_shareType;
@property(retain, nonatomic) NSDate *sharedAtTime; // @synthesize sharedAtTime=_sharedAtTime;
@property(nonatomic) _Bool shouldKeepCaptionOnMediaChange; // @synthesize shouldKeepCaptionOnMediaChange=_shouldKeepCaptionOnMediaChange;
@property(retain, nonatomic) UIImage *snapshot; // @synthesize snapshot=_snapshot;
@property(retain, nonatomic) NSString *sourceMediaID; // @synthesize sourceMediaID=_sourceMediaID;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(retain, nonatomic) NSArray *storyLinks; // @synthesize storyLinks=_storyLinks;
@property(retain, nonatomic) NSArray *storyLocationStickers; // @synthesize storyLocationStickers=_storyLocationStickers;
@property(retain, nonatomic) NSArray *storyMentions; // @synthesize storyMentions=_storyMentions;
@property(retain, nonatomic) UIImage *unfilteredSnapshot; // @synthesize unfilteredSnapshot=_unfilteredSnapshot;
@property(retain, nonatomic) NSDate *uploadStartTime; // @synthesize uploadStartTime=_uploadStartTime;
@property(retain, nonatomic) IGUsertagsMetadata *usertagsMetadata; // @synthesize usertagsMetadata=_usertagsMetadata;
@property(retain, nonatomic) IGVideoMetadata *videoMetadata; // @synthesize videoMetadata=_videoMetadata;
- (void)updateCoverFramePosition:(double)arg1;
- (void)updateEditsInfo:(id)arg1;
- (void)updateIsAudioMuted:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

