//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSURL;

@protocol IGMediaRequestDelegate <NSObject>
- (void)mediaRequestDidFailWithError:(NSError *)arg1 forURL:(NSURL *)arg2;
- (void)mediaRequestDidLoadMediaWithData:(NSData *)arg1 ofType:(unsigned long long)arg2 forURL:(NSURL *)arg3;
- (void)mediaRequestDownloadProgressDidChange:(double)arg1 forURL:(NSURL *)arg2;
@end

