//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGMediaCropViewController;

@protocol IGMediaCropViewDelegate <NSObject>
- (void)mediaCropView:(IGMediaCropViewController *)arg1 updatedAssetCropRect:(struct CGRect)arg2 cropMode:(long long)arg3;
@end

