//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMotionManager, NSOperationQueue;

@interface IGMotionManager : NSObject
{
    CMMotionManager *_motionManager;
    NSOperationQueue *_gravityQueue;
    _Bool _gravityActive;
    CDStruct_31142d93 _gravity;
}

- (void).cxx_destruct;
@property(nonatomic) CDStruct_31142d93 gravity; // @synthesize gravity=_gravity;
- (id)init;
@property(readonly, nonatomic, getter=isGravityActive) _Bool gravityActive; // @synthesize gravityActive=_gravityActive;
- (void)startGravityUpdatesToQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)stopGravityUpdates;

@end

