//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGRequestToken.h"

@class IGNetworkDispatcherOperation, NSProgress;

@interface IGNetworkDispatcherOperationRequestToken : NSObject <IGRequestToken>
{
    IGNetworkDispatcherOperation *_operation;
    NSProgress *_uploadProgress;
    NSProgress *_downloadProgress;
    id <IGRequestToken> _requestToken;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long behavior;
- (void)cancel;
- (void)dealloc;
- (id)downloadProgress;
- (id)initWithOperation:(id)arg1 ofType:(unsigned long long)arg2;
- (_Bool)isCancelled;
- (_Bool)isExecuting;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (long long)queuePriority;
@property(retain, nonatomic) id <IGRequestToken> requestToken; // @synthesize requestToken=_requestToken;
- (unsigned long long)requestType;
- (void)setQueuePriority:(long long)arg1;
- (double)totalBytesDown;
- (double)totalBytesUp;
- (double)totalRequestTimeInMilliseconds;
- (id)uploadProgress;

@end

