//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGSearchSectionController.h"

@class IGUserSession, NSString, UIViewController;

@interface IGNearbyPlacesBannerSectionController : NSObject <IGSearchSectionController>
{
    IGUserSession *_userSession;
    UIViewController *_viewController;
}

- (void).cxx_destruct;
- (id)analyticsInfoForItemAtIndexPath:(id)arg1;
- (id)initWithUserSession:(id)arg1 tableView:(id)arg2 viewController:(id)arg3;
- (unsigned long long)numberOfRows;
- (id)tableView:(id)arg1 cellForIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectIndexPath:(id)arg2 searchString:(id)arg3;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

