//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface IGNetworkOperationConcurrencyManager : NSObject
{
    NSMutableArray *_observers;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)addObserver:(id)arg1;
- (long long)concurrencyRateForTransferRate:(long long)arg1;
- (id)init;
- (void)removeObserver:(id)arg1;
- (void)startMonitoringTransferRateChanges;

@end

