//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface IGNetworkSource : NSObject
{
    _Bool _cancelsPreviousRequest;
    _Bool _loading;
    _Bool _loadingMore;
    id <IGNetworkSourceDelegate> _delegate;
    id <IGNetworkParser> _parser;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    id <IGAPIClient> _APIClient;
    id <IGRequestToken> _previousRequestToken;
    NSString *_maxId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <IGAPIClient> APIClient; // @synthesize APIClient=_APIClient;
- (void)cancel;
@property(readonly, nonatomic) _Bool cancelsPreviousRequest; // @synthesize cancelsPreviousRequest=_cancelsPreviousRequest;
@property(readonly, nonatomic) __weak id <IGNetworkSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
- (void)fetch;
- (void)fetchMore;
- (void)fetchWithLoadMore:(_Bool)arg1;
- (void)handleFailure:(id)arg1;
- (void)handleSuccessResponse:(id)arg1 isLoadMore:(_Bool)arg2;
- (id)initWithDelegate:(id)arg1 APIClient:(id)arg2 parser:(id)arg3 cancelsPreviousRequest:(_Bool)arg4;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(nonatomic, getter=isLoadingMore) _Bool loadingMore; // @synthesize loadingMore=_loadingMore;
- (_Bool)isMoreAvailable;
@property(copy, nonatomic) NSString *maxId; // @synthesize maxId=_maxId;
@property(readonly, nonatomic) id <IGNetworkParser> parser; // @synthesize parser=_parser;
@property(retain, nonatomic) id <IGRequestToken> previousRequestToken; // @synthesize previousRequestToken=_previousRequestToken;

@end

