//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGTagViewDelegate.h"

@class IGUser, NSArray, NSString;

@interface IGObjectInTagDisplayView : UIView <IGTagViewDelegate>
{
    IGUser *_currentUser;
    NSArray *_tagGroups;
    id <IGObjectInTagDisplayDelegate> _delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGUser *currentUser; // @synthesize currentUser=_currentUser;
- (void)dealloc;
@property(nonatomic) __weak id <IGObjectInTagDisplayDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)hasActiveTags;
- (void)hideAllTagsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (void)onTagsChanged;
@property(retain, nonatomic) NSArray *tagGroups; // @synthesize tagGroups=_tagGroups;
- (void)showAllTagsAnimated:(_Bool)arg1;
- (_Bool)tagViewCanBeSelected:(id)arg1;
- (void)tagViewDidEndMove:(id)arg1;
- (void)tagViewDidMove:(id)arg1;
- (void)tagViewWasRemoved:(id)arg1;
- (void)tagViewWasSelected:(id)arg1;
- (void)tagViewWillMove:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

