//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGItemVisibilityTrackerDelegate.h"
#import "IGMapCellDelegate.h"
#import "IGPhotoCellDelegate.h"
#import "IGVideoCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class IGBulkMediaRequestManager, IGFeedItem, IGFeedItemPageCellState, IGFeedItemVideoView, IGImagePreparer, IGItemVisibilityTracker, IGPageMediaVideoViewLoggerProvider, IGUser, NSArray, NSString, UICollectionView;

@interface IGPageMediaView : UIView <IGItemVisibilityTrackerDelegate, IGMapCellDelegate, IGPhotoCellDelegate, IGVideoCellDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UICollectionViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _supportsVideoStitching;
    _Bool _shouldPeek;
    _Bool _onScreen;
    _Bool _enteringView;
    NSArray *_items;
    IGFeedItemPageCellState *_pageCellState;
    double _percentVisible;
    id <IGPageMediaViewDelegate> _delegate;
    id <IGZoomControllerZoomingDelegate> _zoomingDelegate;
    IGPageMediaVideoViewLoggerProvider *_videoLoggerProvider;
    UICollectionView *_collectionView;
    IGBulkMediaRequestManager *_requestManager;
    IGItemVisibilityTracker *_itemVisibilityTracker;
    IGImagePreparer *_imagePreparer;
    IGUser *_currentUser;
    IGFeedItem *_feedItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(retain, nonatomic) IGUser *currentUser; // @synthesize currentUser=_currentUser;
@property(readonly, nonatomic) IGFeedItemVideoView *currentVideoView;
- (void)dealloc;
- (void)decodeAdjacentPhotosForItemAtIndex:(long long)arg1;
@property(nonatomic) __weak id <IGPageMediaViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool enteringView; // @synthesize enteringView=_enteringView;
@property(retain, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (void)handleIndexingForDidScroll:(id)arg1;
@property(retain, nonatomic) IGImagePreparer *imagePreparer; // @synthesize imagePreparer=_imagePreparer;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isOnScreen) _Bool onScreen; // @synthesize onScreen=_onScreen;
@property(retain, nonatomic) IGItemVisibilityTracker *itemVisibilityTracker; // @synthesize itemVisibilityTracker=_itemVisibilityTracker;
- (void)itemVisibilityTracker:(id)arg1 itemDidAppear:(id)arg2;
- (void)itemVisibilityTracker:(id)arg1 itemDidDisappear:(id)arg2;
- (void)itemVisibilityTracker:(id)arg1 itemDidStartViewing:(id)arg2;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
- (void)layoutSubviews;
- (void)mapCellDidDoubleTap:(id)arg1;
- (void)mapCellDidSingleTap:(id)arg1;
- (id)mapCellForItem:(id)arg1 indexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(retain, nonatomic) IGFeedItemPageCellState *pageCellState; // @synthesize pageCellState=_pageCellState;
@property(nonatomic) double percentVisible; // @synthesize percentVisible=_percentVisible;
- (double)percentVisibleForCell:(id)arg1;
- (void)photoCellDidDoubleTapToLike:(id)arg1;
- (void)photoCellDidSingleTap:(id)arg1;
- (id)photoCellForItem:(id)arg1 indexPath:(id)arg2;
- (void)photoCellImageDidLoadImage:(id)arg1;
- (void)prefetchMedia;
@property(retain, nonatomic) IGBulkMediaRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (void)scrollToPage:(long long)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setItems:(id)arg1 currentUser:(id)arg2;
@property(nonatomic) _Bool shouldPeek; // @synthesize shouldPeek=_shouldPeek;
@property(nonatomic) _Bool supportsVideoStitching; // @synthesize supportsVideoStitching=_supportsVideoStitching;
@property(retain, nonatomic) IGPageMediaVideoViewLoggerProvider *videoLoggerProvider; // @synthesize videoLoggerProvider=_videoLoggerProvider;
@property(nonatomic) __weak id <IGZoomControllerZoomingDelegate> zoomingDelegate; // @synthesize zoomingDelegate=_zoomingDelegate;
- (void)updateCollectionViewCellTransform:(struct CGAffineTransform)arg1;
- (void)updateContentOffsetFromPercentVisible:(double)arg1;
- (void)updateItemVisibility;
- (void)videoCell:(id)arg1 didToggleAudio:(_Bool)arg2;
- (void)videoCellDidDoubleTap:(id)arg1;
- (void)videoCellDidLoadImage:(id)arg1;
- (void)videoCellDidPlayToEnd:(id)arg1;
- (void)videoCellDidSingleTap:(id)arg1;
- (id)videoCellForItem:(id)arg1 indexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

