//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGTextButton, NSString, UIActivityIndicatorView, UIButton;

@interface IGPendingRequestView : UIView
{
    CDUnknownBlockType _acceptBlock;
    UIButton *_approveButton;
    UIButton *_ignoreButton;
    IGTextButton *_approveTextButton;
    IGTextButton *_ignoreTextButton;
    NSString *_buttonRedesignStyle;
    UIActivityIndicatorView *_spinner;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType acceptBlock; // @synthesize acceptBlock=_acceptBlock;
@property(retain, nonatomic) UIButton *approveButton; // @synthesize approveButton=_approveButton;
- (double)approveButtonWidth;
@property(retain, nonatomic) IGTextButton *approveTextButton; // @synthesize approveTextButton=_approveTextButton;
@property(copy, nonatomic) NSString *buttonRedesignStyle; // @synthesize buttonRedesignStyle=_buttonRedesignStyle;
@property(retain, nonatomic) UIButton *ignoreButton; // @synthesize ignoreButton=_ignoreButton;
- (double)ignoreButtonWidth;
@property(retain, nonatomic) IGTextButton *ignoreTextButton; // @synthesize ignoreTextButton=_ignoreTextButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)onApproveButtonTapped;
- (void)onIgnoreButtonTapped;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

