//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface IGRetroRegistrationFacebookButtonSeperator : UIView
{
    UILabel *_textLabel;
    UIView *_lineLeft;
    UIView *_lineRight;
}

- (void).cxx_destruct;
- (id)createTextLabelWithColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textColor:(id)arg2 lineColor:(id)arg3;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *lineLeft; // @synthesize lineLeft=_lineLeft;
@property(retain, nonatomic) UIView *lineRight; // @synthesize lineRight=_lineRight;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

