//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGRelatedItemsHeaderView, IGUserSession, NSIndexPath;

@protocol IGRelatedItemsHeaderViewDelegate <NSObject>
- (void)relatedItemsHeaderView:(IGRelatedItemsHeaderView *)arg1 didTapItem:(id <IGRelatedItemType>)arg2 atIndexPath:(NSIndexPath *)arg3 userSession:(IGUserSession *)arg4;
- (void)relatedItemsHeaderView:(IGRelatedItemsHeaderView *)arg1 willDisplayItem:(id <IGRelatedItemType>)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

