//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGCoreTextLinkHandler.h"
#import "IGCountryCodeViewControllerDelegate.h"
#import "IGRetroRegistrationContactPointViewDelegate.h"
#import "IGTextFieldDelegate.h"

@class IGRetroRegistrationContactPointView, NSString, UITapGestureRecognizer;

@interface IGRetroRegistrationContactPointViewController : UIViewController <IGRetroRegistrationContactPointViewDelegate, IGCoreTextLinkHandler, IGTextFieldDelegate, IGCountryCodeViewControllerDelegate>
{
    _Bool _hasSwitchedToEmailTab;
    id <IGRetroRegistrationContactPointViewControllerDelegate> _delegate;
    IGRetroRegistrationContactPointView *_contactPointView;
    UITapGestureRecognizer *_tapGesture;
    long long _contactPointType;
    NSString *_contactPoint;
    id <IGAPIClient> _networker;
}

- (void).cxx_destruct;
- (void)backgroundViewTapped;
@property(copy, nonatomic) NSString *contactPoint; // @synthesize contactPoint=_contactPoint;
@property(nonatomic) long long contactPointType; // @synthesize contactPointType=_contactPointType;
@property(retain, nonatomic) IGRetroRegistrationContactPointView *contactPointView; // @synthesize contactPointView=_contactPointView;
- (void)contactPointView:(id)arg1 didSelectContactPointType:(long long)arg2 wasFirstResponder:(_Bool)arg3;
- (void)contactPointViewDidTapFooterLoginButton;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)countryCodeButtonTapped;
@property(nonatomic) __weak id <IGRetroRegistrationContactPointViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapSignInButton;
@property(nonatomic) _Bool hasSwitchedToEmailTab; // @synthesize hasSwitchedToEmailTab=_hasSwitchedToEmailTab;
- (id)initWithNetworker:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)logNextButtonBlocked:(id)arg1;
@property(readonly, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
- (void)nextButtonTapped;
- (_Bool)prefersNavigationBarHidden;
- (_Bool)prefersStatusBarHidden;
- (void)registerWithEmail;
- (void)registerWithPhone;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)userDidSelectCountryWithName:(id)arg1 countryNumber:(id)arg2;
- (void)validateEmail:(id)arg1;
- (_Bool)validateEmailField:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

