//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CADisplayLink, IGRefreshSpinner, UIScrollView, UISelectionFeedbackGenerator;

@interface IGRefreshControl : UIControl
{
    long long _refreshState;
    UIScrollView *_scrollView;
    double _triggerHeight;
    IGRefreshSpinner *_spinner;
    CADisplayLink *_displayLink;
    double _originalTopContentInset;
    double _disappearProgress;
    double _disappearInitialOffset;
    double _beginTime;
    UISelectionFeedbackGenerator *_feedbackGenerator;
}

- (void).cxx_destruct;
- (void)adjustContentInsetForLoading;
- (void)animateClosed;
- (double)animationProgress;
- (void)beginRefreshingStateUserInteractive:(_Bool)arg1;
@property(nonatomic) double beginTime; // @synthesize beginTime=_beginTime;
- (void)cancelDisplayLink;
@property(nonatomic) double disappearInitialOffset; // @synthesize disappearInitialOffset=_disappearInitialOffset;
@property(nonatomic) double disappearProgress; // @synthesize disappearProgress=_disappearProgress;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(readonly, nonatomic) UISelectionFeedbackGenerator *feedbackGenerator; // @synthesize feedbackGenerator=_feedbackGenerator;
- (void)finishingLoading;
- (id)initWithScrollView:(id)arg1 triggerHeight:(double)arg2;
- (void)layoutInSuperView;
- (void)layoutSubviews;
@property(nonatomic) double originalTopContentInset; // @synthesize originalTopContentInset=_originalTopContentInset;
- (double)realContentOffsetY;
@property(nonatomic) long long refreshState; // @synthesize refreshState=_refreshState;
- (void)reset;
- (double)scrollVelocity;
@property(readonly, nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDragging;
- (void)scrollViewDidScroll;
- (_Bool)scrollViewHasTouches;
- (void)setTopContentInset:(double)arg1;
@property(readonly, nonatomic) IGRefreshSpinner *spinner; // @synthesize spinner=_spinner;
- (void)startLoadingAnimated:(_Bool)arg1;
@property(readonly, nonatomic) double triggerHeight; // @synthesize triggerHeight=_triggerHeight;
- (void)updateDisappearAnimation;
- (void)updateOriginalTopContentInset;
- (void)updateWithAppearingProgress:(double)arg1;
- (double)viewHeight;

@end

