//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGFacebookButton, IGRetroRegistrationFacebookButtonSeperator;

@interface IGRetroRegistrationFacebookButtonContainer : UIView
{
    IGFacebookButton *_facebookButton;
    IGRetroRegistrationFacebookButtonSeperator *_facebookButtonSeparator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGFacebookButton *facebookButton; // @synthesize facebookButton=_facebookButton;
@property(retain, nonatomic) IGRetroRegistrationFacebookButtonSeperator *facebookButtonSeparator; // @synthesize facebookButtonSeparator=_facebookButtonSeparator;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

