//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGChevronTitleButton, IGFacebookButton, IGRetroRegistrationBackgroundView, IGRetroRegistrationFacebookButtonSeperator, UIButton, UIImageView, UILabel;

@interface IGRetroRegistrationWelcomeView : UIView
{
    UIButton *_dismissButton;
    UIImageView *_iconView;
    UILabel *_messageLabel;
    IGRetroRegistrationFacebookButtonSeperator *_facebookButtonSeparator;
    IGRetroRegistrationBackgroundView *_backgroundView;
    IGChevronTitleButton *_changeLanguageButton;
    IGFacebookButton *_facebookButton;
    UILabel *_socialContextLabel;
    UIButton *_signUpButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGRetroRegistrationBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) IGChevronTitleButton *changeLanguageButton; // @synthesize changeLanguageButton=_changeLanguageButton;
- (id)createSocialContextLabel;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) IGFacebookButton *facebookButton; // @synthesize facebookButton=_facebookButton;
@property(retain, nonatomic) IGRetroRegistrationFacebookButtonSeperator *facebookButtonSeparator; // @synthesize facebookButtonSeparator=_facebookButtonSeparator;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIButton *signUpButton; // @synthesize signUpButton=_signUpButton;
@property(retain, nonatomic) UILabel *socialContextLabel; // @synthesize socialContextLabel=_socialContextLabel;
- (void)showDismissButton;
- (void)updateFBLoginButtonWithFBName:(id)arg1 socialContext:(id)arg2;

@end

