//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGRetroRegistrationUtils : NSObject
{
}

+ (void)cleanUpInvalidCharactersFromUsernameField:(id)arg1;
+ (id)validateUsernameField:(id)arg1 networker:(id)arg2 failureBlock:(CDUnknownBlockType)arg3 successBlock:(CDUnknownBlockType)arg4;

@end

