//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSDKAccessToken, IGResetPasswordViewController, IGRetroRegistrationLoginViewController, IGTwoFactorInfo, NSDictionary, NSString, NSURL;

@protocol IGRetroRegistrationLoginViewControllerDelegate <NSObject>
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 didTapOnLoginHelperButtonWithUsername:(NSString *)arg2;
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 didTapOnURL:(NSURL *)arg2;
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 proceedRegistrationWithFBInfo:(NSDictionary *)arg2 facebookAccessToken:(FBSDKAccessToken *)arg3;
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 proceedTwoFactorWithInfo:(IGTwoFactorInfo *)arg2 facebookAccessToken:(FBSDKAccessToken *)arg3;
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 resetPasswordWithViewController:(IGResetPasswordViewController *)arg2;
- (void)loginViewController:(IGRetroRegistrationLoginViewController *)arg1 userEmailTakenAutoLoginWithLoggedInDict:(NSDictionary *)arg2;
- (void)loginViewControllerDidTapGoBackButton:(IGRetroRegistrationLoginViewController *)arg1;
- (void)loginViewControllerDidTapLoginButton:(IGRetroRegistrationLoginViewController *)arg1;
- (void)loginViewControllerDidTapSignUpButton:(IGRetroRegistrationLoginViewController *)arg1;
- (_Bool)loginViewControllerIsSwitchingUsers:(IGRetroRegistrationLoginViewController *)arg1;
- (void)loginViewControllerWantsToDismiss:(IGRetroRegistrationLoginViewController *)arg1;
@end

