//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGResetToFeedController : NSObject
{
}

+ (void)handleApplicationWillEnterForegroundAfterInterval:(double)arg1 forMainAppViewController:(id)arg2;
+ (double)resetFeedIntervalForTabBarItem:(long long)arg1;

@end

