//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UILabel;

@interface IGRelatedItemCollectionViewCell : UICollectionViewCell
{
    UILabel *_textLabel;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
- (void)configureWithRelatedItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;

@end

