//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class IGFileCoordinator, IGReelSeenStateStoreAnnouncer, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface IGReelSeenStateStore : NSObject <IGUserSessionClearableObject>
{
    IGReelSeenStateStoreAnnouncer *_announcer;
    NSString *_userSessionPK;
    id <IGAPIClient> _networker;
    NSObject<OS_dispatch_queue> *_archiveQueue;
    IGFileCoordinator *_fileCoordinator;
    NSMutableDictionary *_reelToLatestSeenMediaDateMap;
}

+ (void)clearForUserPK:(id)arg1;
- (void).cxx_destruct;
- (void)addListener:(id)arg1;
@property(readonly, nonatomic) IGReelSeenStateStoreAnnouncer *announcer; // @synthesize announcer=_announcer;
- (void)archive;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *archiveQueue; // @synthesize archiveQueue=_archiveQueue;
@property(readonly, nonatomic) IGFileCoordinator *fileCoordinator; // @synthesize fileCoordinator=_fileCoordinator;
- (id)initWithUserSessionPK:(id)arg1 networker:(id)arg2;
- (id)latestSeenMediaDateForReelPK:(id)arg1;
@property(readonly, copy, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(retain, nonatomic) NSMutableDictionary *reelToLatestSeenMediaDateMap; // @synthesize reelToLatestSeenMediaDateMap=_reelToLatestSeenMediaDateMap;
- (void)removeListener:(id)arg1;
- (void)sendPendingSeenStateToServer:(id)arg1;
- (void)setLatestSeenMediaDate:(id)arg1 forReelPK:(id)arg2;
- (_Bool)updateIfNeededWithLatestSeenMediaDate:(id)arg1 forReekPK:(id)arg2;
- (void)updateWithReelPKToSeenMap:(id)arg1;
@property(readonly, copy, nonatomic) NSString *userSessionPK; // @synthesize userSessionPK=_userSessionPK;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

