//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class IGNUXInterstitialView, IGUserSession;

@interface IGRUXViewController : UIViewController
{
    IGNUXInterstitialView *_welcomeBackView;
    IGUserSession *_userSession;
    id <IGRUXViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <IGRUXViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithUserSession:(id)arg1 delegate:(id)arg2;
- (void)onDoneButtonTapped;
- (_Bool)prefersNavigationBarHidden;
- (void)seeSuggestionsButtonTapped:(id)arg1;
- (void)skipButtonTapped:(id)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidLoad;
@property(readonly, nonatomic) IGNUXInterstitialView *welcomeBackView; // @synthesize welcomeBackView=_welcomeBackView;

@end

