//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class CALayer;

@interface IGSeparatorFooterView : UICollectionReusableView
{
    double _leftInset;
    double _rightInset;
    CALayer *_separatorLayer;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) double leftInset; // @synthesize leftInset=_leftInset;
@property(nonatomic) double rightInset; // @synthesize rightInset=_rightInset;
@property(readonly, nonatomic) CALayer *separatorLayer; // @synthesize separatorLayer=_separatorLayer;
- (void)setSeparatorColor:(id)arg1;

@end

