//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewCell.h"

@class UIActivityIndicatorView, UIImageView;

@interface IGSearchPromptCell : IGGroupedTableViewCell
{
    UIImageView *_searchGlyph;
    UIActivityIndicatorView *_spinner;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setIsSearching:(_Bool)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;

@end

