//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGTabPageViewController.h"

#import "IGNavSearchBarDelegate.h"
#import "IGSearchResultsViewControllerDelegate.h"
#import "IGTabPageViewControllerDelegate.h"

@class IGExploreAutocompleteSearchHelper, IGKVOHandle, IGNavSearchBar, IGUserSession, IGViewController<IGExploreSearchChildViewController>, NSDate, NSString, UIView;

@interface IGSearchViewController : IGTabPageViewController <IGNavSearchBarDelegate, IGTabPageViewControllerDelegate, IGSearchResultsViewControllerDelegate>
{
    _Bool _isActive;
    _Bool _willMoveToParentVC;
    IGExploreAutocompleteSearchHelper *_searchHelper;
    id <IGExploreSearchControllerDelegate> _searchDelegate;
    NSDate *_lastSearch;
    NSString *_querySessionId;
    NSString *_sessionId;
    IGUserSession *_userSession;
    IGNavSearchBar *_searchBar;
    IGViewController<IGExploreSearchChildViewController> *_topSearchViewController;
    IGViewController<IGExploreSearchChildViewController> *_userSearchViewController;
    IGViewController<IGExploreSearchChildViewController> *_hashtagSearchViewController;
    IGViewController<IGExploreSearchChildViewController> *_placesSearchViewController;
    IGKVOHandle *_topResultsContentOffsetObserver;
    IGKVOHandle *_userResultsContentOffsetObserver;
    IGKVOHandle *_hashtagResultsContentOffsetObserver;
    IGKVOHandle *_placeResultsContentOffsetObserver;
    UIView *_navView;
    UIView *_navLineView;
    struct CGRect _originalHostingContenViewFrame;
    struct CGRect _originalHostingTabControlFrame;
}

- (void).cxx_destruct;
- (id)analyticsExtras;
- (id)analyticsModule;
- (void)animatePushTransition:(id)arg1 duration:(double)arg2 complete:(CDUnknownBlockType)arg3;
- (id)createSearchObserverForSearchCollectionViewController:(id)arg1;
- (id)createSearchObserverForSearchResultViewController:(id)arg1;
- (void)dealloc;
- (void)didTapSearchResult;
- (_Bool)disableNavigationGesture;
- (_Bool)disableNonEdgeNavigationGesture;
- (_Bool)enableNavState;
- (void)fetchFrequentItemsIfNeeded;
@property(retain, nonatomic) IGKVOHandle *hashtagResultsContentOffsetObserver; // @synthesize hashtagResultsContentOffsetObserver=_hashtagResultsContentOffsetObserver;
@property(retain, nonatomic) IGViewController<IGExploreSearchChildViewController> *hashtagSearchViewController; // @synthesize hashtagSearchViewController=_hashtagSearchViewController;
- (id)initWithUserSession:(id)arg1;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
- (void)keyboardDidHide:(id)arg1;
@property(readonly, nonatomic) NSDate *lastSearch; // @synthesize lastSearch=_lastSearch;
@property(retain, nonatomic) UIView *navLineView; // @synthesize navLineView=_navLineView;
@property(retain, nonatomic) UIView *navView; // @synthesize navView=_navView;
- (void)onSearchTextDidChange:(id)arg1;
- (void)onSearchWillBecomeActive;
- (void)onSearchWillBecomeInactive;
@property(nonatomic) struct CGRect originalHostingContenViewFrame; // @synthesize originalHostingContenViewFrame=_originalHostingContenViewFrame;
@property(nonatomic) struct CGRect originalHostingTabControlFrame; // @synthesize originalHostingTabControlFrame=_originalHostingTabControlFrame;
- (void)pageViewController:(id)arg1 didPageToViewController:(id)arg2;
- (void)performPopTransition:(id)arg1 toVC:(id)arg2 duration:(double)arg3 complete:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) IGKVOHandle *placeResultsContentOffsetObserver; // @synthesize placeResultsContentOffsetObserver=_placeResultsContentOffsetObserver;
@property(retain, nonatomic) IGViewController<IGExploreSearchChildViewController> *placesSearchViewController; // @synthesize placesSearchViewController=_placesSearchViewController;
- (struct UIEdgeInsets)preferredContentInsets;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersNavigationBarHidden;
@property(copy, nonatomic) NSString *querySessionId; // @synthesize querySessionId=_querySessionId;
- (void)resetSearchViewForRootVC:(id)arg1;
@property(retain, nonatomic) IGNavSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarButtonTapped:(id)arg1;
- (void)searchBarCancelButtonTapped:(id)arg1;
- (void)searchBarChannelHomeTapped:(id)arg1;
- (void)searchBarDirectIconTapped:(id)arg1;
- (struct CGRect)searchBarFrame;
- (void)searchBarPeopleIconTapped:(id)arg1;
- (void)searchBarReturnKeyTapped:(id)arg1;
- (void)searchBarWillBeginEditing:(id)arg1;
- (void)searchBarWillEndEditing:(id)arg1;
@property(nonatomic) __weak id <IGExploreSearchControllerDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
- (void)searchDidEnd;
- (void)searchDidStart;
@property(readonly, nonatomic) IGExploreAutocompleteSearchHelper *searchHelper; // @synthesize searchHelper=_searchHelper;
- (void)searchTableViewController:(id)arg1 didChangeSearchText:(id)arg2;
@property(readonly, copy, nonatomic) NSString *searchText;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) IGKVOHandle *topResultsContentOffsetObserver; // @synthesize topResultsContentOffsetObserver=_topResultsContentOffsetObserver;
@property(retain, nonatomic) IGViewController<IGExploreSearchChildViewController> *topSearchViewController; // @synthesize topSearchViewController=_topSearchViewController;
@property(retain, nonatomic) IGKVOHandle *userResultsContentOffsetObserver; // @synthesize userResultsContentOffsetObserver=_userResultsContentOffsetObserver;
@property(retain, nonatomic) IGViewController<IGExploreSearchChildViewController> *userSearchViewController; // @synthesize userSearchViewController=_userSearchViewController;
@property(nonatomic) _Bool willMoveToParentVC; // @synthesize willMoveToParentVC=_willMoveToParentVC;
- (void)updateRecentHideItems;
- (void)updateSearchbarPlaceholderForController:(id)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)willMoveToParentViewController:(id)arg1;

// Remaining properties
@property(retain, nonatomic) IGViewController<IGExploreSearchChildViewController> *currentViewController; // @dynamic currentViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

