//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableOrderedSet, NSMutableSet;

@interface IGSeenStateObject : NSObject <NSCoding, NSCopying>
{
    _Bool _isSeenStateSync;
    NSMutableOrderedSet *_unseenIDs;
    NSMutableSet *_seenIDs;
}

+ (id)seenStateObjectWithSeenIDs:(id)arg1 unseenIDs:(id)arg2 seenStateSync:(_Bool)arg3;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool isSeenStateSync; // @synthesize isSeenStateSync=_isSeenStateSync;
@property(readonly, nonatomic) NSMutableSet *seenIDs; // @synthesize seenIDs=_seenIDs;
- (id)seenIDsString;
@property(readonly, nonatomic) NSMutableOrderedSet *unseenIDs; // @synthesize unseenIDs=_unseenIDs;
- (id)unseenIDsString;

@end

