//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PHPhotoLibraryChangeObserver.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOrderedSet, NSString, PHAssetCollection, PHCachingImageManager, PHFetchResult, PHImageRequestOptions, UIActivityIndicatorView, UITableView, UIView;

@interface IGSelectAlbumController : UIViewController <UITableViewDataSource, UITableViewDelegate, PHPhotoLibraryChangeObserver>
{
    _Bool _needsSetPhotoLibraryOptions;
    id <IGSelectAlbumDelegate> _delegate;
    unsigned long long _assetFilterType;
    long long _selectAlbumAppearanceType;
    double _tableViewViewHeight;
    double _maximumContentWidth;
    NSOrderedSet *_allowedAlbumTitles;
    UITableView *_tableView;
    UIActivityIndicatorView *_activityIndicator;
    NSObject<OS_dispatch_queue> *_queue;
    PHAssetCollection *_userLibrary;
    PHFetchResult *_unfilteredSmartAlbums;
    PHFetchResult *_smartAlbums;
    PHFetchResult *_albums;
    NSMutableDictionary *_keyImageFetchResults;
    PHCachingImageManager *_imageManager;
    PHImageRequestOptions *_options;
    UIView *_topSeparatorLine;
    struct CGSize _thumbnailSize;
    struct CGRect _previousPreheatRect;
}

+ (id)allAlbumTitle;
- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) PHFetchResult *albums; // @synthesize albums=_albums;
@property(retain, nonatomic) NSOrderedSet *allowedAlbumTitles; // @synthesize allowedAlbumTitles=_allowedAlbumTitles;
@property(nonatomic) unsigned long long assetFilterType; // @synthesize assetFilterType=_assetFilterType;
- (id)assetsAtIndexPaths:(id)arg1;
- (id)collectionAtIndexPath:(id)arg1;
- (id)collectionFetchResultAtIndexPath:(id)arg1;
- (void)computeDifferenceBetweenRect:(struct CGRect)arg1 andRect:(struct CGRect)arg2 removedHandler:(CDUnknownBlockType)arg3 addedHandler:(CDUnknownBlockType)arg4;
- (void)configureForAppearanceType:(long long)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <IGSelectAlbumDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)enumerateCollections:(CDUnknownBlockType)arg1;
- (id)fetchOptions;
- (id)filterSmartAlbums:(id)arg1;
@property(retain, nonatomic) PHCachingImageManager *imageManager; // @synthesize imageManager=_imageManager;
- (id)indexPathsFromIndexes:(id)arg1 section:(long long)arg2;
- (id)initWithAppearanceType:(long long)arg1 maximumContentWidth:(double)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)keyImageFetchResultForAssetCollection:(id)arg1;
@property(retain) NSMutableDictionary *keyImageFetchResults; // @synthesize keyImageFetchResults=_keyImageFetchResults;
- (void)loadData;
@property(readonly, nonatomic) double maximumContentWidth; // @synthesize maximumContentWidth=_maximumContentWidth;
@property(nonatomic) _Bool needsSetPhotoLibraryOptions; // @synthesize needsSetPhotoLibraryOptions=_needsSetPhotoLibraryOptions;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) PHImageRequestOptions *options; // @synthesize options=_options;
- (void)photoLibraryDidChange:(id)arg1;
@property(nonatomic) struct CGRect previousPreheatRect; // @synthesize previousPreheatRect=_previousPreheatRect;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)resetCachedAssets;
- (void)scrollToTop;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) long long selectAlbumAppearanceType; // @synthesize selectAlbumAppearanceType=_selectAlbumAppearanceType;
- (void)setPhotosLibraryOptions;
@property(retain, nonatomic) PHFetchResult *smartAlbums; // @synthesize smartAlbums=_smartAlbums;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) double tableViewViewHeight; // @synthesize tableViewViewHeight=_tableViewViewHeight;
@property(nonatomic) struct CGSize thumbnailSize; // @synthesize thumbnailSize=_thumbnailSize;
@property(retain, nonatomic) UIView *topSeparatorLine; // @synthesize topSeparatorLine=_topSeparatorLine;
@property(retain, nonatomic) PHFetchResult *unfilteredSmartAlbums; // @synthesize unfilteredSmartAlbums=_unfilteredSmartAlbums;
@property(retain, nonatomic) PHAssetCollection *userLibrary; // @synthesize userLibrary=_userLibrary;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateCachedAssets;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidOpen;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

