//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGListAdapterDataSource.h"
#import "IGNetworkSourceDelegate.h"
#import "IGPageControlTitleViewDelegate.h"
#import "IGTableViewInfoViewSectionControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class IGCommerceFeedItemTracker, IGFeedDirectResponseHandler, IGFeedItem, IGListAdapter, IGListCollectionView, IGNetworkSource, IGPageControlTitleView, IGProductItem, IGProductItemImpressionTracker, IGShoppingViewerProductViewModel, IGUserSession, NSArray, NSString;

@interface IGShoppingViewerViewController : IGViewController <IGListAdapterDataSource, IGNetworkSourceDelegate, IGTableViewInfoViewSectionControllerDelegate, IGPageControlTitleViewDelegate, UIScrollViewDelegate>
{
    _Bool _isPanningToNextItem;
    _Bool _disableVisibilityLogging;
    IGUserSession *_userSession;
    IGFeedItem *_feedItem;
    NSArray *_initialProductItems;
    IGProductItem *_initialFocusedProductItem;
    IGNetworkSource *_networkSource;
    IGFeedDirectResponseHandler *_feedDirectResponseHandler;
    IGCommerceFeedItemTracker *_feedItemTracker;
    IGProductItemImpressionTracker *_productItemImpressionTracker;
    IGListCollectionView *_collectionView;
    IGListAdapter *_listAdapter;
    IGPageControlTitleView *_pageControlTitleView;
    NSArray *_productViewModels;
    IGShoppingViewerProductViewModel *_firstProduct;
    IGShoppingViewerProductViewModel *_focusedProduct;
    double _entryTime;
}

- (void).cxx_destruct;
- (id)analyticsModule;
@property(retain, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)didTapTableViewInfoViewSectionController:(id)arg1;
- (void)disableImpressionTracker;
- (_Bool)disableNavigationGesture;
@property(nonatomic) _Bool disableVisibilityLogging; // @synthesize disableVisibilityLogging=_disableVisibilityLogging;
- (void)doFetch;
- (id)emptyViewForListAdapter:(id)arg1;
@property(nonatomic) double entryTime; // @synthesize entryTime=_entryTime;
@property(readonly, nonatomic) IGFeedDirectResponseHandler *feedDirectResponseHandler; // @synthesize feedDirectResponseHandler=_feedDirectResponseHandler;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
@property(readonly, nonatomic) IGCommerceFeedItemTracker *feedItemTracker; // @synthesize feedItemTracker=_feedItemTracker;
- (void)fetchFullProductsAndReload;
@property(retain, nonatomic) IGShoppingViewerProductViewModel *firstProduct; // @synthesize firstProduct=_firstProduct;
@property(retain, nonatomic) IGShoppingViewerProductViewModel *focusedProduct; // @synthesize focusedProduct=_focusedProduct;
- (_Bool)forceAllowNavigationGesture;
- (id)getMostVisibleItem;
- (id)initWithUserSession:(id)arg1 feedItem:(id)arg2 feedItemTracker:(id)arg3 feedDirectResponseHandler:(id)arg4 title:(id)arg5 products:(id)arg6 currentProduct:(id)arg7;
@property(readonly, nonatomic) IGProductItem *initialFocusedProductItem; // @synthesize initialFocusedProductItem=_initialFocusedProductItem;
@property(readonly, nonatomic) NSArray *initialProductItems; // @synthesize initialProductItems=_initialProductItems;
@property(nonatomic) _Bool isPanningToNextItem; // @synthesize isPanningToNextItem=_isPanningToNextItem;
@property(retain, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
@property(readonly, nonatomic) IGNetworkSource *networkSource; // @synthesize networkSource=_networkSource;
- (void)networkSource:(id)arg1 didFailWithError:(id)arg2;
- (void)networkSource:(id)arg1 didFetchMoreWithObject:(id)arg2;
- (void)networkSource:(id)arg1 didFetchObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
@property(readonly, nonatomic) IGPageControlTitleView *pageControlTitleView; // @synthesize pageControlTitleView=_pageControlTitleView;
- (void)pageControlTitleView:(id)arg1 didChangeToPage:(long long)arg2;
- (_Bool)prefersTabBarHidden;
@property(readonly, nonatomic) IGProductItemImpressionTracker *productItemImpressionTracker; // @synthesize productItemImpressionTracker=_productItemImpressionTracker;
@property(retain, nonatomic) NSArray *productViewModels; // @synthesize productViewModels=_productViewModels;
- (id)requestWithMaxID:(id)arg1;
- (void)scrollToItem:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)updateFocusedModelItem;
- (void)updateImpressionTracker;
- (void)updateImpressionTrackerWithVisibleContentRect:(struct CGRect)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

