//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGImageFilter, UIImage;

@protocol IGSidecarCellType <NSObject>
@property(nonatomic) __weak id <IGSidecarCellDelegate> delegate;
@property(nonatomic) _Bool disabled;
@property(nonatomic) _Bool editButtonHidden;
@property(retain, nonatomic) UIImage *image;
@property(retain, nonatomic) IGImageFilter *imageFilter;
@property(nonatomic) _Bool tagButtonHidden;
@property(nonatomic) __weak id <IGSidecarCellTagPeopleDelegate> tagPeopleDelegate;
- (void)updateFilterStrength:(double)arg1;
@end

