//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UIGestureRecognizerDelegate.h"

@class CAShapeLayer, NSString, UIButton, UIImageView, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface IGSloppyTouchSlider : UIControl <UIGestureRecognizerDelegate>
{
    _Bool _positiveOnlySlider;
    _Bool _defaultColorOnlySlider;
    _Bool _isSliding;
    double _value;
    UIImageView *_thumbView;
    UIView *_trackView;
    UIView *_highlightedTrackView;
    UIImageView *_centerView;
    CAShapeLayer *_triangluarTrackLayer;
    double _panValueOrigin;
    double _sliderPosition;
    UIPanGestureRecognizer *_panGesture;
    UITapGestureRecognizer *_tapGesture;
    UIButton *_addAccessibilityButton;
    UIButton *_subtractAccessibilityButton;
    struct CGSize _touchTargetInflation;
    struct CGSize _thumbViewShadowOffset;
    struct CGPoint _panOrigin;
}

+ (id)accessibilityNudgeButtonWithLabel:(id)arg1 initialValue:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *addAccessibilityButton; // @synthesize addAccessibilityButton=_addAccessibilityButton;
@property(retain, nonatomic) UIImageView *centerView; // @synthesize centerView=_centerView;
- (void)collapse;
- (void)dealloc;
@property(nonatomic) _Bool defaultColorOnlySlider; // @synthesize defaultColorOnlySlider=_defaultColorOnlySlider;
- (id)defaultTrackColor;
- (void)expand;
- (id)highlightedTrackColor;
@property(retain, nonatomic) UIView *highlightedTrackView; // @synthesize highlightedTrackView=_highlightedTrackView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 useTriangularTrack:(_Bool)arg2;
@property(nonatomic) _Bool isSliding; // @synthesize isSliding=_isSliding;
- (void)layoutSubviews;
- (double)minValue;
- (void)onAccessibilityAdd:(id)arg1;
- (void)onAccessibilitySubtract:(id)arg1;
- (void)onPan:(id)arg1;
- (void)onTap:(id)arg1;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(nonatomic) struct CGPoint panOrigin; // @synthesize panOrigin=_panOrigin;
@property(nonatomic) double panValueOrigin; // @synthesize panValueOrigin=_panValueOrigin;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) _Bool positiveOnlySlider; // @synthesize positiveOnlySlider=_positiveOnlySlider;
- (void)setAccessibilityValue:(id)arg1;
@property(nonatomic) double sliderPosition; // @synthesize sliderPosition=_sliderPosition;
@property(retain, nonatomic) UIButton *subtractAccessibilityButton; // @synthesize subtractAccessibilityButton=_subtractAccessibilityButton;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UIImageView *thumbView; // @synthesize thumbView=_thumbView;
@property(nonatomic) struct CGSize thumbViewShadowOffset; // @synthesize thumbViewShadowOffset=_thumbViewShadowOffset;
@property(nonatomic) struct CGSize touchTargetInflation; // @synthesize touchTargetInflation=_touchTargetInflation;
@property(retain, nonatomic) UIView *trackView; // @synthesize trackView=_trackView;
@property(nonatomic) double value; // @synthesize value=_value;
- (void)setValue:(double)arg1 animated:(_Bool)arg2;
- (double)sliderPositionForValue:(double)arg1;
- (struct CGRect)thumbRectForBounds:(struct CGRect)arg1 trackRect:(struct CGRect)arg2 value:(float)arg3;
- (void)toggleAccessibilityButtonsOnValueChange;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (struct CGRect)trackRectForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) CAShapeLayer *triangluarTrackLayer; // @synthesize triangluarTrackLayer=_triangluarTrackLayer;
- (id)triangularTrackCollapsedPath;
- (id)triangularTrackPath;
- (double)unitDisplacementInPoints;
- (double)valueForSliderPosition:(double)arg1;
- (void)voiceOverStatusChangedNotification:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

