//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface IGSQLiteDatabase : NSObject
{
    _Bool _isInvalid;
    struct sqlite3 *_database;
    unsigned long long _transactionDepth;
    NSString *_userPK;
    long long _version;
    NSString *_configurationDirectory;
    NSDictionary *_tablesForNames;
}

+ (id)databasePathForUserPK:(id)arg1;
+ (_Bool)deleteDatabaseForUserPK:(id)arg1;
- (void).cxx_destruct;
- (_Bool)beginTransaction;
- (_Bool)bindStatement:(struct sqlite3_stmt *)arg1 forIndex:(int)arg2 withBinding:(id)arg3;
- (_Bool)closeDatabase;
- (id)columnValueForStatemente:(struct sqlite3_stmt *)arg1 atIndex:(int)arg2;
@property(readonly, copy, nonatomic) NSString *configurationDirectory; // @synthesize configurationDirectory=_configurationDirectory;
@property(readonly, nonatomic) struct sqlite3 *database; // @synthesize database=_database;
- (id)databasePath;
- (long long)databaseVersion;
- (_Bool)endTransaction;
- (_Bool)executeInsertStatement:(id)arg1 withBindings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)executeStatement:(id)arg1 rowProcessBlock:(CDUnknownBlockType)arg2;
- (_Bool)executeUpdateStatement:(id)arg1 withBindings:(id)arg2;
- (id)initWithUserPK:(id)arg1 version:(long long)arg2 configurationsDirectory:(id)arg3;
- (void)invalidateDatabaseWithErrorMessage:(id)arg1;
@property(nonatomic) _Bool isInvalid; // @synthesize isInvalid=_isInvalid;
- (_Bool)openAndPrepareDatabase;
- (_Bool)prepareTables;
- (struct sqlite3_stmt *)preparedSQLiteStatement:(id)arg1 withBindings:(id)arg2;
- (id)rawRowsFromQueryStatement:(id)arg1;
- (_Bool)setDatabaseVersion:(long long)arg1;
@property(nonatomic) unsigned long long transactionDepth; // @synthesize transactionDepth=_transactionDepth;
- (id)tableForName:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *tablesForNames; // @synthesize tablesForNames=_tablesForNames;
@property(readonly, copy, nonatomic) NSString *userPK; // @synthesize userPK=_userPK;
@property(readonly, nonatomic) long long version; // @synthesize version=_version;

@end

