//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGSQLiteRelationship : NSObject
{
    long long _type;
    NSString *_foreignTableName;
    NSString *_foreignColumnName;
    NSString *_associationTableName;
    NSString *_nativeColumnName;
    NSString *_propertyName;
    NSString *_propertyClassName;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *associationTableName; // @synthesize associationTableName=_associationTableName;
@property(readonly, copy, nonatomic) NSString *foreignColumnName; // @synthesize foreignColumnName=_foreignColumnName;
@property(readonly, copy, nonatomic) NSString *foreignTableName; // @synthesize foreignTableName=_foreignTableName;
- (id)initWithType:(long long)arg1 foreignTableName:(id)arg2 foreignColumnName:(id)arg3 nativeColumnName:(id)arg4 associationTableName:(id)arg5 propertyName:(id)arg6 propertyClassName:(id)arg7;
@property(readonly, copy, nonatomic) NSString *nativeColumnName; // @synthesize nativeColumnName=_nativeColumnName;
@property(readonly, copy, nonatomic) NSString *propertyClassName; // @synthesize propertyClassName=_propertyClassName;
@property(readonly, copy, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;

@end

