//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGStoryWebLinksCreationFormViewDelegate.h"

@class IGStoryComposerWaterfallLoggingContext, IGStoryWebLinksCreationFormView, IGUserSession, NSString, NSURL, UIActivityIndicatorView, UIBarButtonItem;

@interface IGStoryWebLinksCreationViewController : IGViewController <IGStoryWebLinksCreationFormViewDelegate>
{
    id <IGStoryWebLinksCreationViewControllerDelegate> _delegate;
    NSURL *_validatedUrl;
    IGStoryComposerWaterfallLoggingContext *_loggingContext;
    IGStoryWebLinksCreationFormView *_formView;
    UIActivityIndicatorView *_activityIndicator;
    IGUserSession *_userSession;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_cancelButton;
    UIBarButtonItem *_spinnerButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
- (id)analyticsModule;
@property(readonly, nonatomic) UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)clearStoryLink;
- (void)configureNavigationBarAppearance;
@property(nonatomic) __weak id <IGStoryWebLinksCreationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapWebViewCloseButton;
- (void)dismiss;
@property(readonly, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(readonly, nonatomic) IGStoryWebLinksCreationFormView *formView; // @synthesize formView=_formView;
- (id)initWithUserSession:(id)arg1 loggingContext:(id)arg2;
@property(readonly, nonatomic) IGStoryComposerWaterfallLoggingContext *loggingContext; // @synthesize loggingContext=_loggingContext;
- (void)onCancelTapped:(id)arg1;
- (void)onDoneTapped:(id)arg1;
- (_Bool)prefersStatusBarHidden;
@property(copy, nonatomic) NSURL *validatedUrl; // @synthesize validatedUrl=_validatedUrl;
- (void)showErrorWithMessage:(id)arg1;
@property(readonly, nonatomic) UIBarButtonItem *spinnerButton; // @synthesize spinnerButton=_spinnerButton;
- (void)urlTextFieldChanged:(id)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (id)validURLFromString:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)webLinksCreationFormViewDidTapPreviewLinkWithUrl:(id)arg1;
- (id)webViewControllerForURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

