//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGAutocompleteAsyncDataSourceDelegate.h"
#import "IGListAdapterDataSource.h"
#import "IGStoryMentionItemControllerDelegate.h"

@class IGListAdapter, IGListCollectionView, IGSearchAsyncDataSource, IGUserSession, NSString;

@interface IGStoryMentionsViewController : UIViewController <IGListAdapterDataSource, IGAutocompleteAsyncDataSourceDelegate, IGStoryMentionItemControllerDelegate>
{
    id <IGStoryMentionsViewControllerDelegate> _delegate;
    NSString *_queryText;
    IGUserSession *_userSession;
    IGListAdapter *_listAdapter;
    IGListCollectionView *_collectionView;
    IGSearchAsyncDataSource *_usersDataSource;
    NSString *_searchRankToken;
}

+ (id)mentionQueryForFullText:(id)arg1 cursorIndex:(long long)arg2 userSession:(id)arg3;
+ (struct _NSRange)mentionReplacementRangeForFullText:(id)arg1 cursorIndex:(long long)arg2 userSession:(id)arg3;
- (void).cxx_destruct;
- (void)autocompleteDataSourceDidFailLoad:(id)arg1;
- (void)autocompleteDataSourceDidFinishLoading:(id)arg1;
- (void)autocompleteDataSourceDidStartLoading:(id)arg1;
@property(readonly, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <IGStoryMentionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)initWithUserSession:(id)arg1;
@property(readonly, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (void)loadView;
- (id)objectsForListAdapter:(id)arg1;
@property(copy, nonatomic) NSString *queryText; // @synthesize queryText=_queryText;
@property(readonly, nonatomic) NSString *searchRankToken; // @synthesize searchRankToken=_searchRankToken;
- (void)storyMentionItemController:(id)arg1 didSelectUser:(id)arg2;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) IGSearchAsyncDataSource *usersDataSource; // @synthesize usersDataSource=_usersDataSource;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

