//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGAnalyticsUploadWaterfall.h"

@class NSString;

@interface IGStoryAnalyticsUploadWaterfall : NSObject <IGAnalyticsUploadWaterfall>
{
    NSString *_sessionId;
    NSString *_entryPoint;
    double _startTimestamp;
}

- (void).cxx_destruct;
- (id)currentSessionID;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, copy, nonatomic) NSString *entryPoint; // @synthesize entryPoint=_entryPoint;
- (id)initWithCoder:(id)arg1;
- (id)initWithContext:(id)arg1;
- (id)logUploadEvent:(id)arg1;
@property(readonly, copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(readonly, nonatomic) double startTimestamp; // @synthesize startTimestamp=_startTimestamp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

