//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGListAdapterDataSource.h"
#import "IGPresentableStoryViewer.h"
#import "IGSoundStateListenerDelegate.h"
#import "IGStoryDataControllerSponsoredStoryItemListener.h"
#import "IGStoryDataControllerStoryItemListener.h"
#import "IGStoryFullscreenControllerTypeDelegate.h"
#import "UIScrollViewDelegate.h"

@class IGListAdapter, IGListAdapterUpdaterLogger, IGListCollectionView, IGSoundStateListener, IGStoryDataController, IGStoryMediaPreloadController, IGStorySeenState, IGStoryViewerConfiguration, IGStoryViewerLoggingContext, IGStoryViewerViewModel, IGUserSession, NSArray, NSNumber, NSString, UIScrollView, UIView;

@interface IGStoryViewerViewController : IGViewController <IGListAdapterDataSource, IGStoryFullscreenControllerTypeDelegate, IGStoryDataControllerSponsoredStoryItemListener, IGStoryDataControllerStoryItemListener, IGSoundStateListenerDelegate, UIScrollViewDelegate, IGPresentableStoryViewer>
{
    _Bool _isDismissing;
    _Bool _isTransitioningBetweenStories;
    _Bool _sponsoredStoriesEnabled;
    id <IGStoryViewerDelegate> _delegate;
    IGStoryDataController *_dataController;
    IGStoryViewerLoggingContext *_loggingContext;
    long long _entryPoint;
    IGStoryViewerConfiguration *_configuration;
    UIScrollView *_dismissScrollView;
    NSNumber *_navigationActionOverride;
    UIView *_backgroundView;
    IGListCollectionView *_collectionView;
    IGListAdapter *_listAdapter;
    IGListAdapterUpdaterLogger *_listAdapterUpdaterLogger;
    IGStoryViewerViewModel *_focusedModelItem;
    NSArray *_modelItems;
    IGSoundStateListener *_soundStateListener;
    IGUserSession *_userSession;
    IGStorySeenState *_pendingSeenState;
    IGStoryMediaPreloadController *_mediaPreloadController;
    long long _entryIndex;
    struct CGPoint _dismissScrollOffset;
    struct CGPoint _dismissCollectionViewOffset;
}

- (void).cxx_destruct;
- (id)analyticsModule;
- (void)appEnteredBackground:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) UIView *backgroundViewForAnimation;
@property(retain, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (struct CGRect)collectionViewFrame;
@property(readonly, nonatomic) IGStoryViewerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) UIView *contentViewForAnimation;
@property(readonly, nonatomic) UIView *contentViewForSnapshot;
@property(readonly, nonatomic) IGStoryDataController *dataController; // @synthesize dataController=_dataController;
- (void)dealloc;
@property(nonatomic) __weak id <IGStoryViewerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGPoint dismissCollectionViewOffset; // @synthesize dismissCollectionViewOffset=_dismissCollectionViewOffset;
@property(nonatomic) struct CGPoint dismissScrollOffset; // @synthesize dismissScrollOffset=_dismissScrollOffset;
@property(retain, nonatomic) UIScrollView *dismissScrollView; // @synthesize dismissScrollView=_dismissScrollView;
- (void)dismissWithNavigationAction:(long long)arg1;
- (id)emptyViewForListAdapter:(id)arg1;
@property(readonly, nonatomic) long long entryIndex; // @synthesize entryIndex=_entryIndex;
@property(readonly, nonatomic) long long entryPoint; // @synthesize entryPoint=_entryPoint;
- (void)fetchItemsForFocusedPreviousAndNextViewModels;
- (void)flushPendingSeenStateToServer;
- (id)focusedCell;
- (id)focusedController;
@property(retain, nonatomic) IGStoryViewerViewModel *focusedModelItem; // @synthesize focusedModelItem=_focusedModelItem;
- (void)fullscreenSectionController:(id)arg1 didAdvancePastLastItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id)arg1 didChangeItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id)arg1 didMarkItemAsSeen:(id)arg2;
- (void)fullscreenSectionController:(id)arg1 didMarkStoryViewModelAsHidden:(id)arg2;
- (void)fullscreenSectionController:(id)arg1 didRewindPastFirstItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id)arg1 willUpdateFromStoryModel:(id)arg2 toStoryModel:(id)arg3 storyItem:(id)arg4;
- (_Bool)fullscreenSectionControllerCanResumePlayback:(id)arg1;
- (void)fullscreenSectionControllerDidDisplayWebView:(id)arg1;
- (void)fullscreenSectionControllerDidEndDisplayingWebView:(id)arg1;
- (void)fullscreenSectionControllerDidEndTransition;
- (void)fullscreenSectionControllerDidStartTransition;
- (void)fullscreenSectionControllerDidTapDismiss:(id)arg1;
- (id)getMostVisibleItem;
- (id)initWithUserSession:(id)arg1 viewModels:(id)arg2 currentViewModel:(id)arg3 dataController:(id)arg4 loggingContext:(id)arg5 entryPoint:(long long)arg6 delegate:(id)arg7 configuration:(id)arg8;
@property(nonatomic) _Bool isDismissing; // @synthesize isDismissing=_isDismissing;
@property(nonatomic) _Bool isTransitioningBetweenStories; // @synthesize isTransitioningBetweenStories=_isTransitioningBetweenStories;
@property(retain, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
@property(readonly, nonatomic) IGListAdapterUpdaterLogger *listAdapterUpdaterLogger; // @synthesize listAdapterUpdaterLogger=_listAdapterUpdaterLogger;
- (void)loadView;
@property(readonly, nonatomic) IGStoryViewerLoggingContext *loggingContext; // @synthesize loggingContext=_loggingContext;
- (void)markSkippedForViewModel:(id)arg1;
@property(readonly, nonatomic) IGStoryMediaPreloadController *mediaPreloadController; // @synthesize mediaPreloadController=_mediaPreloadController;
@property(retain, nonatomic) NSArray *modelItems; // @synthesize modelItems=_modelItems;
@property(retain, nonatomic) NSNumber *navigationActionOverride; // @synthesize navigationActionOverride=_navigationActionOverride;
- (id)objectsForListAdapter:(id)arg1;
@property(retain, nonatomic) IGStorySeenState *pendingSeenState; // @synthesize pendingSeenState=_pendingSeenState;
- (_Bool)prefersNavigationBarHidden;
- (_Bool)prefersStatusBarHidden;
- (_Bool)prefersTabBarHidden;
- (void)preloadMedia;
- (void)proceedToNextChannelWithNavigationAction:(long long)arg1;
@property(readonly, nonatomic) UIView *profileImageViewForAnimation;
- (void)rewindToPreviousChannelWithNavigationAction:(long long)arg1;
- (void)scrollToInitialItem;
- (void)scrollToItem:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)soundListenerDidUpdate:(id)arg1;
@property(readonly, nonatomic) IGSoundStateListener *soundStateListener; // @synthesize soundStateListener=_soundStateListener;
@property(readonly, nonatomic) _Bool sponsoredStoriesEnabled; // @synthesize sponsoredStoriesEnabled=_sponsoredStoriesEnabled;
- (void)storyDataController:(id)arg1 didReturnNoStoryItemResultsForReelPK:(id)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
- (void)storyDataController:(id)arg1 didUpdateReel:(id)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
- (void)storyDataController:(id)arg1 didUpdateSponsoredReel:(id)arg2;
- (void)storyDataController:(id)arg1 fetchStoryItemsDidFailWithError:(id)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
- (id)trayUserIds;
- (void)updateBackgroundForDragDistance:(double)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
@property(readonly, copy, nonatomic) NSString *viewModelIdentifier;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

