//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGCircularButton, IGStoryGradientRingView, UILabel;

@interface IGStoryDiscoveryCell : UICollectionViewCell
{
    id <IGStoryDiscoveryCellDelegate> _delegate;
    IGStoryGradientRingView *_gradientRingView;
    IGCircularButton *_actionButton;
    UILabel *_titleLabel;
}

+ (struct CGSize)preferredCellSize;
- (void).cxx_destruct;
@property(readonly, nonatomic) IGCircularButton *actionButton; // @synthesize actionButton=_actionButton;
- (void)configureCell:(long long)arg1;
@property(nonatomic) __weak id <IGStoryDiscoveryCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGStoryGradientRingView *gradientRingView; // @synthesize gradientRingView=_gradientRingView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)storyDiscoveryCell:(id)arg1 didActionButton:(id)arg2;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

