//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGStoryPreviewFooterViewType.h"

@class IGTapButton, NSString;

@interface IGStoryPreviewDefaultFooterView : UIView <IGStoryPreviewFooterViewType>
{
    id <IGStoryPreviewDefaultFooterViewDelegate> _delegate;
    IGTapButton *_cancelButton;
    IGTapButton *_storyButton;
    IGTapButton *_downloadButton;
}

+ (id)downloadButtonWithTarget:(id)arg1 action:(SEL)arg2;
+ (id)storyButtonWithTarget:(id)arg1 action:(SEL)arg2;
- (void).cxx_destruct;
- (id)buttonAtCenter;
@property(readonly, nonatomic) IGTapButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (id)currentCancelButton;
- (id)currentStoryButton;
@property(nonatomic) __weak id <IGStoryPreviewDefaultFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapCancelButton:(id)arg1;
- (void)didTapDownloadButton:(id)arg1;
- (void)didTapStoryButton:(id)arg1;
@property(readonly, nonatomic) IGTapButton *downloadButton; // @synthesize downloadButton=_downloadButton;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setUpCancelButton;
- (void)setUpDownloadButton;
- (void)setUpStoryButton;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) IGTapButton *storyButton; // @synthesize storyButton=_storyButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

