//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGQuickCamAssetProcessorGenerationDelegate.h"
#import "IGStoryBoomerangManagerDelegate.h"

@class IGPerformanceEvent, IGQuickCamAssetProcessor, IGStoryBoomerangManager, IGUserSession, NSString;

@interface IGStoryAssetManager : NSObject <IGQuickCamAssetProcessorGenerationDelegate, IGStoryBoomerangManagerDelegate>
{
    _Bool _isUpdatingAsset;
    id <IGStoryAssetManagerDelegate> _delegate;
    id <IGQuickCamOutputAsset> _outputAsset;
    long long _mode;
    IGUserSession *_userSession;
    id <IGQuickCamInputAsset> _inputAsset;
    id <IGQuickCamOutputAsset> _originalOutputAsset;
    IGStoryBoomerangManager *_boomerangManager;
    IGQuickCamAssetProcessor *_assetProcessor;
    IGPerformanceEvent *_performanceEvent;
    struct CGSize _constrainingSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGQuickCamAssetProcessor *assetProcessor; // @synthesize assetProcessor=_assetProcessor;
@property(readonly, nonatomic) IGStoryBoomerangManager *boomerangManager; // @synthesize boomerangManager=_boomerangManager;
- (_Bool)canUpdateOutputAssetWithMode:(long long)arg1;
@property(nonatomic) struct CGSize constrainingSize; // @synthesize constrainingSize=_constrainingSize;
- (id)coverPhoto;
@property(nonatomic) __weak id <IGStoryAssetManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finalizeAssetWithDrawingImage:(id)arg1 overlayContainerView:(id)arg2;
- (void)finalizeVideoOutputAsset:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)finishWithOutputAsset:(id)arg1;
- (void)generateBoomerangForLivePhoto:(id)arg1;
@property(readonly, nonatomic) _Bool hasPhotoAsset;
- (id)initTextPostWithConstrainingSize:(struct CGSize)arg1 color:(id)arg2 userSession:(id)arg3;
- (id)initWithBoomerangManager:(id)arg1;
- (id)initWithInputAsset:(id)arg1 boomerangManager:(id)arg2 constrainingSize:(struct CGSize)arg3 performanceEvent:(id)arg4 userSession:(id)arg5;
@property(retain, nonatomic) id <IGQuickCamInputAsset> inputAsset; // @synthesize inputAsset=_inputAsset;
- (_Bool)isBoomerangMode;
@property(readonly, nonatomic) _Bool isUpdatingAsset; // @synthesize isUpdatingAsset=_isUpdatingAsset;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (void)notifyDidBeginUpdatingAsset;
- (void)notifyDidFinishUpdatingAssetWithSuccess:(_Bool)arg1;
@property(retain, nonatomic) id <IGQuickCamOutputAsset> originalOutputAsset; // @synthesize originalOutputAsset=_originalOutputAsset;
@property(retain, nonatomic) id <IGQuickCamOutputAsset> outputAsset; // @synthesize outputAsset=_outputAsset;
- (_Bool)outputAssetHasLivePhoto;
@property(retain, nonatomic) IGPerformanceEvent *performanceEvent; // @synthesize performanceEvent=_performanceEvent;
- (void)quickCamAssetProcessor:(id)arg1 didGeneratePhotoAsset:(id)arg2;
- (void)quickCamAssetProcessor:(id)arg1 didGenerateVideoAsset:(id)arg2;
- (void)quickCamAssetProcessor:(id)arg1 didUpdateProgress:(double)arg2;
- (void)quickCamAssetProcessorDidDetectIncompatible:(id)arg1;
- (void)quickCamAssetProcessorDidFailProcessing:(id)arg1;
- (void)storyBoomerangManager:(id)arg1 didGenerateAsset:(id)arg2;
- (void)storyBoomerangManagerDidFailToGenerateAsset:(id)arg1;
- (void)storyBoomerangManagerDidStartGeneratingNewAsset:(id)arg1;
- (void)updateOutputAssetWithMode:(long long)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

