//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGTooltipViewDelegate.h"

@class IGTooltipView, NSString;

@interface IGStoryAddToStoryNuxView : UIView <IGTooltipViewDelegate>
{
    IGTooltipView *_nuxView;
}

- (void).cxx_destruct;
- (void)didTapTooltipView:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 leftBarButtonView:(id)arg2;
@property(retain, nonatomic) IGTooltipView *nuxView; // @synthesize nuxView=_nuxView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

