//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGStoryViewerViewModel;

@protocol IGStoryFullscreenControllerTypeDelegate <NSObject>
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 didAdvancePastLastItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 didChangeItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 didMarkItemAsSeen:(id <IGStoryItemType>)arg2;
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 didMarkStoryViewModelAsHidden:(IGStoryViewerViewModel *)arg2;
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 didRewindPastFirstItemWithNavigationAction:(long long)arg2;
- (void)fullscreenSectionController:(id <IGStoryFullscreenControllerType>)arg1 willUpdateFromStoryModel:(IGStoryViewerViewModel *)arg2 toStoryModel:(IGStoryViewerViewModel *)arg3 storyItem:(id <IGStoryItemType>)arg4;
- (_Bool)fullscreenSectionControllerCanResumePlayback:(id <IGStoryFullscreenControllerType>)arg1;
- (void)fullscreenSectionControllerDidDisplayWebView:(id <IGStoryFullscreenControllerType>)arg1;
- (void)fullscreenSectionControllerDidEndDisplayingWebView:(id <IGStoryFullscreenControllerType>)arg1;
- (void)fullscreenSectionControllerDidTapDismiss:(id <IGStoryFullscreenControllerType>)arg1;
@end

