//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStaticStickerSingleModel.h"

@class NSString, UIColor;

@interface IGStaticStickerTextModel : IGStaticStickerSingleModel
{
    NSString *_text;
    double _fontSize;
    UIColor *_textColor;
    UIColor *_textBackgroundColor;
}

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) UIColor *textBackgroundColor; // @synthesize textBackgroundColor=_textBackgroundColor;
@property(readonly, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;

@end

