//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGImageProgressViewDelegate.h"
#import "IGStoryPlayerMediaViewType.h"

@class CADisplayLink, IGImageProgressView, NSString, NSTimer;

@interface IGStoryPhotoView : UIView <IGImageProgressViewDelegate, IGStoryPlayerMediaViewType>
{
    _Bool _paused;
    id <IGStoryItemType> _item;
    IGImageProgressView *_photoView;
    NSTimer *_timer;
    CADisplayLink *_displayLink;
    double _timerStartTime;
    double _durationBeforePhotoPause;
    id <IGStoryPlayerMediaViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)advanceTimerFired:(id)arg1;
- (void)cancelTimer;
- (void)configureWithItem:(id)arg1 delegate:(id)arg2 loggingContext:(id)arg3 config:(id)arg4;
@property(readonly, nonatomic) __weak id <IGStoryPlayerMediaViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) double durationBeforePhotoPause; // @synthesize durationBeforePhotoPause=_durationBeforePhotoPause;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isViewFinishedLoading;
@property(readonly, nonatomic) id <IGStoryItemType> item; // @synthesize item=_item;
- (void)layoutSubviews;
- (double)mediaCurrentTime;
- (struct CGSize)mediaSize;
- (void)onDisplayLinkDidFire:(id)arg1;
- (void)pauseWithReason:(long long)arg1;
@property(nonatomic) _Bool paused; // @synthesize paused=_paused;
@property(readonly, nonatomic) IGImageProgressView *photoView; // @synthesize photoView=_photoView;
- (void)play;
- (void)prepareForReuse;
- (void)progressImageView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)progressImageView:(id)arg1 didLoadImage:(id)arg2;
- (void)seekToBeginning;
- (void)setAudioEnabled:(_Bool)arg1;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) double timerStartTime; // @synthesize timerStartTime=_timerStartTime;
- (void)startTimer;
- (void)stopWithReason:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

