//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGFeedScrollViewListener.h"
#import "IGFeedStatusViewDelegate.h"
#import "IGListAdapterDataSource.h"
#import "IGNavSearchBarDelegate.h"
#import "IGUserListNetworkDataSourceDelegate.h"
#import "IGUserListSectionControllerSelectionDelegate.h"

@class IGFeedScrollViewAnnouncer, IGFeedStatusView, IGLabelItemConfiguration, IGListAdapter, IGListCollectionView, IGNavSearchBar, IGNavSearchBarItemConfiguration, IGUserListNetworkDataSource, IGUserSession, NSMutableArray, NSMutableSet, NSSet, NSString, UIBarButtonItem;

@interface IGStorySettingsBlockedUserListViewController : IGViewController <IGFeedStatusViewDelegate, IGListAdapterDataSource, IGNavSearchBarDelegate, IGUserListNetworkDataSourceDelegate, IGFeedScrollViewListener, IGUserListSectionControllerSelectionDelegate>
{
    _Bool _loading;
    id <IGStorySettingsBlockedUserListViewControllerDelegate> _delegate;
    IGListCollectionView *_collectionView;
    IGListAdapter *_listAdapter;
    IGFeedScrollViewAnnouncer *_scrollViewAnnouncer;
    NSMutableArray *_userList;
    IGFeedStatusView *_emptyStateView;
    IGUserSession *_userSession;
    NSString *_sessionId;
    IGNavSearchBar *_searchBar;
    IGNavSearchBarItemConfiguration *_searchBarItemConfig;
    NSString *_searchString;
    IGUserListNetworkDataSource *_networkDataSource;
    NSMutableSet *_selectedUsers;
    NSSet *_blockedUsers;
    long long _entryPoint;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_loadingButton;
    IGLabelItemConfiguration *_headerInfoDisplayLabelItemConfig;
}

- (void).cxx_destruct;
- (id)analyticsModule;
- (void)authorizeAndFetchUsers;
@property(readonly, nonatomic) NSSet *blockedUsers; // @synthesize blockedUsers=_blockedUsers;
@property(retain, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)dataSourceDidFailLoad:(id)arg1;
- (void)dataSourceDidFinishLoading:(id)arg1;
- (void)dataSourceDidStartLoading:(id)arg1;
@property(nonatomic) __weak id <IGStorySettingsBlockedUserListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) IGFeedStatusView *emptyStateView; // @synthesize emptyStateView=_emptyStateView;
- (id)emptyViewForListAdapter:(id)arg1;
@property(nonatomic) long long entryPoint; // @synthesize entryPoint=_entryPoint;
- (void)feedStatusViewDidTapOnInfoView:(id)arg1;
@property(retain, nonatomic) IGLabelItemConfiguration *headerInfoDisplayLabelItemConfig; // @synthesize headerInfoDisplayLabelItemConfig=_headerInfoDisplayLabelItemConfig;
- (id)initWithUserSession:(id)arg1 blockedUsers:(id)arg2 entryPoint:(long long)arg3;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(retain, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (void)loadMoreUsers;
@property(retain, nonatomic) UIBarButtonItem *loadingButton; // @synthesize loadingButton=_loadingButton;
@property(retain, nonatomic) IGUserListNetworkDataSource *networkDataSource; // @synthesize networkDataSource=_networkDataSource;
- (id)objectsForListAdapter:(id)arg1;
- (void)onBackButtonTap;
- (void)onDoneButtonTap;
- (void)reloadData;
@property(retain, nonatomic) IGFeedScrollViewAnnouncer *scrollViewAnnouncer; // @synthesize scrollViewAnnouncer=_scrollViewAnnouncer;
- (void)scrollViewDidEndDragging:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillScrollNearBottom:(id)arg1;
- (void)scrollViewWillScrollNearTop:(id)arg1;
@property(retain, nonatomic) IGNavSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
@property(retain, nonatomic) IGNavSearchBarItemConfiguration *searchBarItemConfig; // @synthesize searchBarItemConfig=_searchBarItemConfig;
- (void)searchBarWillBeginEditing:(id)arg1;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(readonly, nonatomic) NSMutableSet *selectedUsers; // @synthesize selectedUsers=_selectedUsers;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) NSMutableArray *userList; // @synthesize userList=_userList;
@property(retain, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)userListSectionControllerDidDeselectUser:(id)arg1;
- (void)userListSectionControllerDidSelectUser:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

