//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDiskCache, IGStreamingVideoCacheRequest, IGStreamingVideoMetaDataCacheEntry, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface IGStreamingVideoTask : NSObject
{
    IGStreamingVideoCacheRequest *_originalRequest;
    IGDiskCache *_diskCache;
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _completionBlock;
    NSMutableSet *_parkingRequests;
    _Bool _canceled;
    unsigned long long _bytesDownloaded;
    IGStreamingVideoMetaDataCacheEntry *_metaDataEntry;
    id <IGRequestToken> _requestToken;
}

- (void).cxx_destruct;
- (void)attachRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *cacheKey;
- (void)cancel:(id)arg1;
- (void)dispatchMediaInfoCallback:(id)arg1;
- (void)dispatchProgressCallback:(const char *)arg1 length:(unsigned long long)arg2 contentLength:(long long)arg3;
- (id)initWithRequest:(id)arg1 diskCache:(id)arg2 queue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)interrupt;
- (struct _NSRange)loadBytesFromDiskCache:(struct _NSRange)arg1 bytesHandler:(CDUnknownBlockType)arg2;
- (struct _NSRange)loadFromDiskCacheAndMaybeAttachRequest:(id)arg1;
- (id)loadMetaDataFromDiskCache;
- (void)loadVideo;
- (void)loadVideoFromNetworkAndFinishTask:(struct _NSRange)arg1;
- (void)maybeDispatchErrorCallback:(id)arg1;
@property(readonly, nonatomic) IGStreamingVideoCacheRequest *originalRequest; // @synthesize originalRequest=_originalRequest;
- (void)queue_attachRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)queue_cancel:(id)arg1;
- (void)queue_interrupt;
- (void)queue_loadVideo;

@end

