//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGStoryCameraModeSwitcherViewDelegate.h"

@class IGQuickCamCaptureButton, IGStoryCameraModeSwitcherView, IGTapButton, NSString, UIButton, UILabel;

@interface IGStoryCameraFooterView : UIView <IGStoryCameraModeSwitcherViewDelegate>
{
    _Bool _supportsLowLight;
    _Bool _supportsFlash;
    IGQuickCamCaptureButton *_captureButton;
    IGTapButton *_flashButton;
    IGTapButton *_lowLightButton;
    IGTapButton *_switchCameraButton;
    UILabel *_swipeForTextLabel;
    UIButton *_liveVideoButton;
    IGStoryCameraModeSwitcherView *_cameraModeSwitcherView;
    id <IGStoryCameraFooterViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)animateButtons:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateFromLiveButton;
- (void)animateToLiveButton;
@property(readonly, nonatomic) IGStoryCameraModeSwitcherView *cameraModeSwitcherView; // @synthesize cameraModeSwitcherView=_cameraModeSwitcherView;
- (void)cameraModeSwitcherView:(id)arg1 didSwitchToMode:(long long)arg2;
@property(readonly, nonatomic) IGQuickCamCaptureButton *captureButton; // @synthesize captureButton=_captureButton;
- (void)configureAndPositionLeftButtonsAnimated:(_Bool)arg1 supportsLowLight:(_Bool)arg2 supportsFlash:(_Bool)arg3;
- (long long)currentMode;
@property(nonatomic) __weak id <IGStoryCameraFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGTapButton *flashButton; // @synthesize flashButton=_flashButton;
- (void)flashButtonTapped;
- (void)flipSwitchCamerasButton;
- (id)initWithSwitchCamerasVisible:(_Bool)arg1 isDirectStory:(_Bool)arg2 availableModes:(id)arg3 initialMode:(long long)arg4 captureButtonDelegate:(id)arg5;
- (void)layoutSubviews;
- (void)liveButtonTapped;
@property(readonly, nonatomic) UIButton *liveVideoButton; // @synthesize liveVideoButton=_liveVideoButton;
@property(readonly, nonatomic) IGTapButton *lowLightButton; // @synthesize lowLightButton=_lowLightButton;
- (void)lowLightButtonTapped;
- (void)onSwitchCamerasButtonTapped;
- (void)positionsSwitchCameraButton;
@property(nonatomic) _Bool supportsFlash; // @synthesize supportsFlash=_supportsFlash;
@property(nonatomic) _Bool supportsLowLight; // @synthesize supportsLowLight=_supportsLowLight;
- (void)showCameraModeSwitcher:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)snapshotWithoutCaptureButton;
@property(readonly, nonatomic) UILabel *swipeForTextLabel; // @synthesize swipeForTextLabel=_swipeForTextLabel;
@property(readonly, nonatomic) IGTapButton *switchCameraButton; // @synthesize switchCameraButton=_switchCameraButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

