//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStoredObject.h"
#import "NSCoding.h"

@class NSString;

@interface IGStorableObject : NSObject <NSCoding, IGStoredObject>
{
    _Bool _isStored;
    _Bool _isUnmanaged;
    NSString *_pk;
    unsigned long long _version;
}

+ (id)centralizedStore;
+ (id)pkFromDict:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initUnmanaged;
- (id)initUnmanagedWithDictionary:(id)arg1;
- (id)initUnmanagedWithPk:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPk:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) _Bool isStored; // @synthesize isStored=_isStored;
@property(readonly, nonatomic) _Bool isUnmanaged; // @synthesize isUnmanaged=_isUnmanaged;
@property(copy, nonatomic) NSString *pk; // @synthesize pk=_pk;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
- (_Bool)updateWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

