//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSString;

@interface IGSuggestPostsLogger : NSObject
{
    NSString *_sessionId;
    NSString *_module;
    long long _position;
    NSMutableSet *_loggedImpressions;
}

- (void).cxx_destruct;
- (void)addBasicLoggingForEvent:(id)arg1;
- (void)addLoggingForEvent:(id)arg1 feedItem:(id)arg2 atIndex:(long long)arg3;
- (id)initWithSessionId:(id)arg1 module:(id)arg2 position:(long long)arg3;
- (void)logClickForCTA;
- (void)logClickForFeedItem:(id)arg1 atIndex:(long long)arg2;
- (void)logImpression;
- (void)logImpressionForFeedItem:(id)arg1 atIndex:(long long)arg2;
@property(readonly, copy, nonatomic) NSMutableSet *loggedImpressions; // @synthesize loggedImpressions=_loggedImpressions;
@property(readonly, copy, nonatomic) NSString *module; // @synthesize module=_module;
@property(readonly, nonatomic) long long position; // @synthesize position=_position;
@property(readonly, copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;

@end

