//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFindUsersViewController.h"

#import "IGRaindropAnalyticsDelegate.h"

@class NSString;

@interface IGSuggestedFriendsViewController : IGFindUsersViewController <IGRaindropAnalyticsDelegate>
{
}

- (id)analyticsModule;
- (void)authorizeAndFetchUsers;
- (_Bool)enableNavState;
- (void)followButton:(id)arg1 logfollowButtonTapWithAction:(long long)arg2 targetID:(id)arg3;
- (id)initWithUserSession:(id)arg1;
- (id)newFindUsersView;
- (id)newFindUsersViewDataSource;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

