//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGSurveryPrimerViewDelegate.h"
#import "IGSurveyQuestionViewDelegate.h"

@class IGSurveyPrimerView, IGSurveyQuestion, IGSurveyQuestionView, IGSurveyResultView, NSString;

@interface IGSurveyViewController : IGViewController <IGSurveryPrimerViewDelegate, IGSurveyQuestionViewDelegate>
{
    _Bool _showingPrimerView;
    IGSurveyQuestion *_question;
    IGSurveyPrimerView *_primerView;
    IGSurveyQuestionView *_questionView;
    IGSurveyResultView *_resultView;
}

+ (double)popoverWidth;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)dealloc;
- (void)dismiss;
- (id)initWithQuestion:(id)arg1;
- (void)notifySurveyPrimerViewDidDismissWithResponse:(_Bool)arg1;
@property(retain, nonatomic) IGSurveyPrimerView *primerView; // @synthesize primerView=_primerView;
- (void)primerViewDidTapNextInView:(id)arg1;
@property(retain, nonatomic) IGSurveyQuestion *question; // @synthesize question=_question;
@property(retain, nonatomic) IGSurveyQuestionView *questionView; // @synthesize questionView=_questionView;
- (void)questionView:(id)arg1 didSelectAnswer:(id)arg2;
@property(retain, nonatomic) IGSurveyResultView *resultView; // @synthesize resultView=_resultView;
@property(nonatomic) _Bool showingPrimerView; // @synthesize showingPrimerView=_showingPrimerView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

