//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGDimmedOverlayViewControllerDelegate.h"
#import "IGInlineGalleryPresenter.h"
#import "IGNavigationControllerDelegate.h"
#import "IGSwitchUsersControllerDelegate.h"
#import "IGTooltipViewDelegate.h"
#import "IGViewControllerInitializationDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISplitViewControllerDelegate.h"

@class IGDimmedOverlayViewController, IGExploreMainFeedViewController, IGInlineGalleryViewController, IGNavigationController, IGNewsViewController, IGSwitchUsersController, IGTabBar, IGTabBarButton, IGTabBarControllerPerformanceMonitor, IGToastData, IGTooltipView, IGUserDetailViewController, IGUserSession, NSArray, NSString, UISplitViewController, UIView, UIWindow;

@interface IGTabBarController : UIViewController <IGDimmedOverlayViewControllerDelegate, IGInlineGalleryPresenter, IGNavigationControllerDelegate, IGSwitchUsersControllerDelegate, IGTooltipViewDelegate, IGViewControllerInitializationDelegate, UIGestureRecognizerDelegate, UISplitViewControllerDelegate>
{
    IGTabBar *_tabBar;
    IGTabBarButton *_homeButton;
    IGTabBarButton *_popularButton;
    IGTabBarButton *_cameraButton;
    IGTabBarButton *_newsButton;
    IGTabBarButton *_profileButton;
    _Bool _mainFeedCreationEnabled;
    _Bool _manualRefreshNecessary;
    _Bool _isPerformingTabBarAction;
    _Bool _isDisplayingSwitchUsersTableView;
    _Bool _usesNewCreationFlow;
    long long _selectedTabBarItem;
    NSArray *_viewControllers;
    IGUserSession *_userSession;
    IGTooltipView *_activityToastView;
    long long _cameraButtonMode;
    IGToastData *_suppressedToastData;
    long long _pendingRequestCount;
    IGSwitchUsersController *_switchUsersController;
    UIWindow *_dimmedOverlayWindow;
    IGDimmedOverlayViewController *_dimmedOverlayViewController;
    IGInlineGalleryViewController *_inlineGalleryController;
    IGNavigationController *_profileNav;
    UISplitViewController *_splitViewController;
    IGNavigationController *_detailNavigationController;
    UIViewController *_placeHolderViewController;
    UIViewController *_defaultDetailController;
    IGTabBarControllerPerformanceMonitor *_performanceMonitor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGTooltipView *activityToastView; // @synthesize activityToastView=_activityToastView;
- (void)addSplitViewControllerwithMasterController:(id)arg1 detailController:(id)arg2;
- (void)animateSwitchUsersTableView;
- (void)autoPromptInlineGallery:(id)arg1;
- (void)badgeInfoDidupdate:(id)arg1;
- (id)buttonForItem:(long long)arg1;
- (void)cameraButtonLongPressed:(id)arg1;
@property(nonatomic) long long cameraButtonMode; // @synthesize cameraButtonMode=_cameraButtonMode;
- (void)cameraButtonPressed;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;
- (void)clearDetailNavigationController;
- (void)dealloc;
@property(retain, nonatomic) UIViewController *defaultDetailController; // @synthesize defaultDetailController=_defaultDetailController;
@property(retain, nonatomic) IGNavigationController *detailNavigationController; // @synthesize detailNavigationController=_detailNavigationController;
- (void)didReceiveCopyrightViolation:(id)arg1;
- (void)didTapTooltipView:(id)arg1;
@property(retain, nonatomic) IGDimmedOverlayViewController *dimmedOverlayViewController; // @synthesize dimmedOverlayViewController=_dimmedOverlayViewController;
- (void)dimmedOverlayViewControllerDidTapDimmedOverlay:(id)arg1;
@property(retain, nonatomic) UIWindow *dimmedOverlayWindow; // @synthesize dimmedOverlayWindow=_dimmedOverlayWindow;
- (void)displayActivityToastWithToastData:(id)arg1;
- (void)displaySuppressedActivityToastWhenApporiate;
@property(readonly, nonatomic) IGExploreMainFeedViewController *exploreViewController;
- (void)focusNewsViewController:(id)arg1;
- (void)grayOverlayViewTapped;
- (void)hideActivityToastAnimated:(_Bool)arg1;
- (void)hideActivityToastWithAnimation;
- (void)homeButtonPressed;
- (void)impressionDebugging:(id)arg1;
- (void)inboxCountDidUpdate:(id)arg1;
- (id)initWithUserSession:(id)arg1 mainFeedCreationEnabled:(_Bool)arg2 manualRefreshNecessary:(_Bool)arg3;
- (void)initializeInlineGalleryVCIfNeeded;
- (void)initializeReactNativeAutoupdaterService;
- (void)initializeViewControllersWithMainFeedNetworkSource:(id)arg1;
- (void)inlineGallery:(id)arg1 didUpdateToState:(long long)arg2;
@property(retain, nonatomic) IGInlineGalleryViewController *inlineGalleryController; // @synthesize inlineGalleryController=_inlineGalleryController;
@property(nonatomic) _Bool isDisplayingSwitchUsersTableView; // @synthesize isDisplayingSwitchUsersTableView=_isDisplayingSwitchUsersTableView;
@property(nonatomic) _Bool isPerformingTabBarAction; // @synthesize isPerformingTabBarAction=_isPerformingTabBarAction;
@property(readonly, nonatomic) _Bool isTabBarVisible;
- (_Bool)itemNeedsAttention:(long long)arg1;
- (void)layoutToast;
- (void)logNavigationEventForClickPoint:(id)arg1;
@property(readonly, nonatomic) _Bool mainFeedCreationEnabled; // @synthesize mainFeedCreationEnabled=_mainFeedCreationEnabled;
@property(readonly, nonatomic) _Bool manualRefreshNecessary; // @synthesize manualRefreshNecessary=_manualRefreshNecessary;
- (void)moveDownTabBarToOffset:(double)arg1;
- (void)navigateToSearchController;
- (void)navigationController:(id)arg1 didNavigateToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 didPopViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willNavigateToViewController:(id)arg2;
- (id)navigationControllerForTabBarItem:(long long)arg1;
- (void)newPromotionCreated;
- (void)newsButtonPressed;
@property(readonly, nonatomic) IGNavigationController *newsNavigationController;
@property(readonly, nonatomic) IGNewsViewController *newsViewController;
- (void)openURLInNewsTab:(id)arg1;
@property(nonatomic) long long pendingRequestCount; // @synthesize pendingRequestCount=_pendingRequestCount;
@property(retain, nonatomic) IGTabBarControllerPerformanceMonitor *performanceMonitor; // @synthesize performanceMonitor=_performanceMonitor;
@property(retain, nonatomic) UIViewController *placeHolderViewController; // @synthesize placeHolderViewController=_placeHolderViewController;
- (void)popularButtonLongPressed:(id)arg1;
- (void)popularButtonPressed;
- (void)prefetchAndFocusInboxInNewsTab;
- (void)prefetchProfile;
- (void)preheatDrafts;
- (_Bool)presentInlineGalleryWithStyle:(long long)arg1 animated:(_Bool)arg2;
- (void)profileButtonLongPressed:(id)arg1;
- (void)profileButtonPressed;
@property(retain, nonatomic) IGNavigationController *profileNav; // @synthesize profileNav=_profileNav;
@property(readonly, nonatomic) IGUserDetailViewController *profileViewController;
- (void)pushDetailContentController:(id)arg1 animated:(_Bool)arg2;
- (double)referenceYPositionForInlineGallery:(id)arg1;
- (void)removeInlineGalleryAsChildViewController;
- (void)removeSplitViewController;
@property(readonly, nonatomic) long long selectedTabBarItem; // @synthesize selectedTabBarItem=_selectedTabBarItem;
@property(readonly, nonatomic) UIViewController *selectedViewController;
- (void)setNeedsAttention:(_Bool)arg1 forItem:(long long)arg2;
- (void)setSelectedTabBarItem:(long long)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UISplitViewController *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(retain, nonatomic) IGToastData *suppressedToastData; // @synthesize suppressedToastData=_suppressedToastData;
@property(retain, nonatomic) IGSwitchUsersController *switchUsersController; // @synthesize switchUsersController=_switchUsersController;
@property(nonatomic) _Bool usesNewCreationFlow; // @synthesize usesNewCreationFlow=_usesNewCreationFlow;
- (void)settingsCountDidUpdate:(id)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
@property(readonly, nonatomic) _Bool shouldDelayToastPopup;
- (_Bool)shouldTabBarBeHiddenForController:(id)arg1;
- (_Bool)showingActivityToast;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (_Bool)splitViewExpanded;
- (void)switchUsersController:(id)arg1 tableViewDidSelectRowWithAuthenticatedUser:(id)arg2;
- (void)switchUsersController:(id)arg1 tableViewDidSelectRowWithIGDeviceBasedLoginAccount:(id)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)switchUsersControllerDidSelectAddAccountRow:(id)arg1;
- (void)switchUsersControllerDidSelectRowWithCurrentUser:(id)arg1;
@property(readonly, nonatomic) UIView *tabBar;
- (void)tabBarIsHiding;
- (void)toastCountsReceived:(id)arg1;
- (void)updateTabBarButtonsToSelectedItem:(long long)arg1;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void)viewController:(id)arg1 didFinishInitializingWithSuccess:(_Bool)arg2;
- (void)viewController:(id)arg1 logDataPoint:(id)arg2;
- (void)viewControllerDidFinishAllNetworkingRequests:(id)arg1;
@property(readonly, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

