//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGTabSwitcher;

@protocol IGTabSwitcherDelegate <NSObject>
- (void)IGTabSwitcher:(IGTabSwitcher *)arg1 didSelectIndex:(unsigned long long)arg2;
@end

