//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGTableViewCell.h"

@class IGFollowButton, IGProfilePictureImageView, IGUser;

@interface IGThreadInfoUserTableViewCell : IGTableViewCell
{
    IGUser *_user;
    IGFollowButton *_followButton;
    IGProfilePictureImageView *_profilePicture;
}

+ (double)cellHeight;
- (void).cxx_destruct;
- (void)configureWithUser:(id)arg1 userSession:(id)arg2;
@property(readonly, nonatomic) IGFollowButton *followButton; // @synthesize followButton=_followButton;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) IGProfilePictureImageView *profilePicture; // @synthesize profilePicture=_profilePicture;
@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;

@end

