//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedNetworkSource, IGFeedScrollViewAnnouncer, IGListAdapter, IGUserSession, IGViewController<IGAnalyticsModule>, UICollectionView;

@interface IGToggleFeedCollectionViewLayoutManagerToolbox : NSObject
{
    IGViewController<IGAnalyticsModule> *_viewController;
    IGUserSession *_userSession;
    UICollectionView *_collectionView;
    IGListAdapter *_listAdapter;
    IGFeedNetworkSource *_feedNetworkSource;
    IGFeedScrollViewAnnouncer *_scrollViewAnnouncer;
    id <IGFeedConfigurationType> _feedConfiguration;
    id <IGFeedItemConfigurationType> _itemConfiguration;
    double _topContentInset;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) id <IGFeedConfigurationType> feedConfiguration; // @synthesize feedConfiguration=_feedConfiguration;
@property(readonly, nonatomic) IGFeedNetworkSource *feedNetworkSource; // @synthesize feedNetworkSource=_feedNetworkSource;
- (id)initWithUserSession:(id)arg1 viewController:(id)arg2 collectionView:(id)arg3 listAdapter:(id)arg4 feedNetworkSource:(id)arg5 scrollViewAnnouncer:(id)arg6 feedConfiguration:(id)arg7 itemConfiguration:(id)arg8;
- (id)initWithUserSession:(id)arg1 viewController:(id)arg2 collectionView:(id)arg3 listAdapter:(id)arg4 feedNetworkSource:(id)arg5 scrollViewAnnouncer:(id)arg6 feedConfiguration:(id)arg7 itemConfiguration:(id)arg8 topContentInset:(double)arg9;
@property(readonly, nonatomic) id <IGFeedItemConfigurationType> itemConfiguration; // @synthesize itemConfiguration=_itemConfiguration;
@property(readonly, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
@property(readonly, nonatomic) IGFeedScrollViewAnnouncer *scrollViewAnnouncer; // @synthesize scrollViewAnnouncer=_scrollViewAnnouncer;
@property(readonly, nonatomic) double topContentInset; // @synthesize topContentInset=_topContentInset;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) __weak IGViewController<IGAnalyticsModule> *viewController; // @synthesize viewController=_viewController;

@end

