//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGTranslationNetworkDataSource, NSDictionary, NSError;

@protocol IGTranslationNetworkDataSourceDelegate
- (void)translationNetworkDataSource:(IGTranslationNetworkDataSource *)arg1 didFailWithError:(NSError *)arg2;
- (void)translationNetworkDataSource:(IGTranslationNetworkDataSource *)arg1 didLoadTranslations:(NSDictionary *)arg2;
@end

