//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStorableObject.h"

@class IGHashtagModel, NSArray, NSString;

@interface IGTrendingHashtag : IGStorableObject
{
    NSArray *_mediaBundles;
    NSString *_name;
    NSString *_title;
    NSString *_subtitle;
    NSString *_byline;
    unsigned long long _taggedNumber;
}

+ (id)centralizedStore;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *byline; // @synthesize byline=_byline;
@property(readonly, copy, nonatomic) NSArray *mediaBundles; // @synthesize mediaBundles=_mediaBundles;
@property(readonly, nonatomic) IGHashtagModel *model;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) unsigned long long taggedNumber; // @synthesize taggedNumber=_taggedNumber;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (_Bool)updateWithDictionary:(id)arg1;

@end

