//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class NSString;

@interface IGUserSessionClassRegistry : NSObject <IGUserSessionClearableObject>
{
}

+ (void)clearForUserPK:(id)arg1;
+ (id)inMemoryStoresThatCacheUserData;
+ (id)storesThatCacheUserData;
+ (id)storesToClearAfterApplicationCrash;
- (void)willLogOut;
- (void)willSwitchUsers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

