//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGUserInvalidationHelper : NSObject
{
}

+ (void)invalidateUser:(id)arg1;
+ (_Bool)shouldUserDisplay:(id)arg1;
+ (void)validateUser:(id)arg1;

@end

