//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, IGVideoConfiguration, NSObject<OS_dispatch_queue>, NSString, NSURL;

@interface IGVideoWriter : NSObject
{
    _Bool _optimizeVideoForNetwork;
    _Bool _videoWritingIsFinished;
    _Bool _audioWritingIsFinished;
    _Bool _isFastVideo;
    id <IGVideoWriterDelegate> _delegate;
    double _progress;
    NSURL *_outputFileURL;
    AVAssetWriter *_assetWriter;
    AVAssetWriterInput *_videoWriterInput;
    AVAssetWriterInput *_audioWriterInput;
    AVAssetWriterInputPixelBufferAdaptor *_bufferAdaptor;
    NSObject<OS_dispatch_queue> *_videoQueue;
    NSObject<OS_dispatch_queue> *_audioQueue;
    IGVideoConfiguration *_videoConfiguration;
    NSString *_locationMetadataName;
    struct CGSize _size;
    CDStruct_1b6d18a9 _videoDuration;
    struct CGAffineTransform _transform;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVAssetWriter *assetWriter; // @synthesize assetWriter=_assetWriter;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *audioQueue; // @synthesize audioQueue=_audioQueue;
@property(retain, nonatomic) AVAssetWriterInput *audioWriterInput; // @synthesize audioWriterInput=_audioWriterInput;
@property(nonatomic) _Bool audioWritingIsFinished; // @synthesize audioWritingIsFinished=_audioWritingIsFinished;
@property(retain, nonatomic) AVAssetWriterInputPixelBufferAdaptor *bufferAdaptor; // @synthesize bufferAdaptor=_bufferAdaptor;
@property(nonatomic) __weak id <IGVideoWriterDelegate> delegate; // @synthesize delegate=_delegate;
- (double)getVideoBitRate;
- (id)initWithVideoConfiguration:(id)arg1 size:(struct CGSize)arg2 duration:(CDStruct_1b6d18a9)arg3 isFastVideo:(_Bool)arg4 locationMetadataName:(id)arg5 transform:(struct CGAffineTransform)arg6;
@property(readonly, nonatomic) _Bool isFastVideo; // @synthesize isFastVideo=_isFastVideo;
@property(readonly, nonatomic) NSString *locationMetadataName; // @synthesize locationMetadataName=_locationMetadataName;
@property(nonatomic) _Bool optimizeVideoForNetwork; // @synthesize optimizeVideoForNetwork=_optimizeVideoForNetwork;
@property(retain, nonatomic) NSURL *outputFileURL; // @synthesize outputFileURL=_outputFileURL;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *videoQueue; // @synthesize videoQueue=_videoQueue;
@property(retain, nonatomic) AVAssetWriterInput *videoWriterInput; // @synthesize videoWriterInput=_videoWriterInput;
@property(nonatomic) _Bool videoWritingIsFinished; // @synthesize videoWritingIsFinished=_videoWritingIsFinished;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
- (void)startWriting;
@property(readonly, nonatomic) struct CGAffineTransform transform; // @synthesize transform=_transform;
@property(readonly, nonatomic) IGVideoConfiguration *videoConfiguration; // @synthesize videoConfiguration=_videoConfiguration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 videoDuration; // @synthesize videoDuration=_videoDuration;

@end

