//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVQueuePlayer, IGKVOHandle, NSObject<OS_dispatch_queue>, NSString, UILabel;

@interface IGVideoPlayerTargetView : UIView
{
    NSObject<OS_dispatch_queue> *_workingQueue;
    id <IGVideoPlayerTargetViewDelegate> _delegate;
    IGKVOHandle *_readyToDisplayObserver;
    IGKVOHandle *_playerRateObserver;
    id _playerPlaybackObserver;
    UIView *_debugOverlay;
    UILabel *_debugLabel;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) UILabel *debugLabel; // @synthesize debugLabel=_debugLabel;
@property(retain, nonatomic) UIView *debugOverlay; // @synthesize debugOverlay=_debugOverlay;
@property(copy, nonatomic) NSString *debugText;
@property(nonatomic) __weak id <IGVideoPlayerTargetViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1 workingQueue:(id)arg2;
@property(retain, nonatomic) AVQueuePlayer *player;
@property(retain, nonatomic) id playerPlaybackObserver; // @synthesize playerPlaybackObserver=_playerPlaybackObserver;
@property(retain, nonatomic) IGKVOHandle *playerRateObserver; // @synthesize playerRateObserver=_playerRateObserver;
@property(retain, nonatomic) IGKVOHandle *readyToDisplayObserver; // @synthesize readyToDisplayObserver=_readyToDisplayObserver;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workingQueue; // @synthesize workingQueue=_workingQueue;
- (void)setupDebugOverlay;
- (_Bool)shouldDeallocInWorkingQueue;
- (void)updateVideoInfoVisibility;

@end

