//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface IGVideoLoadProgressView : UIView
{
    double _progress;
    double _playbackProgress;
    double _duration;
    UIView *_progressView;
    UIView *_playbackProgressView;
    double _frameHeight;
    UILabel *_progressLabel;
}

- (void).cxx_destruct;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double frameHeight; // @synthesize frameHeight=_frameHeight;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double playbackProgress; // @synthesize playbackProgress=_playbackProgress;
@property(retain, nonatomic) UIView *playbackProgressView; // @synthesize playbackProgressView=_playbackProgressView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UILabel *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
- (void)reset;

@end

