//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGVideoCell;

@protocol IGVideoCellDelegate <NSObject>
- (void)videoCell:(IGVideoCell *)arg1 didToggleAudio:(_Bool)arg2;
- (void)videoCellDidDoubleTap:(IGVideoCell *)arg1;
- (void)videoCellDidLoadImage:(IGVideoCell *)arg1;
- (void)videoCellDidSingleTap:(IGVideoCell *)arg1;
@end

