//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIViewController;

@protocol IGViewControllerInitializationDelegate <NSObject>
- (void)viewController:(UIViewController *)arg1 didFinishInitializingWithSuccess:(_Bool)arg2;
- (void)viewController:(UIViewController *)arg1 logDataPoint:(NSString *)arg2;
- (void)viewControllerDidFinishAllNetworkingRequests:(UIViewController *)arg1;
@end

