//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGAudioIndicatorButton, IGSimpleButton, IGVideoGlyphView;

@interface IGVideoIndicatorView : UIView
{
    UIView *_glyphView;
    IGSimpleButton *_playGlyph;
    IGSimpleButton *_pauseGlyph;
    IGSimpleButton *_errorGlyph;
    IGVideoGlyphView *_videoGlyph;
    _Bool _disableIndicator;
    long long _indicatorState;
    IGAudioIndicatorButton *_audioButton;
}

- (void).cxx_destruct;
- (id)accessibilityButtons;
@property(retain, nonatomic) IGAudioIndicatorButton *audioButton; // @synthesize audioButton=_audioButton;
@property(nonatomic) _Bool disableIndicator; // @synthesize disableIndicator=_disableIndicator;
@property(nonatomic) long long indicatorState; // @synthesize indicatorState=_indicatorState;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setAccessibilityLabel:(id)arg1;
- (void)setAccessibilityTraits:(unsigned long long)arg1;
- (void)showGlyph:(_Bool)arg1 animated:(_Bool)arg2 duration:(double)arg3 delay:(double)arg4 completion:(CDUnknownBlockType)arg5;

@end

