//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGVideoPlaybackController, IGVideoPlaybackItem;

@protocol IGVideoPlaybackControllerProgressDelegate <NSObject>
- (void)videoPlaybackController:(IGVideoPlaybackController *)arg1 didUpdatePlaybackProgressForItem:(IGVideoPlaybackItem *)arg2 progress:(double)arg3;
@end

