//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGWatchAndActionPresentationAnimatorDelegate.h"
#import "IGWatchAndBrowseViewControllerDelegate.h"
#import "IGWatchAndInstallViewControllerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class IGBrowserController, IGDirectResponseLogger, IGFeedItem, IGFeedItemActionCellState, IGFeedVideoCellManager, IGUserSession, IGVideoPlaybackConfiguration, IGWatchAndActionPresentationAnimator, IGWatchAndBrowseViewController, IGWatchAndInstallViewController, NSString, UICollectionViewCell<IGFeedVideoCell>, UINavigationController, UIView;

@interface IGWatchAndActionController : NSObject <IGWatchAndActionPresentationAnimatorDelegate, IGWatchAndBrowseViewControllerDelegate, IGWatchAndInstallViewControllerDelegate, UIViewControllerTransitioningDelegate>
{
    _Bool _presenting;
    _Bool _presented;
    _Bool _useWatchAndInstallV2;
    _Bool _dismissing;
    _Bool _statusBarHiddenForTopViewController;
    IGUserSession *_userSession;
    id <IGFeedItemLoggingProviderDelegate><IGFeedItemDirectResponseLoggingProviderDelegate> _loggingProvider;
    UINavigationController *_navigationController;
    IGFeedVideoCellManager *_videoCellManager;
    UIView *_videoContentView;
    UICollectionViewCell<IGFeedVideoCell> *_videoCell;
    IGFeedItem *_feedItem;
    IGDirectResponseLogger *_directResponseLogger;
    IGFeedItemActionCellState *_actionCellState;
    IGVideoPlaybackConfiguration *_playbackConfig;
    IGWatchAndActionPresentationAnimator *_presentationAnimator;
    double _currentVideoPlayingTime;
    unsigned long long _watchAndActionType;
    IGBrowserController *_browserController;
    IGWatchAndBrowseViewController *_watchAndBrowseViewController;
    IGWatchAndInstallViewController *_watchAndInstallViewController;
    struct CGRect _cellFrameInFeed;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) IGFeedItemActionCellState *actionCellState; // @synthesize actionCellState=_actionCellState;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) IGBrowserController *browserController; // @synthesize browserController=_browserController;
@property(readonly, nonatomic) struct CGRect cellFrameInFeed; // @synthesize cellFrameInFeed=_cellFrameInFeed;
@property(nonatomic) double currentVideoPlayingTime; // @synthesize currentVideoPlayingTime=_currentVideoPlayingTime;
@property(readonly, nonatomic) IGDirectResponseLogger *directResponseLogger; // @synthesize directResponseLogger=_directResponseLogger;
- (void)dismiss;
- (void)dismissWatchAndBrowse;
- (void)dismissWatchAndBrowseViewController:(id)arg1;
- (void)dismissWatchAndInstall;
- (void)dismissWatchAndInstallViewController:(id)arg1;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (id)initWithNavigationController:(id)arg1 videoCellManager:(id)arg2 videoCell:(id)arg3 feedItem:(id)arg4 loggingProvider:(id)arg5 directResponseLogger:(id)arg6 actionCellState:(id)arg7 userSession:(id)arg8;
@property(nonatomic, getter=isDismissing) _Bool dismissing; // @synthesize dismissing=_dismissing;
@property(nonatomic, getter=isPresented) _Bool presented; // @synthesize presented=_presented;
@property(nonatomic, getter=isPresenting) _Bool presenting; // @synthesize presenting=_presenting;
@property(nonatomic, getter=isStatusBarHiddenForTopViewController) _Bool statusBarHiddenForTopViewController; // @synthesize statusBarHiddenForTopViewController=_statusBarHiddenForTopViewController;
@property(readonly, nonatomic) __weak id <IGFeedItemLoggingProviderDelegate><IGFeedItemDirectResponseLoggingProviderDelegate> loggingProvider; // @synthesize loggingProvider=_loggingProvider;
- (void)moveVideoViewToFeed;
@property(readonly, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(readonly, nonatomic) IGVideoPlaybackConfiguration *playbackConfig; // @synthesize playbackConfig=_playbackConfig;
- (void)present;
- (void)presentWatchAndBrowse;
- (void)presentWatchAndInstall;
@property(retain, nonatomic) IGWatchAndActionPresentationAnimator *presentationAnimator; // @synthesize presentationAnimator=_presentationAnimator;
- (void)presentationAnimatorDidFinishAnimating:(id)arg1 isDismissal:(_Bool)arg2;
- (void)presentationAnimatorDidStartAnimating:(id)arg1 isDismissal:(_Bool)arg2;
@property(nonatomic) _Bool useWatchAndInstallV2; // @synthesize useWatchAndInstallV2=_useWatchAndInstallV2;
@property(nonatomic) unsigned long long watchAndActionType; // @synthesize watchAndActionType=_watchAndActionType;
@property(retain, nonatomic) IGWatchAndBrowseViewController *watchAndBrowseViewController; // @synthesize watchAndBrowseViewController=_watchAndBrowseViewController;
@property(retain, nonatomic) IGWatchAndInstallViewController *watchAndInstallViewController; // @synthesize watchAndInstallViewController=_watchAndInstallViewController;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) UICollectionViewCell<IGFeedVideoCell> *videoCell; // @synthesize videoCell=_videoCell;
@property(readonly, nonatomic) IGFeedVideoCellManager *videoCellManager; // @synthesize videoCellManager=_videoCellManager;
@property(readonly, nonatomic) UIView *videoContentView; // @synthesize videoContentView=_videoContentView;
- (void)watchAndBrowseViewController:(id)arg1 setPlayVideo:(_Bool)arg2;
- (void)watchAndInstallViewController:(id)arg1 setPlayVideo:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

