//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGRetroRegistrationBackgroundView, UIButton, UIImageView, UILabel;

@interface IGWelcomeViewBackgroundView : UIView
{
    UIView *_canvasView;
    IGRetroRegistrationBackgroundView *_backgroundView;
    UIImageView *_brandView;
    UILabel *_brandValuePropositionLabel;
    UIView *_footerViewSeperator;
    UIView *_footerView;
    UIButton *_firstActionButton;
    UIButton *_secondActionButton;
    UILabel *_textLabel;
    long long _viewType;
    struct CGPoint _brandViewOrigin;
    struct CGRect _canvasViewOriginalFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IGRetroRegistrationBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *brandValuePropositionLabel; // @synthesize brandValuePropositionLabel=_brandValuePropositionLabel;
@property(retain, nonatomic) UIImageView *brandView; // @synthesize brandView=_brandView;
@property(nonatomic) struct CGPoint brandViewOrigin; // @synthesize brandViewOrigin=_brandViewOrigin;
@property(retain, nonatomic) UIView *canvasView; // @synthesize canvasView=_canvasView;
@property(nonatomic) struct CGRect canvasViewOriginalFrame; // @synthesize canvasViewOriginalFrame=_canvasViewOriginalFrame;
- (id)createBrandValuePropositionLabel;
- (id)createFooterViewSeparator;
- (id)createFooterViewWithFirstActionButton:(id)arg1 textLabel:(id)arg2 secondActionButton:(id)arg3;
- (struct CGRect)desiredCanvasViewFrame;
@property(retain, nonatomic) UIButton *firstActionButton; // @synthesize firstActionButton=_firstActionButton;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
- (struct CGRect)footerViewFrame;
@property(retain, nonatomic) UIView *footerViewSeperator; // @synthesize footerViewSeperator=_footerViewSeperator;
- (id)initWithFrame:(struct CGRect)arg1 viewType:(long long)arg2;
- (_Bool)isTouchOnLoginButton:(struct CGPoint)arg1;
- (_Bool)isTouchOnSignUpButton:(struct CGPoint)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)layoutFooterView;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIButton *loginButton;
@property(retain, nonatomic) UIButton *secondActionButton; // @synthesize secondActionButton=_secondActionButton;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
- (_Bool)shouldHaveBrandValuePropositionLabel;
- (_Bool)shouldHaveBrandView;
@property(readonly, nonatomic) UIButton *signUpButton;

@end

