//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@interface RCTActivityIndicatorViewManager : RCTViewManager
{
}

+ (void)load;
+ (id)moduleName;
+ (id)propConfig_animating;
+ (id)propConfig_color;
+ (id)propConfig_hidesWhenStopped;
+ (id)propConfig_size;
- (void)set_animating:(id)arg1 forView:(id)arg2 withDefaultView:(id)arg3;
- (id)view;

@end

