//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTInvalidating.h"
#import "RCTReloadListener.h"

@class NSArray, NSDictionary, NSLock, NSString, NSURL, RCTAccessibilityManager, RCTDevMenu, RCTImageLoader, RCTImageStoreManager, RCTNetworking, RCTPerformanceLogger, RCTRedBox, RCTUIManager;

@interface RCTBridge : NSObject <RCTReloadListener, RCTInvalidating>
{
    NSURL *_delegateBundleURL;
    NSURL *_bundleURL;
    Class _executorClass;
    id <RCTBridgeDelegate> _delegate;
    NSDictionary *_launchOptions;
    RCTPerformanceLogger *_performanceLogger;
    long long _flowID;
    struct __CFDictionary *_flowIDMap;
    NSLock *_flowIDMapLock;
    RCTBridge *_batchedBridge;
    CDUnknownBlockType _moduleProvider;
}

+ (id)currentBridge;
+ (void)initialize;
+ (void)setCurrentBridge:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) RCTAccessibilityManager *accessibilityManager;
@property(retain) RCTBridge *batchedBridge; // @synthesize batchedBridge=_batchedBridge;
- (void)bindKeys;
@property(retain, nonatomic) NSURL *bundleURL; // @synthesize bundleURL=_bundleURL;
- (id)callFunctionOnModule:(id)arg1 method:(id)arg2 arguments:(id)arg3 error:(id *)arg4;
- (void)createBatchedBridge;
- (void)dealloc;
@property(readonly, nonatomic) __weak id <RCTBridgeDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) RCTDevMenu *devMenu;
- (void)didReceiveReloadCommand;
- (void)enqueueCallback:(id)arg1 args:(id)arg2;
- (void)enqueueJSCall:(id)arg1 args:(id)arg2;
- (void)enqueueJSCall:(id)arg1 method:(id)arg2 args:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)eventDispatcher;
@property(retain, nonatomic) Class executorClass; // @synthesize executorClass=_executorClass;
@property(nonatomic) long long flowID; // @synthesize flowID=_flowID;
@property(nonatomic) struct __CFDictionary *flowIDMap; // @synthesize flowIDMap=_flowIDMap;
@property(retain, nonatomic) NSLock *flowIDMapLock; // @synthesize flowIDMapLock=_flowIDMapLock;
@property(readonly, nonatomic) RCTImageLoader *imageLoader;
@property(readonly, nonatomic) RCTImageStoreManager *imageStoreManager;
- (id)init;
- (id)initWithBundleURL:(id)arg1 moduleProvider:(CDUnknownBlockType)arg2 launchOptions:(id)arg3;
- (id)initWithDelegate:(id)arg1 bundleURL:(id)arg2 moduleProvider:(CDUnknownBlockType)arg3 launchOptions:(id)arg4;
- (id)initWithDelegate:(id)arg1 launchOptions:(id)arg2;
- (void)invalidate;
- (_Bool)isBatchActive;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
@property(readonly, copy, nonatomic) NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property(readonly, copy, nonatomic) NSArray *moduleClasses;
- (id)moduleForClass:(Class)arg1;
- (id)moduleForName:(id)arg1;
- (_Bool)moduleIsInitialized:(Class)arg1;
@property(readonly, copy, nonatomic) CDUnknownBlockType moduleProvider; // @synthesize moduleProvider=_moduleProvider;
- (id)modulesConformingToProtocol:(id)arg1;
@property(readonly, nonatomic) RCTNetworking *networking;
@property(readonly, nonatomic) RCTPerformanceLogger *performanceLogger; // @synthesize performanceLogger=_performanceLogger;
@property(readonly, nonatomic) RCTRedBox *redBox;
- (void)reload;
- (void)requestReload;
- (void)setUp;
@property(readonly, nonatomic) RCTUIManager *uiManager;
- (void)whitelistedModulesDidChange;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

