//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

#import "RCTInvalidating.h"
#import "RCTModalHostViewInteractor.h"

@class NSHashTable, NSString;

@interface RCTModalHostViewManager : RCTViewManager <RCTModalHostViewInteractor, RCTInvalidating>
{
    NSHashTable *_hostViews;
    CDUnknownBlockType _presentationBlock;
    CDUnknownBlockType _dismissalBlock;
}

+ (void)load;
+ (id)moduleName;
+ (id)propConfig_animationType;
+ (id)propConfig_onOrientationChange;
+ (id)propConfig_onShow;
+ (id)propConfig_supportedOrientations;
+ (id)propConfig_transparent;
- (void).cxx_destruct;
- (void)dismissModalHostView:(id)arg1 withViewController:(id)arg2 animated:(_Bool)arg3;
@property(copy, nonatomic) CDUnknownBlockType dismissalBlock; // @synthesize dismissalBlock=_dismissalBlock;
- (void)invalidate;
- (void)presentModalHostView:(id)arg1 withViewController:(id)arg2 animated:(_Bool)arg3;
@property(copy, nonatomic) CDUnknownBlockType presentationBlock; // @synthesize presentationBlock=_presentationBlock;
- (id)shadowView;
- (id)view;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

