//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTAnimatedNode.h"

@class NSMutableDictionary;

@interface RCTStyleAnimatedNode : RCTAnimatedNode
{
    NSMutableDictionary *_propsDictionary;
}

- (void).cxx_destruct;
- (id)initWithTag:(id)arg1 config:(id)arg2;
- (void)performUpdate;
- (id)propsDictionary;

@end

