//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISwitch.h"

@interface RCTSwitch : UISwitch
{
    _Bool _wasOn;
    CDUnknownBlockType _onChange;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType onChange; // @synthesize onChange=_onChange;
- (void)setOn:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool wasOn; // @synthesize wasOn=_wasOn;

@end

