//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTView.h"

#import "UITextViewDelegate.h"

@class NSAttributedString, NSNumber, NSString, RCTEventDispatcher, RCTText, UIColor, UIFont, UIScrollView, UITextRange, UITextView;

@interface RCTTextView : RCTView <UITextViewDelegate>
{
    RCTEventDispatcher *_eventDispatcher;
    NSString *_placeholder;
    UITextView *_placeholderView;
    UITextView *_textView;
    RCTText *_richTextView;
    NSAttributedString *_pendingAttributedText;
    UIScrollView *_scrollView;
    UITextRange *_previousSelectionRange;
    unsigned long long _previousTextLength;
    double _previousContentHeight;
    NSString *_predictedText;
    _Bool _blockTextShouldChange;
    _Bool _nativeUpdatesInFlight;
    long long _nativeEventCount;
    struct CGSize _previousContentSize;
    _Bool _viewDidCompleteInitialLayout;
    _Bool _blurOnSubmit;
    _Bool _clearTextOnFocus;
    _Bool _selectTextOnFocus;
    _Bool _automaticallyAdjustContentInsets;
    UIColor *_placeholderTextColor;
    long long _mostRecentEventCount;
    NSNumber *_maxLength;
    CDUnknownBlockType _onChange;
    CDUnknownBlockType _onContentSizeChange;
    CDUnknownBlockType _onSelectionChange;
    CDUnknownBlockType _onTextInput;
    CDUnknownBlockType _onScroll;
    struct UIEdgeInsets _contentInset;
}

- (void).cxx_destruct;
@property(nonatomic) long long autocorrectionType;
@property(nonatomic) _Bool automaticallyAdjustContentInsets; // @synthesize automaticallyAdjustContentInsets=_automaticallyAdjustContentInsets;
- (_Bool)becomeFirstResponder;
@property(nonatomic) _Bool blurOnSubmit; // @synthesize blurOnSubmit=_blurOnSubmit;
- (_Bool)canBecomeFirstResponder;
@property(nonatomic) _Bool clearTextOnFocus; // @synthesize clearTextOnFocus=_clearTextOnFocus;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
- (void)dealloc;
- (id)defaultPlaceholderFont;
- (id)defaultPlaceholderTextColor;
- (void)didUpdateReactSubviews;
@property(retain, nonatomic) UIFont *font;
- (id)initWithCoder:(id)arg1;
- (id)initWithEventDispatcher:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)insertReactSubview:(id)arg1 atIndex:(long long)arg2;
- (_Bool)isFirstResponder;
- (void)layoutSubviews;
@property(retain, nonatomic) NSNumber *maxLength; // @synthesize maxLength=_maxLength;
@property(nonatomic) long long mostRecentEventCount; // @synthesize mostRecentEventCount=_mostRecentEventCount;
@property(copy, nonatomic) CDUnknownBlockType onChange; // @synthesize onChange=_onChange;
@property(copy, nonatomic) CDUnknownBlockType onContentSizeChange; // @synthesize onContentSizeChange=_onContentSizeChange;
@property(copy, nonatomic) CDUnknownBlockType onScroll; // @synthesize onScroll=_onScroll;
@property(copy, nonatomic) CDUnknownBlockType onSelectionChange; // @synthesize onSelectionChange=_onSelectionChange;
@property(copy, nonatomic) CDUnknownBlockType onTextInput; // @synthesize onTextInput=_onTextInput;
- (void)performPendingTextUpdate;
- (void)performTextUpdate;
@property(retain, nonatomic) UIColor *placeholderTextColor; // @synthesize placeholderTextColor=_placeholderTextColor;
- (void)reactDidMakeFirstResponder;
- (void)reactWillMakeFirstResponder;
- (void)removeReactSubview:(id)arg1;
- (_Bool)resignFirstResponder;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) _Bool selectTextOnFocus; // @synthesize selectTextOnFocus=_selectTextOnFocus;
- (void)setPlaceholder:(id)arg1;
- (void)setSelection:(id)arg1;
@property(nonatomic) long long spellCheckingType;
@property(copy, nonatomic) NSString *text;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)updateContentSize;
- (void)updateFrames;
- (void)updatePlaceholder;
- (void)updatePlaceholderVisibility;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

