//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@interface RCTTabBarManager : RCTViewManager
{
}

+ (void)load;
+ (id)moduleName;
+ (id)propConfig_barTintColor;
+ (id)propConfig_itemPositioning;
+ (id)propConfig_tintColor;
+ (id)propConfig_translucent;
+ (id)propConfig_unselectedItemTintColor;
+ (id)propConfig_unselectedTintColor;
- (id)view;

@end

