//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@interface RCTTextManager : RCTViewManager
{
}

+ (void)load;
+ (id)moduleName;
+ (id)propConfigShadow_adjustsFontSizeToFit;
+ (id)propConfigShadow_allowFontScaling;
+ (id)propConfigShadow_color;
+ (id)propConfigShadow_ellipsizeMode;
+ (id)propConfigShadow_fontFamily;
+ (id)propConfigShadow_fontSize;
+ (id)propConfigShadow_fontStyle;
+ (id)propConfigShadow_fontVariant;
+ (id)propConfigShadow_fontWeight;
+ (id)propConfigShadow_isHighlighted;
+ (id)propConfigShadow_letterSpacing;
+ (id)propConfigShadow_lineHeight;
+ (id)propConfigShadow_minimumFontScale;
+ (id)propConfigShadow_numberOfLines;
+ (id)propConfigShadow_opacity;
+ (id)propConfigShadow_selectable;
+ (id)propConfigShadow_textAlign;
+ (id)propConfigShadow_textDecorationColor;
+ (id)propConfigShadow_textDecorationLine;
+ (id)propConfigShadow_textDecorationStyle;
+ (id)propConfigShadow_textShadowColor;
+ (id)propConfigShadow_textShadowOffset;
+ (id)propConfigShadow_textShadowRadius;
+ (id)propConfigShadow_writingDirection;
- (id)shadowView;
- (CDUnknownBlockType)uiBlockToAmendWithShadowView:(id)arg1;
- (CDUnknownBlockType)uiBlockToAmendWithShadowViewRegistry:(id)arg1;
- (id)view;

@end

