//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface Tool : NSObject
{
    NSString *_title;
    UIImage *_icon;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (id)initWithTitle:(id)arg1 icon:(id)arg2;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

