//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Round)
+ (id)ig_resizableRoundedRectWithCornerRadius:(double)arg1 fillColor:(id)arg2;
+ (id)losengeWithSize:(struct CGSize)arg1 fillColor:(id)arg2 borderColor:(id)arg3 borderWidth:(double)arg4;
+ (id)losengeWithSize:(struct CGSize)arg1 fillColor:(id)arg2 borderColor:(id)arg3 borderWidth:(double)arg4 drawnBehindImage:(id)arg5;
+ (id)roundedRectWithSize:(struct CGSize)arg1 fillColor:(id)arg2 cornerRadius:(double)arg3 borderColor:(id)arg4 borderWidth:(double)arg5 drawnBehindImage:(id)arg6;
- (id)imageWithRoundedBackgroundColor:(id)arg1 andSize:(struct CGSize)arg2;
- (id)roundedImageOfSize:(struct CGSize)arg1 borderColor:(id)arg2 borderWidth:(double)arg3 backgroundColor:(id)arg4;
@end

